### ISSUE TITLE
ECR Repository Attribute `RepositoryUri` Cannot be Referenced in Other Resources

### ISSUE THREAD

**Issue by jacky96623** [aws-cloudformation/cloudformation-coverage-roadmap#1033]
### Name of the resource

AWS::ECR::Repository

### Issue Description

According to <https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/124#issuecomment-861642127> and <https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-return-values>, AWS already enabled the feature that a repository's URI can be directly referenced in **Outputs** from a `AWS::ECR::Repository` resource.

However, when I try to reference it in other resources by `Fn::Sub` or `Fn::GetAtt`, the following error occurs:
```
Template error: instance of  references invalid resource attribute repo.RepositoryUri
```

### Expected Behavior

A repository's URI can be referenced in other resources e.g. ECS task definition.

### Observed Behavior

A repository's URI can only be referenced in output.

### Test Cases

The following CloudFormation template should be able to reproduce the stated error:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  taskExecutionRoleArn:
    Type: String
Resources:
  repo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: test-image
  taskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: test-task-def
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
        - EC2
      ExecutionRoleArn: !Ref taskExecutionRoleArn
      Memory: 512
      Cpu: 256
      ContainerDefinitions:
        - Name: test
          Image: !Sub ${repo.RepositoryUri}
```

**Comment by bradg-aws** [comment]
Hi, thanks for raising the issue, and appreciate the details.

Using the test case template, I was able to create a stack successfully. I was also able to verify that the task definition was created with the proper repository Uri under image. 

Is there something I'm missing maybe?

**Comment by jacky96623** [comment]
Hi, thanks for the prompt response. I am sorry that I gave a template which does not reproduce the issue - it was because my original CloudFormation stack is more complicated and I want the example to be lighter.

The actual template which can reproduce the issue should look like this:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  taskExecutionRoleArn:
    Type: String
  repoURL:
    Type: String
    Default: ''

Conditions:
  createRepo: !Equals
    - !Ref repoURL
    - ''

Resources:
  repo:
    Condition: createRepo
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: test-image
  taskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: test-task-def
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
        - EC2
      ExecutionRoleArn: !Ref taskExecutionRoleArn
      Memory: 512
      Cpu: 256
      ContainerDefinitions:
        - Name: test
          Image: !If 
            - createRepo
            - !Sub ${repo.RepositoryUri}
            - !Ref repoURL
```

And the `repoURL` parameter should be set with non-empty value.

As a result, the CloudFormation console will show something like this:
![image](https://user-images.githubusercontent.com/37379550/150630243-ee6ec4e4-9fe9-432a-9806-ce7014637209.png)

**Comment by cappellaiomatto** [comment]
I'd use !GetAtt instead of !Sub

```
          Image: !If 
            - createRepo
            - !GetAtt repo.RepositoryUri
            - !Ref repoURL
```

**Comment by cappellaiomatto** [comment]
Then you'd better do something like:
```
- !Join [":", [!GetAtt repo.RepositoryUri, !Ref myTag]]
```

**Comment by jacky96623** [comment]
> Then you'd better do something like:
> 
> ```
> - !Join [":", [!GetAtt repo.RepositoryUri, !Ref myTag]]
> ```

Thanks for your advice, but is it something proved to work?

**Comment by bradg-aws** [comment]
Hi @jacky96623
I have used the second template you provided with a null repoURL parameter and it works as expected. 
Why are you attempting to pass in a repoUrl?

Won't your condition fail if you enter in a repoUrl, meaning the repo isn't created (and so there is no repo.RepositoryUri)?
```
Conditions:
  createRepo: !Equals
    - !Ref repoURL
    - ''
```

**Comment by jacky96623** [comment]
Hi @bradg-aws 

> Why are you attempting to pass in a repoUrl?

I was composing some CloudFormation boilerplate for ECS service. One aim is that others can create a service with existing resources, e.g. ECR repository, by passing them in parameters. I can achieve it for other resources, e.g. IAM role. So i think it might be a bug for the ECR repository case.

> Won't your condition fail if you enter in a repoUrl, meaning the repo isn't created (and so there is no repo.RepositoryUri)?

I think it is on purpose as if user passes repoURL in (which refers to an external existing ECR repository), there is no need to create another ECR repository. And in this case, I expect the condition (as quoted below) will help to skip the null resources `repo` and just use the parameter `repoURL` instead.

> ```yaml
>         - Name: test
>           Image: !If 
>             - createRepo
>             - !Sub ${repo.RepositoryUri}
>             - !Ref repoURL
> ```

**Comment by bradg-aws** [comment]
Hi @jacky96623,

Thanks for the clarification.

To re-word the issue: repo.RepositoryUri can be referenced from the task definition if the repository was created.
This is seen in your first provided template and the second template if creating a repository.

Additionally, passing in the repoURL as a parameter works if you remove the conditional using `!Sub ${repo.RepositoryUri}` and just use the parameter directly. 

The problem then is in the conditional handling if the repository isn't created. As the ECR repository resource isn't created in this case, repo.RepositoryUri isn't valid but the sub seems to be evaluated still. The same is true when using GetAtt as well.

**Comment by jacky96623** [comment]
> Hi @jacky96623,
> 
> Thanks for the clarification.
> 
> To re-word the issue: repo.RepositoryUri can be referenced from the task definition if the repository was created. This is seen in your first provided template and the second template if creating a repository.
> 
> Additionally, passing in the repoURL as a parameter works if you remove the conditional using `!Sub ${repo.RepositoryUri}` and just use the parameter directly.
> 
> The problem then is in the conditional handling if the repository isn't created. As the ECR repository resource isn't created in this case, repo.RepositoryUri isn't valid but the sub seems to be evaluated still. The same is true when using GetAtt as well.

Hi @bradg-aws , thanks for the precise wrapping up. I believe it is an unexpected behaviour because I could achieve similar thing with other resources like taskExecutionRole etc.

**Comment by bradg-aws** [comment]
Hi @jacky96623,

While we're still investigating the repositoryUri handling in the template conditional, could you use the following as a workaround: 
```
!Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${repoName}"
```


Example template: 

```
Parameters:
  taskExecutionRoleArn:
    Type: String
    Default: ''
  repoURL:
    Type: String
    Default: ''
  repoName:
    Type: String
    Default: 'test-image'

Conditions:
  createRepo: !Equals [!Ref repoURL, '']

Resources:
  repo:
    Condition: createRepo
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref repoName
  taskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: test-task-def
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
        - EC2
      ExecutionRoleArn: !Ref taskExecutionRoleArn
      Memory: 512
      Cpu: 256
      ContainerDefinitions:
        - Name: test
          Image: !If  [createRepo ,!Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${repoName}", !Ref repoURL]

 ```
