### ISSUE TITLE
CloudFormation 

### ISSUE THREAD

**Issue by saiteja313** [aws-cloudformation/cloudformation-coverage-roadmap#1049]
### Name of the resource

AWS::Backup::BackupVault

### Issue Description

CloudFormation fails to untag BackupVault resources when a stack is deleted with DeletionPolicy for BackupVault resource.

### Expected Behavior

1. create AWS::Backup::BackupVault resource using a CFN stack.
2. Configure retain resource deletion policy for AWS::Backup::BackupVault and delete the stack
3. AWS::Backup::BackupVault resource is now orphaned and `AWS::Backup::BackupVault` resource do NOT have tags aws:cloudformation:stackid... and stack name.

```
Resources:
    Vault:
        Type: AWS::Backup::BackupVault
        DeletionPolicy: Retain
        Properties:
            BackupVaultName: testing
```

### Observed Behavior

1. create AWS::Backup::BackupVault resource using a CFN stack.
2. Configure retain resource deletion policy for AWS::Backup::BackupVault and delete the stack
3. AWS::Backup::BackupVault resource is now orphaned and `AWS::Backup::BackupVault` resource do have tags aws:cloudformation:stackid... and stack name.

```
Resources:
    Vault:
        Type: AWS::Backup::BackupVault
        DeletionPolicy: Retain
        Properties:
            BackupVaultName: testing
```

### Test Cases

1. create AWS::Backup::BackupVault resource using a CFN stack.
2. Configure retain resource deletion policy for AWS::Backup::BackupVault and delete the stack
3. AWS::Backup::BackupVault resource is now orphaned and `AWS::Backup::BackupVault` resource do not have tags aws:cloudformation:stackid... and stack name.

```
Resources:
    Vault:
        Type: AWS::Backup::BackupVault
        DeletionPolicy: Retain
        Properties:
            BackupVaultName: testing
```
