### ISSUE TITLE
AWS::EKS::Addon - [EKS] Support --preserve parameter when deleting EKS addon

### ISSUE THREAD

**Issue by 0xlen** [aws-cloudformation/cloudformation-coverage-roadmap#1050]
### Name of the resource

AWS::EKS::Addon

### Resource name

AWS::EKS::Addon

### Description

EKS started to support a safe way to remove EKS addon by adding `--preserve` flag [1], which is included in EKS [DeleteAddon](https://docs.aws.amazon.com/eks/latest/APIReference/API_DeleteAddon.html#API_DeleteAddon_RequestParameters) API:

> --preserve
> Specifying this option preserves the add-on software on your cluster but Amazon EKS stops managing any settings for the add-on. If an IAM account is associated with the add-on, it is not removed.

But if using CloudFormation to manage EKS addon, it doesn't provide a smooth way to delete so it can cause impact to the cluster when removing critical component such as `vpc-cni`, `CoreDNS` ...etc. For instance, if I create a managed addon with following template:

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Addon:
    Type: AWS::EKS::Addon
    Properties: 
      AddonName: coredns
      AddonVersion: v1.8.0-eksbuild.1
      ClusterName: <My_CLUSTER>
```

The delete action just remove the CoreDNS deployment without preserving it in my EKS cluster and have no choice can keep it on CloudFormation side. This can lead potential cluster down risk and seems no workaround can prevent it when using CloudFormation to manage the addon. So it would be great if CloudFormation can support this property.

### Other Details

[1] https://github.com/aws/containers-roadmap/issues/1415#issuecomment-904770014
[2] https://github.com/aws/containers-roadmap/issues/1597
