### ISSUE TITLE
AWS::RDS::DBClusterParameterGroup - Updates that should require replacement don't work

### ISSUE THREAD

**Issue by pitkley** [aws-cloudformation/cloudformation-coverage-roadmap#1057]
### Name of the resource

AWS::RDS::DBClusterParameterGroup

### Issue Description

The [documentation for the `AWS::RDS::DBClusterParameterGroup` resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html) documents that modifying the `Description` and `Family` properties requires replacement of the resource, which sounds like the correct behaviour given there don't seem to be any RDS-APIs to apply these modifications.

Unfortunately CloudFormation does not perform the replacement in question, but instead marks modified resources as `UPDATE_COMPLETE` without having actually applied any modifications.

### Expected Behavior

Modifying either the `Description` or (more crucially) the `Family` fields should result in AWS CloudFormation replacing the resource, given that there are no APIs for modifying either value of a cluster parameter group.

### Observed Behavior

CloudFormation detects that there were changes to the resource if `Description` or `Family` were modified, but doesn't actually apply any modifications and doesn't perform any replacements.

### Test Cases

The following template is a (mostly) minimal reproducer for the issues. It contains the same resource, `DBClusterParameterGroup`, four times, where each definition represents an "iteration" in terms of which modifications have been performed.

Reproducing the bug is simple:

1. :heavy_check_mark: Deploy the template as is. On deployment success you will get a Aurora DB-cluster parameter-group compatible with Aurora MySQL 5.6 with the `character_set_client` parameter modified to have the value `utf8`.
2. :heavy_check_mark: Comment out the first `DBClusterParameterGroup` resource, uncomment the second one. Deploying this will correctly modify the already created group and set the `character_set_client` parameter to have the value `utf8mb4` instead.
3. :x: Comment out the second resource and uncomment the third, which should result in the group's description being modified (or rather a new group being created that has the new description).

    The changeset created for this change already shows "Replacement: false", indicating incorrect behaviour, and executing it confirms it: CFN transitions the resource into `UPDATE_IN_PROGRESS` and into `UPDATE_COMPLETE` within a few seconds, and a look into the RDS-console confirms that the description wasn't changed.

4. :x: Comment out the third resource and uncomment the fourth, which should result in a new group being created that changes the group's family to Aurora MySQL 5.7.

    The changeset created for this change already shows "Replacement: false", indicating incorrect behaviour, and executing it confirms it: CFN transitions the resource into `UPDATE_IN_PROGRESS` and into `UPDATE_COMPLETE` within a few seconds, and a look into the RDS-console confirms that the family wasn't changed.

    The group is now incompatible with an Aurora MySQL 5.7 RDS-cluster, although it be expected to work.

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS::RDS::DBClusterParameterGroup - issue reproducer'

Resources:
  # 1. Aurora MySQL5.6 compatible group, one parameter added
  # EXPECTED: group created and the `character_set_client` parameter will differ to the default group
  # ACTUAL:   -- matches --
  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora MySQL5.6 parameter group
      Family: aurora5.6
      Parameters:
        character_set_client: utf8

  # 2. Aurora MySQL5.6 compatible group, one parameter is modified
  # EXPECTED: existing group is modified and the `character_set_client` now has the updated value
  # ACTUAL:   -- matches --
  # DBClusterParameterGroup:
  #   Type: AWS::RDS::DBClusterParameterGroup
  #   Properties:
  #     Description: Aurora MySQL5.6 parameter group
  #     Family: aurora5.6
  #     Parameters:
  #       character_set_client: utf8mb4

  # 3. Aurora MySQL5.6 compatible group, description modified
  # EXPECTED: there is no API to change an existing group's description, so a new group should be created with the
  #           updated description
  # ACTUAL:   The CloudFormation changeset shows "Replacement: false", but detects that there is a change. On exectuion
  #           it moves the resource to `UPDATE_IN_PROGRESS`, but it finishes within seconds to `UPDATE_COMPLETE` without
  #           the resource actually being modified (or recreated).
  # DBClusterParameterGroup:
  #   Type: AWS::RDS::DBClusterParameterGroup
  #   Properties:
  #     Description: Aurora MySQL5.7 parameter group
  #     Family: aurora5.6
  #     Parameters:
  #       character_set_client: utf8mb4

  # 4. Aurora MySQL5.7 compatible group, one parameter is modified
  # EXPECTED: there is no API to change an existing group's family, so a new group should be created with the updated
  #           family and where the parameter `character_set_client` will differ to the default group
  # ACTUAL:   The CloudFormation changeset shows "Replacement: false", but detects that there is a change. On exectuion
  #           it moves the resource to `UPDATE_IN_PROGRESS`, but it finishes within seconds to `UPDATE_COMPLETE` without
  #           the resource actually being modified (or recreated). The group is now not compatible with a
  #           aurora-mysql5.7 Aurora-cluster although you would expect it to be.
  # DBClusterParameterGroup:
  #   Type: AWS::RDS::DBClusterParameterGroup
  #   Properties:
  #     Description: Aurora MySQL5.7 parameter group
  #     Family: aurora-mysql5.7
  #     Parameters:
  #       character_set_client: utf8mb4
```

### Other Details

* Only tested in eu-central-1, in case it matters.
* There might be some relation to #896, although that ticket affects the `AWS::RDS::DBCluster`.
