### ISSUE TITLE
EKS Cluster Certificate Data too long for output

### ISSUE THREAD

**Issue by nicc777** [aws-cloudformation/cloudformation-coverage-roadmap#1062]
### Name of the resource

AWS::EKS::Cluster

### Resource Name

n/a

### Issue Description

I have the following output section:

```yaml
Outputs:

  EksClusterCertificateData:
    Description: "Certificate Data for  EksCluster"
    Value:
      Fn::GetAtt: 
      - "EksCluster"
      - "CertificateAuthorityData"
    Export:
      Name:
        Fn::Join:
        - '-'
        - - Ref: AWS::StackName
          - "EksClusterCertificateData"
```

However, during the CloudFormation  deployment, the following error is generated:

> Cannot export output EksClusterCertificateData with length 1424. Max length of 1024 exceeded.. Rollback requested by user.

Can the max. output length perhaps not be increased to something more reasonable for certificates?

### Expected Behavior

The certificate data should be present in the CloudFormation outputs

### Observed Behavior

During the CloudFormation  deployment, the following error is generated:

> Cannot export output EksClusterCertificateData with length 1424. Max length of 1024 exceeded.. Rollback requested by user.

### Test Cases

Create any EKS cluster and try to export the certificate data in the Outputs.
