### ISSUE TITLE
Updates to AWS::XRay::Group Tags are not applied

### ISSUE THREAD

**Issue by snijbell** [aws-cloudformation/cloudformation-coverage-roadmap#1104]
### Name of the resource

Other

### Resource name

AWS::XRay::Group

### Description

When an existing AWS::XRay::Group is updated from CloudFormation, updates to tags are not deployed. Using a new stack, create two new groups. One with tags, one without.

```
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  NewGroupTagged:
    Type: AWS::XRay::Group
    Properties:
      FilterExpression: !Sub 'resource.arn BEGINSWITH "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:"'
      GroupName: TestTaggedGroup
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false
      Tags:
        - Key: anykey
          Value: where-is-it

  NewGroupNonTagged:
    Type: AWS::XRay::Group
    Properties:
      FilterExpression: !Sub 'resource.arn BEGINSWITH "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:"'
      GroupName: TestNonTaggedGroup
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false

```

This will create two new X-Ray Groups. Notice the tags are successfully created on the first. Now, update the stack with:

AWSTemplateFormatVersion: '2010-09-09'

```
Resources:
  NewGroupTagged:
    Type: AWS::XRay::Group
    Properties:
      FilterExpression: !Sub 'resource.arn BEGINSWITH "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:"'
      GroupName: TestTaggedGroup
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false
      Tags:
        - Key: anykey
          Value: found-it

  NewGroupNonTagged:
    Type: AWS::XRay::Group
    Properties:
      FilterExpression: !Sub 'resource.arn BEGINSWITH "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:"'
      GroupName: TestNonTaggedGroup
      InsightsConfiguration:
        InsightsEnabled: false
        NotificationsEnabled: false
      Tags:
        - Key: anykey
          Value: where-is-it
```

### Result

No changes to Tags are applied to either X-Ray group.

### Expectation

CloudFormation should update the groups with the new tags.
