### ISSUE TITLE
Custom resource not updated after dependent resource is updated (ignores DependsOn and references)

### ISSUE THREAD

**Issue by eyalroth** [aws-cloudformation/cloudformation-coverage-roadmap#1112]
### Name of the resource

AWS::CloudFormation::CustomResource

### Issue Description

I've defined a custom resource that invokes a lambda with inline code:
```yml
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: myfunction
    Handler: index.handler
    Runtime: nodejs14.x
    Policies:
      - AWSLambdaVPCAccessExecutionRole
    InlineCode: |
      const cfnResponse = require('cfn-response');
      
      exports.handler = async function(event, context) {
        cfnResponse.send(event, context, cfnResponse.SUCCESS);
      }

MyCustomResource:
  Type: Custom::MyCustomResource
  Properties:
    ServiceToken: !GetAtt MyFunction.Arn
```

The resource is created successfully; however, it does not get updated by CF when the function is updated.

For instance, when I update the lambda code or add/change its timeout, the lambda gets updated but the custom resource does not (no event on the CF stack and no message in the lambda's logs).

I tried to add `DependsOn` and other types of references, as suggested in [this SO question](https://stackoverflow.com/questions/46479991/dependson-and-cloudformation-custom-resources), but it didn't affect this behavior:

```yml
MyCustomResource:
  Type: Custom::MyCustomResource
  DependsOn: MyFunction
  Properties:
    ServiceToken: !GetAtt MyFunction.Arn
    Foo: !Ref MyFunction
```

I'm not 100% if this is a bug or something that is just not supported.

### Expected Behavior

The custom resource should be updated and triggered with an `Update` event if another resource that it (directly) `DependsOn` is updated.

### Observed Behavior

The custom resource is not updated/triggerd.

### Test Cases

.
