### ISSUE TITLE
AWS::Sagemaker::StudioLifecycleConfiguration (Lifecycle Configuration for Sagemaker Studio Notebooks)

### ISSUE THREAD

**Issue by MarcusRosen-Rio** [aws-cloudformation/cloudformation-coverage-roadmap#1132]
### Name of the resource

Other

### Resource name

AWS::Sagemaker::StudioLifecycleConfiguration

### Description

Resource for supporting Lifecycle Configuration management on Sagemaker Studio Notebooks. Lifecycle configuration is vital to control SageMaker studio spend via auto-idle shutdown or for configuration and automated integration of private package management and git repositories especially in larger deployments across many AWS Accounts.

This resource type needs to provide the ability to attach lifecycle configuration to both the jupyter server or an image kernel and at the user level or at the domain wide-level (all users). Package command support, drift detection and resource import would be great bonuses!

Suggested Structure:

```yaml
AutoShutDownLifecycleConfiguration:
    Type: AWS::Sagemaker::StudioLifecycleConfiguration
    Properties:
      DomainId: <Sagemaker Studio Domain Id>
      Scope: [ Domain | User ]
      Type: [ Server | Kernel ]
      Name:  <name of lifecycle configuration>
      Script: <base64 encoded lcc script>
 
```
    

### Other Details

Sagemaker Studio Lifecycle Management APIs:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/create-studio-lifecycle-config.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/describe-studio-lifecycle-config.html
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/delete-studio-lifecycle-config.html

Attachment/Detachment against Sagemaker Studio Domain:
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/update-domain.html

Lifecycle Configuration Examples provided by AWS:
https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples

General overview of Studio Lifecycle Configuraiton:
https://aws.amazon.com/blogs/machine-learning/customize-amazon-sagemaker-studio-using-lifecycle-configurations/
