### ISSUE TITLE
Cloudformation for EKS : Should support return value for OpenIdConnectIssuerUrl !

### ISSUE THREAD

**Issue by crechandan** [aws-cloudformation/cloudformation-coverage-roadmap#1139]
### Name of the resource

AWS::CloudFormation::Stack

### Resource name

AWS::EKS::Cluster

### Description

Currently, We are able to create EKS cluster via Cloudformation (AWS::EKS::Cluster), We should be able to get retrun value of EKS cluster's **OpenIdConnectIssuerUrl** . This is important feature for defining IAM roles/policy other resource access for EKS cluster. Currently we are replying on Lambda function for getting the OpenIdConnectIssuerUrl of already existing EKS cluster (This is sometimes cumbersome/complex).

**Comment by mengmann** [comment]
Already there :
https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#aws-resource-eks-cluster-return-values

we use it like this:
```yaml
  AmazonEbsCsiDriverIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "arn:aws:iam::${AWS::AccountId}:oidc-provider/${OidcProviderEndpoint}"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "${OidcProviderEndpoint}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                        }
                    }
                }
            ]
          }
        - OidcProviderEndpoint: !Select [1, !Split ["//", !GetAtt Cluster.OpenIdConnectIssuerUrl]]
```
