### ISSUE TITLE
AWS::CloudFront::OriginRequestPolicy generic error message if the policy is duplicated

### ISSUE THREAD

**Issue by mpnguyen0401** [aws-cloudformation/cloudformation-coverage-roadmap#1157]
### Name of the resource

AWS::CloudFront::OriginRequestPolicy

### Description

If an origin request policy with the same name already exists, the resource creation failed after ~3 minutes with generic error message: "Internal error reported from downstream service during operation 'AWS::CloudFront::OriginRequestPolicy'."

Please improve the error message to inform the user about the duplication:

Steps to replicate the issue:

1. Create a stack with AWS::CloudFront::OriginRequestPolicy resource:
```
Resources:
  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties: 
      OriginRequestPolicyConfig: 
        HeadersConfig:
          Headers:
          - User-Agent
          - true-client-ip
          - Accept
          - x-api-key
          HeaderBehavior: whitelist
        CookiesConfig:
          CookieBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: all
        Name: client-origin-request-policy
```
The stack should be created successfully
3. Create the second stack with the exact same template => The error can be seen.
