### ISSUE TITLE
AWS::Logs::LogGroup don’t receive the aws:cloudformation built-in tags

### ISSUE THREAD

**Issue by bogdanb** [aws-cloudformation/cloudformation-coverage-roadmap#1158]
### Name of the resource

AWS::Logs::LogGroup

### Issue Description

When you have an `AWS::Log::LogGroup` resource in your stack, it does not get assigned the built-in tags: `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id`

This seems to happen both when the resource is created by the stack, and when it is imported.

### Expected Behavior

All stack resources should automatically receive the `aws:cloudformation:*` built-in tags.

### Observed Behavior

No tags are added automatically to `AWS::Log::LogGroup` resources.

### Test Cases

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: my-test-log-group
```
