### ISSUE TITLE
AWS::InspectorV2::Filter - allow tags

### ISSUE THREAD

**Issue by a2ush** [aws-cloudformation/cloudformation-coverage-roadmap#1170]
### Name of the resource

Other

### Resource name

AWS::InspectorV2::Filter

### Description

Request to allow to add tags to the AWS::InspectorV2::Filter resource.
Currently, CloudFormation does not support tags property for AWS::InspectorV2::Filter.

AWS::InspectorV2::Filter - AWS CloudFormation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspectorv2-filter.html

### Other Details

CreateFilter API supports tags property.

CreateFilter - Inspector
https://docs.aws.amazon.com/inspector/v2/APIReference/API_CreateFilter.html
```
   "tags": { 
      "string" : "string" 
   }
```

**Comment by r-heimann** [comment]
Seems like Tags are supported now:

```yaml
Type: AWS::InspectorV2::Filter
Properties:
  Description: String
  FilterAction: String
  FilterCriteria: 
    FilterCriteria
  Name: String
  Tags: 
    Key: Value
```
