### ISSUE TITLE
AWS::EKS::Cluster - ResourcesVpcConfig-endpointPrivateAccess

### ISSUE THREAD

**Issue by dnascimento** [aws-cloudformation/cloudformation-coverage-roadmap#118]
## 1. Title 
AWS::EKS::Cluster-ResourcesVpcConfig-endpointPrivateAccess

## 2. Scope of request 

AWS::EKS::Cluster-ResourcesVpcConfig supports `SecurityGroupIds` and `SubnetIds` but not `endpointPrivateAccess` and `endpointPublicAccess`. These properties can be created via API but not via CloudFormation.

## 3. Expected behavior

Allow users to set endpointPrivateAccess=True/False and endpointPublicAccess=True/False

```yaml
Type: AWS::EKS::Cluster
Properties: 
  Name: String
  ResourcesVpcConfig: 
    SecurityGroupIds:
        - String
    SubnetIds: 
        - String
    EndpointPrivateAccess: Boolean
    EndpointPublicAccess: Boolean
  RoleArn: String
  Version: String
```

## 4. Suggest specific test cases

Many users do not want to expose their EKS API to public and/or need to expose a private endpoint to EKS. This is a **blocker** for many customers as their security policies don't allow public endpoints. [EKS Cluster Endpoint Access](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html)
As alternative, many are using awscli and terraform.

## 5. Helpful Links to speed up research and evaluation

[EKS API Reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_VpcConfigRequest.html#AmazonEKS-Type-VpcConfigRequest-endpointPrivateAccess)
[EKS Cluster Endpoint Access](https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html)

https://github.com/weaveworks/eksctl/issues/649
https://github.com/weaveworks/eksctl/issues/778
https://github.com/aws/containers-roadmap/issues/242
https://github.com/aws-quickstart/quickstart-amazon-eks/issues/37

## 6. Category
1. Compute (EKS)
