### ISSUE TITLE
AWS::RDS::DBInstance - Validate invalid DeletionPolicy for DB instance resource

### ISSUE THREAD

**Issue by 0xlen** [aws-cloudformation/cloudformation-coverage-roadmap#1180]
### Name of the resource

AWS::RDS::DBInstance

### Description

According to the document [1], the `AWS::RDS::DBInstance`  allows you have DeletionPolicy to decide how to preserve DB instance. However, CloudFormation did not validate the `DeletionPolicy` when I am deploying the stack by using Amazon RDS DB instance (not Aurora DB cluster) so I was expected it works. Once I update the DB instance resource with CloudFormation (e.g. rename the `DBName` property to trigger replace).

> For DB instances that are part of an Aurora DB cluster, you can set a deletion policy for your DB instance to control how AWS CloudFormation handles the DB instance when the stack is deleted. For Amazon RDS DB instances, you can choose to `retain` the DB instance, to delete the DB instance, or to create a snapshot of the DB instance.

I think the document [1] also wasn't very clear to highlight this issue (Need to use `retain` instead of `Snapshot`) and it can be ignored as it wasn't very straightforward. Because when I was using the property, I will expect CloudFormation should help me to build a snapshot before deletion. Most importantly, **CloudFormation also did not validate the property or have any warning**. It causes the production impact because I will lose my database data after doing stack update.

[Sample template]
```
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 'mydb'
      AllocatedStorage: 50
      StorageType: gp2
      DBInstanceClass: 'db.m5.large'
      Engine: postgres
      EngineVersion: "10.18"
      Port: '5432'
      MasterUsername: DBUsername
      MasterUserPassword: DBPassword
      MultiAZ: 'false'
      PubliclyAccessible: false
    DeletionPolicy: Snapshot
```

[Stack event]

![image](https://user-images.githubusercontent.com/1008379/169853800-01729ce2-a799-43c7-8960-820cb96bf97e.png)

[1] AWS::RDS::DBInstance - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html

**Comment by PatMyron** [comment]
> (e.g. rename the `DBName` property to trigger replace)

Replacements require [`UpdateReplacePolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatereplacepolicy.html) rather than [`DeletionPolicy`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html)

[`cfn-lint` has a rule to warn about resources with one policy set but not the other policy](https://github.com/aws-cloudformation/cfn-lint/blob/main/docs/rules.md#W3011)

**Comment by 0xlen** [comment]
@PatMyron Thanks for clarifying! But that's is not very straightforward especially the document can mislead when I am walking through it. Especially the event for DBInstance has `DELETE_IN_PROGRESS` event for DBInstance, so it can be confusing and you will never know what's going on for this policy until you realized it doesn't work for database replacement.

I think have some protection for this as default behavior might be better for preventing unexpected data loss (e.g. Set [`DeletionProtection`](https://docs.aws.amazon.com/zh_cn/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-deletionprotection) as true. But it looks like Aurora doesn't apply this configuration, haven't tested it), or have default `UpdateReplacePolicy` to create snapshot; otherwise, if the CloudFormation doesn't validate it and users without using `cfn-lint`, it can be easily ignored when writing my template.

```
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: 'mydb'
      AllocatedStorage: 50
      StorageType: gp2
      DBInstanceClass: 'db.m5.large'
      Engine: postgres
      ...
      DeletionProtection: true
```

![image](https://user-images.githubusercontent.com/1008379/170003102-22e708d4-0710-47f0-bda5-11e7c0a570ed.png)
