### ISSUE TITLE
Condition reference inside RuleCondition in Rule block

### ISSUE THREAD

**Issue by quanght55** [aws-cloudformation/cloudformation-coverage-roadmap#1183]
### Resource Name

CloudFormation Rules Block

### Details

Rule-specific intrinsic function "Condition" cannot be used under Rules block of CloudFormation template.

**Expected Behavior:**
Can reference to a condition since it will return true or false in RuleCondition block for more flexible constraint validation
**Observed Behavior:**
Cannot reference to a condition
**Test case:**
```
Parameters:
  Stream:
    Type: String

Condition:
  Testing: !Equals ['a', 'a']
Rules:
  FirstRule:
    RuleCondition: !Condition Testing 
    Assertions:
      - AssertDescription: "Must have value"
        Assert:  !Not
            - !Equals [ !Ref Stream, '' ]
```
