### ISSUE TITLE
AWS::Backup::BackupVault notification settings falsely return an error on initial create

### ISSUE THREAD

**Issue by redterror** [aws-cloudformation/cloudformation-coverage-roadmap#1188]
### Name of the resource

AWS::Backup::BackupVault

### Issue Description

Hi!  Creating a BackupVault with a `Notifications` block produces an error on initial create, but on update, it works correctly.  E.g.  the following template:

```
Description: AWS Backup plan for us-west-2 resources

Parameters:
  SnsTopicArn:
    Type: String
    Description: SNS topic for backup notifications

Resources:
  Vault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: my-resources
      Notifications:
        SNSTopicArn: !Ref SnsTopicArn
        BackupVaultEvents:
          - BACKUP_JOB_COMPLETED
          - COPY_JOB_FAILED
          - COPY_JOB_SUCCESSFUL
          - S3_BACKUP_OBJECT_FAILED
```

Yields the error:

```
2022-05-26 19:16:03 +0000 Vault AWS::Backup::BackupVault CREATE_FAILED Resource handler returned message: "Please select from the following list of notifications BACKUP_JOB_STARTED, BACKUP_JOB_COMPLETED, RESTORE_JOB_STARTED, RESTORE_JOB_COMPLETED, COPY_JOB_STARTED, COPY_JOB_SUCCESSFUL, COPY_JOB_FAILED, RECOVERY_POINT_MODIFIED, S3_BACKUP_OBJECT_FAILED, S3_RESTORE_OBJECT_FAILED (Service: Backup, Status Code: 400, Request ID: 5904aeaa-baf8-4324-9110-b8c266ea9f58, Extended Request ID: null)" (RequestToken: a11b89cb-287b-6f77-93fe-3f7a60744ffa, HandlerErrorCode: GeneralServiceException)
```

If I comment the `Notifications` block, create the stack, uncomment and then update it, then it converges correctly.

### Expected Behavior

It should work in one step, not two.

### Observed Behavior

See above.

### Test Cases

See above.
