### ISSUE TITLE
AWS::EC2::SecurityGroupIngress causing false positive drift within referenced AWS::EC2::SecurityGroup

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1198]
### Name of the resource

AWS::EC2::SecurityGroupIngress

### Resource Name

AWS::EC2::SecurityGroup

### Issue Description

It's possible to add a rule within a `AWS::EC2::SecurityGroup` using SecurityGroupIngress rule directly as part of the resource OR  defining a dedicated resource called `AWS::EC2::SecurityGroupIngress`. Within this `AWS::EC2::SecurityGroupIngress` need to specify the SecurityGroupId, where is rule should be added. This 2nd common pattern causing a causing false positive drift within referenced `AWS::EC2::SecurityGroup`.

### Expected Behavior

CloudFormation drift detection must be able to “understand” rules added via AWS::EC2::SecurityGroupIngress to an existing AWS::EC2::SecurityGroup.

### Observed Behavior

Rules within SecurityGroup which had been added via AWS::EC2::SecurityGroupIngress are reported as drift. CloudFormation drift detection doesn't "resolve" rules from AWS::EC2::SecurityGroupIngress resource. Users of CloudFormation drift detection assume this rules are added outside of CloudFormation. Once checking the rules via AWS Console the rules reported in drift are in place. Details please see via "Test Cases"

### Test Cases

**(1)**
Add a Stack A which containing a AWS::EC2::SecurityGroup and some rules:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack A (hosting the SecGroup with sample rules 1 and 2) - case 10148943561

Resources: 
  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: SecGroup in Stack A e.g. for an NLB
      GroupName: 'rogo-testA'
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.10.10.100/32
          Description: Rule 1 defined in SecurityGroup directly
        - IpProtocol: tcp
          FromPort: 6777
          ToPort: 6777
          CidrIp: 10.10.10.101/32
          Description: Rule 2 defined in SecurityGroup directly
      Tags: 
      - Key: ApplicationID
        Value: sample
      VpcId: 
        Fn::ImportValue: VPC1-VPC-ID
```
After creation you can see, that Stack is state IN_SYNC:
![stackA-beforeRefViaSecurityGroupIngress_GIT](https://user-images.githubusercontent.com/16392819/172047636-4df0eae5-1c93-4135-ad5b-8da9d09d8e00.jpg)

**(2)** 
Catch the GroupId of AWS::EC2::SecurityGroup from Stack A and add a Stack B, which contains AWS::EC2::SecurityGroupIngress with reference to this SecurityGroup GroupId:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack B (AWS::EC2::SecurityGroupIngress causing drift false-positive within referenced SecGroup) - case 10148943561

Resources:
  ServerSecGroupIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-0f7274xR0beRtx
      IpProtocol: tcp
      FromPort: 6777
      ToPort: 6777
      CidrIp: 10.20.20.202/32
      Description: Rule 3 added by SecurityGroupIngress
  
  ServerSecGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-0f7274xR0beRtx
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 10.20.20.200/32
      Description: Rule 4 added by SecurityGroupIngress
```

After the stack is created as well you can see the correct/expected result in the SecurityGroup:
![SecGroupRes_GIT](https://user-images.githubusercontent.com/16392819/172047776-08b64ed1-7eec-491d-9c98-f53d0cb01018.jpg)

**(3)** 
Run the CloudFormation drift detection again on Stack A and see the bug:
![stackA-DRIFTafterSecurityGroupIngress_GIT](https://user-images.githubusercontent.com/16392819/172047791-a9ac2c8a-771d-4d8b-b663-5347fa15e275.jpg)
Both rules (here called Rule 3 + Rule 4 coming from AWS::EC2::SecurityGroupIngress) are *reported as drift*, even this rules are part of the SecurityGroup! The stack is in state DRIFTED.

### Other Details

Managing SecurityGroup rules is an important and fundamental part of IaC. Having this said, CloudFormation drift detection is the essential part for monitoring your existing setup, especially SecurityGroup rules.

**Comment by chrisflorin** [comment]
Name of the resource
AWS::EC2::SecurityGroupIngress

Resource Name
AWS::EC2::SecurityGroup

Issue Description
It's possible to create a SecurityGroupIngress rule for a SecurityGroup that is both part of the SecurityGroup and references the SecurityGroup.

Expected Behavior
CloudFormation should detect no drift on resources within a single stack.

Observed Behavior
CloudFormation detects drift on the AllowMysqlFromOneSg resource in the template in the Test Cases section.

Test Cases

```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcId:
    Type: String
    Description: 'Enter the VPC ID where the Security Groups will be created'
#---------------------------------------------------------------------------
# RESOURCES
#---------------------------------------------------------------------------
Resources:
  #---------------------------------------------------------------------------
  # one-sg
  #---------------------------------------------------------------------------
  OneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: one-sg 
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: one-sg
  #---------------------------------------------------------------------------
  # another-sg
  #---------------------------------------------------------------------------
  AnotherSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: another-sg 
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: another-sg
  # Allow MySQL from myself (one-sg)
  AllowMysqlFromOneSg:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OneSecurityGroup
      SourceSecurityGroupId: !Ref OneSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      Description: Allow MySQL from one-sg
  # Allow MySQL from another-sg
  AllowMysqlFromAnotherSg:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OneSecurityGroup
      SourceSecurityGroupId: !Ref AnotherSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      Description: Allow MySQL from another-sg
#---------------------------------------------------------------------------
# OUTPUTS
#---------------------------------------------------------------------------
Outputs:
  OneSecurityGroup:
    Description: 'one-sg'
    Value: !Ref OneSecurityGroup
    Export:
      Name: 'one-sg'
  AnotherSecurityGroup:
    Description: 'another-sg'
    Value: !Ref AnotherSecurityGroup
    Export:
      Name: 'another-sg'

```
Other Details
![Screenshot from 2022-06-25 15-38-50](https://user-images.githubusercontent.com/5882537/196703494-30174a30-3ff1-471a-a3d9-8b2e6b8fcec2.png)
![Screenshot from 2022-06-25 15-39-39](https://user-images.githubusercontent.com/5882537/196703478-f35a3186-3c8c-4439-a7f1-15a0c7d5e761.png)

**Comment by rgoltz** [comment]
@davidataws - If you like I can cross-check within the next days, if this drift detection bug for AWS::EC2::SecurityGroupIngress is still reproducible along the examples here in the case. Please confirm that you are able/willing to work on this (or you can just try to reproduce this along the examples by your own and share your results. I can cross-check them afterwards.)

**Comment by davidataws** [comment]
If I'm understanding correctly, there are two issues here:

1. With a single stack: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1198#issuecomment-1284012604
1. With two different stacks (the issue originally described here)

---

I can't reproduce the issue reported in https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1198#issuecomment-1284012604 with a single stack. I used the following template:

```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  VpcId:
    Type: String
    Description: 'Enter the VPC ID where the Security Groups will be created'
#---------------------------------------------------------------------------
# RESOURCES
#---------------------------------------------------------------------------
Resources:
  #---------------------------------------------------------------------------
  # one-sg
  #---------------------------------------------------------------------------
  OneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: one-sg
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: one-sg
  #---------------------------------------------------------------------------
  # another-sg
  #---------------------------------------------------------------------------
  AnotherSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: another-sg
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: another-sg
  # Allow MySQL from myself (one-sg)
  AllowMysqlFromOneSg:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OneSecurityGroup
      SourceSecurityGroupId: !Ref OneSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      Description: Allow MySQL from one-sg
  # Allow MySQL from another-sg
  AllowMysqlFromAnotherSg:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref OneSecurityGroup
      SourceSecurityGroupId: !Ref AnotherSecurityGroup
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      Description: Allow MySQL from another-sg
#---------------------------------------------------------------------------
# OUTPUTS
#---------------------------------------------------------------------------
Outputs:
  OneSecurityGroup:
    Description: 'one-sg'
    Value: !Ref OneSecurityGroup
    Export:
      Name: 'one-sg'
  AnotherSecurityGroup:
    Description: 'another-sg'
    Value: !Ref AnotherSecurityGroup
    Export:
      Name: 'another-sg'
```

The stack creates successfully, and I don't see any drifted resources:

```
% aws cloudformation describe-stack-resource-drifts --stack-name ... --region us-east-2
{
    "StackResourceDrifts": [
        {
            "StackId": "...",
            "LogicalResourceId": "AnotherSecurityGroup",
            "PhysicalResourceId": "sg-...",
            "ResourceType": "AWS::EC2::SecurityGroup",
            "ExpectedProperties": "{\"GroupDescription\":\"another-sg\",\"VpcId\":\"vpc-...\",\"Tags\":[{\"Value\":\"another-sg\",\"Key\":\"Name\"}]}",
            "ActualProperties": "{\"GroupDescription\":\"another-sg\",\"VpcId\":\"vpc-...\",\"Tags\":[{\"Value\":\"another-sg\",\"Key\":\"Name\"}]}",
            "PropertyDifferences": [],
            "StackResourceDriftStatus": "IN_SYNC",
            "Timestamp": "2025-05-22T16:50:04.104000+00:00"
        },
        {
            "StackId": "...",
            "LogicalResourceId": "OneSecurityGroup",
            "PhysicalResourceId": "sg-...",
            "ResourceType": "AWS::EC2::SecurityGroup",
            "ExpectedProperties": "{\"GroupDescription\":\"one-sg\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"SourceSecurityGroupId\":\"sg-...\",\"Description\":\"Allow MySQL from one-sg\",\"FromPort\":3306,\"IpProtocol\":\"tcp\",\"ToPort\":3306,\"SourceSecurityGroupOwnerId\":\"...\"},{\"SourceSecurityGroupId\":\"sg-...\",\"Description\":\"Allow MySQL from another-sg\",\"FromPort\":3306,\"IpProtocol\":\"tcp\",\"ToPort\":3306,\"SourceSecurityGroupOwnerId\":\"...\"}],\"Tags\":[{\"Value\":\"one-sg\",\"Key\":\"Name\"}]}",
            "ActualProperties": "{\"GroupDescription\":\"one-sg\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"SourceSecurityGroupId\":\"sg-...\",\"Description\":\"Allow MySQL from one-sg\",\"FromPort\":3306,\"IpProtocol\":\"tcp\",\"ToPort\":3306,\"SourceSecurityGroupOwnerId\":\"...\"},{\"SourceSecurityGroupId\":\"sg-...\",\"Description\":\"Allow MySQL from another-sg\",\"FromPort\":3306,\"IpProtocol\":\"tcp\",\"ToPort\":3306,\"SourceSecurityGroupOwnerId\":\"...\"}],\"Tags\":[{\"Value\":\"one-sg\",\"Key\":\"Name\"}]}",
            "PropertyDifferences": [],
            "StackResourceDriftStatus": "IN_SYNC",
            "Timestamp": "2025-05-22T16:50:04.402000+00:00"
        }
    ]
}
```

---

I _can_, however, reproduce the issue originally presented with two different stacks. Everything's fine after I create the first stack:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack A (hosting the SecGroup with sample rules 1 and 2) - case 10148943561

Resources:
  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecGroup in Stack A e.g. for an NLB
      GroupName: 'rogo-testA'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.10.10.100/32
          Description: Rule 1 defined in SecurityGroup directly
        - IpProtocol: tcp
          FromPort: 6777
          ToPort: 6777
          CidrIp: 10.10.10.101/32
          Description: Rule 2 defined in SecurityGroup directly
      Tags:
      - Key: ApplicationID
        Value: sample
      VpcId: 'vpc-...'
```

```
% aws cloudformation describe-stack-resource-drifts --stack-name ...-1 --region us-east-2
{
    "StackResourceDrifts": [
        {
            "StackId": "...",
            "LogicalResourceId": "ServerSecGroup",
            "PhysicalResourceId": "sg-...",
            "ResourceType": "AWS::EC2::SecurityGroup",
            "ExpectedProperties": "{\"GroupDescription\":\"SecGroup in Stack A e.g. for an NLB\",\"GroupName\":\"rogo-testA\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"CidrIp\":\"10.10.10.100/32\",\"Description\":\"Rule 1 defined in SecurityGroup directly\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22},{\"CidrIp\":\"10.10.10.101/32\",\"Description\":\"Rule 2 defined in SecurityGroup directly\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777}],\"Tags\":[{\"Value\":\"sample\",\"Key\":\"ApplicationID\"}]}",
            "ActualProperties": "{\"GroupDescription\":\"SecGroup in Stack A e.g. for an NLB\",\"GroupName\":\"rogo-testA\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"CidrIp\":\"10.10.10.100/32\",\"Description\":\"Rule 1 defined in SecurityGroup directly\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22},{\"CidrIp\":\"10.10.10.101/32\",\"Description\":\"Rule 2 defined in SecurityGroup directly\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777}],\"Tags\":[{\"Value\":\"sample\",\"Key\":\"ApplicationID\"}]}",
            "PropertyDifferences": [],
            "StackResourceDriftStatus": "IN_SYNC",
            "Timestamp": "2025-05-22T17:17:02.645000+00:00"
        }
    ]
}
```

But when I create the second stack:

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack B (AWS::EC2::SecurityGroupIngress causing drift false-positive within referenced SecGroup) - case 10148943561

Resources:
  ServerSecGroupIngress1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-...
      IpProtocol: tcp
      FromPort: 6777
      ToPort: 6777
      CidrIp: 10.20.20.202/32
      Description: Rule 3 added by SecurityGroupIngress

  ServerSecGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: sg-...
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 10.20.20.200/32
      Description: Rule 4 added by SecurityGroupIngress
```

I now see the first stack get marked as drifted:

```
% aws cloudformation describe-stack-resource-drifts --stack-name ...-1 --region us-east-2
{
    "StackResourceDrifts": [
        {
            "StackId": "...",
            "LogicalResourceId": "ServerSecGroup",
            "PhysicalResourceId": "sg-...",
            "ResourceType": "AWS::EC2::SecurityGroup",
            "ExpectedProperties": "{\"GroupDescription\":\"SecGroup in Stack A e.g. for an NLB\",\"GroupName\":\"rogo-testA\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"CidrIp\":\"10.10.10.100/32\",\"Description\":\"Rule 1 defined in SecurityGroup directly\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22},{\"CidrIp\":\"10.10.10.101/32\",\"Description\":\"Rule 2 defined in SecurityGroup directly\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777}],\"Tags\":[{\"Value\":\"sample\",\"Key\":\"ApplicationID\"}]}",
            "ActualProperties": "{\"GroupDescription\":\"SecGroup in Stack A e.g. for an NLB\",\"GroupName\":\"rogo-testA\",\"VpcId\":\"vpc-...\",\"SecurityGroupIngress\":[{\"CidrIp\":\"10.10.10.100/32\",\"Description\":\"Rule 1 defined in SecurityGroup directly\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22},{\"CidrIp\":\"10.20.20.200/32\",\"Description\":\"Rule 4 added by SecurityGroupIngress\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22},{\"CidrIp\":\"10.10.10.101/32\",\"Description\":\"Rule 2 defined in SecurityGroup directly\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777},{\"CidrIp\":\"10.20.20.202/32\",\"Description\":\"Rule 3 added by SecurityGroupIngress\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777}],\"Tags\":[{\"Value\":\"sample\",\"Key\":\"ApplicationID\"}]}",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/SecurityGroupIngress/1",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"CidrIp\":\"10.20.20.200/32\",\"Description\":\"Rule 4 added by SecurityGroupIngress\",\"FromPort\":22,\"IpProtocol\":\"tcp\",\"ToPort\":22}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/SecurityGroupIngress/3",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"CidrIp\":\"10.20.20.202/32\",\"Description\":\"Rule 3 added by SecurityGroupIngress\",\"FromPort\":6777,\"IpProtocol\":\"tcp\",\"ToPort\":6777}",
                    "DifferenceType": "ADD"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",
            "Timestamp": "2025-05-22T17:20:42.867000+00:00"
        }
    ]
}
```

even though the second stack doesn't:

```
% aws cloudformation describe-stack-resource-drifts --stack-name ...-2 --region us-east-2
{
    "StackResourceDrifts": []
}
```

This _sounds_ like documented behavior (emphasis mine to highlight the relevant bit):

> Certain resources have attachment relationships with related resources, such that a resource may actually attach or remove property values for another resource, defined in the same or another template. For example, the `AWS::EC2::SecurityGroupIngress` and `AWS::EC2::SecurityGroupEgress` resources may be used to attach and remove values from `AWS::EC2::SecurityGroup` resources. In these cases, CloudFormation analyses the stack template for attachments before performing the drift comparison. **However, CloudFormation can't perform this analysis across stacks, and so may not return accurate drift results where resources that are attached reside in different stacks.**

([ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#drift-considerations))

But I'm going to reach out to the team that owns drift detection to confirm and see if we should track this as a feature request.
