### ISSUE TITLE
AWS::Lightsail::Distribution "Resource of type 'Distribution' with identifier already exists." 

### ISSUE THREAD

**Issue by sgargel** [aws-cloudformation/cloudformation-coverage-roadmap#1202]
### Name of the resource

AWS::Lightsail::Distribution

### Resource Name

AWS::Lightsail::Distribution

### Issue Description

Stated that there aren't any Lightsail distribution configured:

![image](https://user-images.githubusercontent.com/24651376/172375731-b437f89e-68ef-46c8-83c0-fc07a311005e.png)

![image](https://user-images.githubusercontent.com/24651376/172375859-8f71b1b6-bcf5-4ecf-a29b-49dff961e7a8.png)

Deploying `AWS::Lightsail::Distribution` using the template below throws this error:

`Resource handler returned message: "Resource of type 'Distribution' with identifier 'distribution-2' already exists." `

```
  WebAppCDN:
    Type: AWS::Lightsail::Distribution
    Properties:
      BundleId: small_1_0
      CacheBehaviors: 
        - 
          Behavior: cache
          Path: _next/static/*

        - 
          Behavior: cache
          Path: _next/image*

                                                          
      CacheBehaviorSettings: 
        AllowedHTTPMethods: GET,HEAD
        CachedHTTPMethods: GET,HEAD
        DefaultTTL: 500
        #ForwardedCookies: 
        #  CookieObject
        #ForwardedHeaders: 
        #  HeaderObject
        #ForwardedQueryStrings: 
        #  QueryStringObject
        MaximumTTL: 1800
        MinimumTTL: 60

      #CertificateName: String
      DefaultCacheBehavior: 
        Behavior: dont-cache
      DistributionName: distribution-2
      #IpAddressType: ipv4
      IsEnabled: true
      Origin: 
        Name: my-webapp-service
        #Region: eu-central-1
```
Changing `DistributionName` values does not work.

### Expected Behavior

The expected behavior is the ability to deploy the resource.

### Observed Behavior

There isn't a `DistributionName` value that cloudformation accepts and the parameter is mandatory.

### Test Cases

Origin `my-webapp-service` must exists and in my case is a LightSail container service.

```
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  LightSail CDN



Resources:

  WebAppCDN:
    Type: AWS::Lightsail::Distribution
    Properties:
      BundleId: small_1_0
      CacheBehaviors: 
        - 
          Behavior: cache
          Path: _next/static/*

        - 
          Behavior: cache
          Path: _next/image*
                                                          
      CacheBehaviorSettings: 
        AllowedHTTPMethods: GET,HEAD
        CachedHTTPMethods: GET,HEAD
        DefaultTTL: 500
        #ForwardedCookies: 
        #  CookieObject
        #ForwardedHeaders: 
        #  HeaderObject
        #ForwardedQueryStrings: 
        #  QueryStringObject
        MaximumTTL: 1800
        MinimumTTL: 60

      #CertificateName: String
      DefaultCacheBehavior: 
        Behavior: dont-cache
      DistributionName: distribution-2
      #IpAddressType: ipv4
      IsEnabled: true
      Origin: 
        Name: my-webapp-service
        #Region: eu-central-1
```
