### ISSUE TITLE
Drift Detection false positive for KmsKeyId property under AWS::Redshift::Cluster resource

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1203]
### Name of the resource

AWS::Redshift::Cluster

### Issue Description

The `KmsKeyId ` property for the AWS::Redshift::Cluster resource is marked as drifted when just the Id (not full ARN) is specified in the template and the stack is created. 

Ideally, drift detection should not have been performed on the `KmsKeyId ` property as per - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#drift-considerations

```
CloudFormation does not perform drift detection on the KMSKeyId property of any resources. Because AWS KMS keys can be referenced by multiple aliases, CloudFormation can't guarantee consistently accurate drift results for this property.
```

### Expected Behavior

The `KmsKeyId ` property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The `KmsKeyId ` property is marked as NOT_EQUAL with 
expected = `xxxx-xxxx-xxxx-xxxx`
actual = `arn:aws:kms:us-east-1:123465798012:key/xxxx-xxxx-xxxx-xxxx`

### Test Cases

Steps to reproduce - 
1) Create Stack using following template - 
```
Resources:
    myCluster:
      Type: 'AWS::Redshift::Cluster'
      Properties:
        DBName: mydb
        Encrypted: true
        MasterUsername: master
        MasterUserPassword: xxxxxxxxxx
        NodeType: ds2.xlarge
        ClusterType: single-node
        KmsKeyId: xxxx-xxxx-xxxx-xxxx
```
2) Run drift detection
3) View drift results
