### ISSUE TITLE
Drift Detection issue for Classic property under AWS::Redshift::Cluster resource

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1204]
### Name of the resource

AWS::Redshift::Cluster

### Issue Description

The `Classic` property for the AWS::Redshift::Cluster resource is marked as drifted when its value is specified as `false`. 

### Expected Behavior

The `Classic` property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The `Classic` property is marked as REMOVE with
expected = false
actual = -

### Test Cases

Steps to reproduce -

1) Create Stack using following template -
```
Resources:
    myCluster:
      Type: 'AWS::Redshift::Cluster'
      Properties:
        DBName: mydb
        MasterUsername: master
        MasterUserPassword: xxxxxxxxxx
        NodeType: ds2.xlarge
        ClusterType: single-node
        Classic: false
```
2) Run drift detection
3) View drift results
