### ISSUE TITLE
Using Fn::Import with ChangeSet that IncludeNestedStacks set to True gives error "TemplateURL must be a supported URL."

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#1212]
### Name of the resource

AWS::CloudFormation::Stack

### Issue Description

Using `Fn::Import` in template when creating a ChangeSet with `IncludeNestedStacks` set to `True` gives error "TemplateURL must be a supported URL."

See template below.

```
Parameters:
    MyExportName:
        Type: String

Resources:
    Stack: 
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: 
                Fn::Sub:
                - https://${BucketName}.s3.${AWS::Region}.amazonaws.com/template.yaml 
                - BucketName:
                    Fn::ImportValue: !Sub ${SSMParameter}-Export
```

This also fails when trying to use `Fn::ImportValue` under `Fn::Join`. 

I suspect that the `IncludeNestedStacks` feature when creating changesets does not work with `Fn::ImportValue`. Because if I specify `IncludeNestedStacks` to false, the error goes away.

Removing `Fn::ImportValue` also fixes this issue.

### Expected Behavior

It should not fail.

### Observed Behavior

It fails with the error `TemplateURL must be a supported URL.`

### Test Cases

Create a changeset with a template that has an `AWS::CloudFormation::Stack` resource, with TemplateURL using Fn::ImportValue, like the above example.
