### ISSUE TITLE
CloudFormation reports incorrect drift for AWS::ECS::Cluster regarding aws:cloudformation:* AutoTags generated by CFN

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1222]
### Name of the resource

AWS::ECS::Cluster

### Issue Description

Once generating a new CloudFormation stack containing a `AWS::ECS::Cluster` resource, CloudFormation will add following automatic default AutoTags `aws:cloudformation:`:
* aws:cloudformation:stack-name
* aws:cloudformation:logical-id
* aws:cloudformation:stack-id

![EcsClusterWithCfnAutoTags_githubfixed](https://user-images.githubusercontent.com/16392819/175557401-f612b094-9ec1-4e78-8d55-e6b18a2cf869.jpg)

Once you trigger a CloudFormation drift detection for such stack, it’s reporting a drift (details see "Observed Behavior").

### Expected Behavior

Cloudformation drift detection must be aware of his “own” automatic set tags with naming-pattern `aws:cloudformation:` and doesn't reported those tags as drift for `AWS::ECS::Cluster`. Stack must be in state IN_SYNC.

### Observed Behavior

Cloudformation reports his own AutoTags as drift, which is a bug. Stack is in state DRIFTED. It’s not possible to set or define tags starting with `aws:cloudformation:` within a CloudFormation template. Hence, it's not possible to fix this issue yet.

Below you can see the details of the reported drift:
![EcsClusterDriftDetails_github](https://user-images.githubusercontent.com/16392819/175557557-67309475-05ad-45cb-9587-d337478ccd3d.jpg)

### Test Cases

Create a new stack with a simple `AWS::ECS::Cluster`, like:

```yaml
  EXXXXECSsandboxEXXXXECSsandboxClusterAXXXXXXF:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: EXXXXECS-sandbox-Cluster
      Tags:
      - Key: TagKeySetByCustomer1
        Value: SameValue1
      - Key: TagKeySetByCustomer2
        Value: SameValue2
```
