### ISSUE TITLE
Drift Detection false positive for WaitForSuccessTimeoutSeconds property of AWS::SSM::Association resource

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1225]
### Name of the resource

AWS::SSM::Association

### Issue Description

In 2020 a new property for resource type `AWS::SSM::Association` called `WaitForSuccessTimeoutSeconds` had been added via #491 to CloudFormation. Once you adding this property to your template, the CloudFormation Drift Detection will report this property as REMOVED, but it’s still part of the existing Association. 

### Expected Behavior

CloudFormation Drift Detection is able to find this `WaitForSuccessTimeoutSeconds` property and doesn't report this property as drift. The stack containing such resource should be in IN_SYNC.

### Observed Behavior

Resource `AWS::SSM::Association` is causing an unexpected drift result in the stack. More specifically, the `WaitForSuccessTimeoutSeconds` property is triggering this drift result. A stack having such resource is in state DRIFTED.

Below you can find an example of CFN Drift Detection details (property is not part of "Actual / Current value"):
![WaitForSuccessTimeoutSeconds_github](https://user-images.githubusercontent.com/16392819/175809094-e6b0c5da-cde4-4ff5-be9d-1660a253e63d.jpg)

### Test Cases

Create a new CFN stack define a `AWS::SSM::Association` resource with a `WaitForSuccessTimeoutSeconds` property. Run the CloudFormation Drift Detection after creation and check the Drift Status/Details.

```yaml
  ScriptExecAssociation:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: association-name-rgoltz
      Targets:
        - Key: "resource-groups:Name"
          Values:
            - resource-group-rgoltz
      ScheduleExpression:
        Ref: ScheduleAssociation
      Name: AWS-RunShellScript
      Parameters:
        commands:
        - echo "here is some bash code 1"
        - echo "here is some bash code 2"
        workingDirectory:
        - "/tmp"
      WaitForSuccessTimeoutSeconds: 500
```
