### ISSUE TITLE
AWS::IoTWireless::DeviceProfile - Add LoRaWAN RX Parameters

### ISSUE THREAD

**Issue by baxterjo** [aws-cloudformation/cloudformation-coverage-roadmap#1227]
### Name of the resource

AWS::IoTWireless::DeviceProfile

### Description

Request to add rx params to LoRaWAN device profile in CloudFormation template.

Current `create_device_profile` request in boto3 looks like this:
```python
response = client.create_device_profile(
    Name='string',
    LoRaWAN={
        'SupportsClassB': True|False,
        'ClassBTimeout': 123,
        'PingSlotPeriod': 123,
        'PingSlotDr': 123,
        'PingSlotFreq': 123,
        'SupportsClassC': True|False,
        'ClassCTimeout': 123,
        'MacVersion': 'string',
        'RegParamsRevision': 'string',
        'RxDelay1': 123,
        'RxDrOffset1': 123,
        'RxDataRate2': 123,
        'RxFreq2': 123,
        'FactoryPresetFreqsList': [
            123,
        ],
        'MaxEirp': 123,
        'MaxDutyCycle': 123,
        'RfRegion': 'string',
        'SupportsJoin': True|False,
        'Supports32BitFCnt': True|False
    },
    Tags=[
        {
            'Key': 'string',
            'Value': 'string'
        },
    ],
    ClientRequestToken='string'
)
```

And current cloud formation template looks like this:
```yaml
Type: AWS::IoTWireless::DeviceProfile
Properties: 
  LoRaWAN: 
      ClassBTimeout: Integer
      ClassCTimeout: Integer
      MacVersion: String
      MaxDutyCycle: Integer
      MaxEirp: Integer
      PingSlotDr: Integer
      PingSlotFreq: Integer
      PingSlotPeriod: Integer
      RegParamsRevision: String
      RfRegion: String
      Supports32BitFCnt: Boolean
      SupportsClassB: Boolean
      SupportsClassC: Boolean
      SupportsJoin: Boolean
  Name: String
  Tags: 
    - Tag
```

Missing parameters are:
```yaml
RxDelay1: Integer
RxDrOffset1: Integer
RxDataRate2: Integer
RxFreq2: Integer
FactoryPresetFreqsList:
    - Integer
```
