### ISSUE TITLE
Allow CloudFormation variables in OpenAPI specs

### ISSUE THREAD

**Issue by andyRokit** [aws-cloudformation/cloudformation-coverage-roadmap#1232]
### Name of the resource

AWS::ApiGateway::RestApi

### Description

**Desired change**
When creating an API Gateway using an OpenAPI spec, allow CF variables to be used in the spec.  CF would resolve the variables before making the call to the API Gateway service.

**Reason for change**
OpenAPI specs have become a standard for describing HTTP APIs.  When creating a gateway in this manner you're moving out of "CloudFormation land".  However, there may be a need to reference various AWS resources from that spec.

E.g. The Gateway team have provided OpenAPI extensions to describe API integrations.  So, I might want to have a method call a specified Lambda function, using a specified IAM role:
```
x-amazon-apigateway-integration:
  type: aws
  uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${myLambdaFunction.Arn}/invocations
  credentials: ${myApiGatewayRole.Arn}
```

For a newly deployed (or updated) stack, various things will not have hard-coded values, so having the ability to include CF resources in this description would be a benifit.

**Current workaround**
The best approaches [1][2] I've found to work around this issue involve uploading the OpenAPI spec to S3, then injecting directly back into the template using `AWS::Include`.  However, in the words of the author of [1], this "feels really hacky".

**CDK: Follow-on feature request**
If this FR is implemented, it will still require another hack for CDK to take full advantage of.  CDK generates Logical IDs for CF resources at runtime, therefore, the reference to them in the spec will break.  Workaround [1] gets around this be overriding the generated IDs with static ones.  The need for this hack could be removed by updating CDK to update CF refs when creating the asset for the definition body.

E.g.

my-openapi-spec.yaml
```
x-amazon-apigateway-integration:
  credentials: ${myApiGatewayRole.Arn}
```

my-stack.ts
```
const myApiGatewayRole = new iam.Role(this, 'myApiGatewayRole', ...)
```

asset.############.yaml
```
x-amazon-apigateway-integration:
  credentials: ${myGatewayStack-myApiGatewayRole-1SSDY2TNMRSS8.Arn}
```

[1] https://stackoverflow.com/questions/62179893/aws-cdk-how-to-create-an-api-gateway-backed-by-lambda-from-openapi-spec/62811530#62811530  
[2] https://scratchpad.blog/serverless/howto/configure-aws-api-gateway-with-swagger/

**Comment by benbridts** [comment]
This should already be possible if you do not pass the openapi definition as a string:

eg:
```yaml
Api:
  Type: AWS::ApiGateway::RestApi
  Properties: 
    Body:
      x-amazon-apigateway-integration:
        credentials: !Sub ${myApiGatewayRole.Arn}
```

If a string is required, you should be able to do something like:

```yaml
Api:
  Type: AWS::ApiGateway::RestApi
  Properties: 
    Body: !Sub |
      x-amazon-apigateway-integration:
        credentials: ${myApiGatewayRole.Arn}
```
