### ISSUE TITLE
AWS::EC2::NetworkInterface bug when decreasing SecondaryPrivateIpAddressCount

### ISSUE THREAD

**Issue by davmayd** [aws-cloudformation/cloudformation-coverage-roadmap#1249]
### Name of the resource

AWS::EC2::NetworkInterface

### Resource Name

AWS::EC2::NetworkInterface

### Issue Description

If an ENI is deployed with SecondaryPrivateIpAddressCount set to N, a stack update with the value set to N+1 is successful, however a stack update with the value set to N-1 is unsuccessful; the stack update completes successfully but the number of secondary IP addresses assigned to the ENI doesn't actually decrease.

### Expected Behavior

A stack update with a lower number of secondary IP addresses specified should decrease the number of secondary IP addresses assigned to the ENI

### Observed Behavior

A stack update with a lower number of secondary IP addresses specified does not actually result in fewer secondary IP addresses assigned to the ENI

### Test Cases

Deploy the following CloudFormation template, then perform a stack update with a lower number of secondary IP addresses specified:

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Eni:
    Type: AWS::EC2::NetworkInterface
    Properties:
      GroupSet: [ MY_SG ]
      SecondaryPrivateIpAddressCount: 3
      SubnetId: MY_SUBNET
Outputs:
  NodeSecondaryPrivateIPs:
    Value:
      Fn::Join:
        - ', '
        - Fn::GetAtt:
            - Eni
            - SecondaryPrivateIpAddresses
```
