### ISSUE TITLE
Macro transformation stuck in IN_PROGRESS if resulting template is not valid

### ISSUE THREAD

**Issue by weeniearms** [aws-cloudformation/cloudformation-coverage-roadmap#1251]
### Name of the resource

Other

### Issue Description

A stack that includes any sort of macro transform (both custom ones and things like AWS::Serverless) and where the template contains invalid CFN (e.g. an incorrect type specification on a resource that is not modified by the macro) will end up stuck in a IN_PROGRESS state forcing the user to either wait for the operation to time out or cancel it manually.
Moreover, there's no error response that would tell the user what's wrong with the template and the initial template validation (i.e. the one performed when submitting the create/update request) seems to ignore these types of errors (which is kind of expected due to the fact that the pre-transform template is likely not valid CFN).

### Expected Behavior

Stack create/update is stuck in an IN_PROGRESS state with no clear indication of any issues with the template.

### Observed Behavior

Stack create/update is stuck in an IN_PROGRESS state with no clear indication of any issues with the template.

### Test Cases

Create a stack using the following template (notice the single `:` in the queue type definition):
```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
  MyQueue:
    Type: AWS::SQS:Queue
```
