### ISSUE TITLE
Fix a bug in Fn::If intrinsic function usage in nested Modules

### ISSUE THREAD

**Issue by niharkarra** [aws-cloudformation/cloudformation-coverage-roadmap#1257]
### Name of the resource

Other

### Issue Description

 Issue while using Fn::If in template which has modules.

Template error: Fn::If cannot be preprocessed

Place of usage of Fn::If:

```
   MyResource: 
        Type: XXXX::AWS::S3::MODULE 
        Properties: 
            BucketName: xxxxxx
            AdditionalPolicySet: !If [IsProduction, true, false] 
```

### Expected Behavior

Fn::If should resolve normally

### Observed Behavior

Template error: Fn::If cannot be preprocessed

**Comment by MalikAtalla-AWS** [comment]
Hey @niharkarra,
thanks for raising this issue. Based on your description I'm not able to reproduce it. Would you mind giving us a concrete example that reproduces the issue, including the main template and the module fragment?

Here is what I tried:
 * I registered a module called Malik::Test::Test::MODULE. I used the default module generated by the cfn-cli without changes
 * I created a stack with the below template which includes an Fn::If as part of the parameter passed into the module
 * The stack was created successfully and the bucket has the expected name

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Conditions:
  IsProd:
    Fn::Equals:
      - prod
      - prod
Resources:
  MyModule:
    Type: "Malik::Test::Test::MODULE"
    Properties:
      BucketName: !If [IsProd, bucketname243563445, bucketname25643534]
```

**Comment by MalikAtalla-AWS** [comment]
I'll close this issue for now. Feel free to reopen it, if you think it persists.

**Comment by JGSweets** [comment]
@MalikAtalla-AWS I'm currently encountering this error with the current example.


```yaml
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Var1:
    Type: String
    Default: ''
  Var2:
    Type: String
    Default: ''

Conditions:
  BothVarsFilled: !And
    - !Not
      - !Equals
        - !Ref Var1
        - ''
    - !Not
      - !Equals
        - !Ref Var2
        - ''

Resources:
  MyModule:
    Type: "Malik::Test::Test::MODULE"
    Properties:
      AreBothVarsFilled: !If [BothVarsFilled, true, false]
```
