### ISSUE TITLE
[AWS::AppStream::Stack][Drift] False Positive Drift for Tags and UserSettings for resource AWS::AppStream::Stack

### ISSUE THREAD

**Issue by surbhbh** [aws-cloudformation/cloudformation-coverage-roadmap#1258]
### Name of the resource

AWS::AppStream::Stack

### Issue Description

Facing False-Positive Drift for Tags and UserSettings for resource AWS::AppStream::Stack
The report is complaining about missing UserSettings + Tags. The actual resource has the same UserSettings + Tags as defined in the CFN template. 

False Drift doesn't occur in Self-Service AWS::AppStream::Stack(in us-east-1). It only occurs in eu-central-1 which is for resource AWS::AppStream::Stack.

### Expected Behavior

Status should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

Expected:
UserSettings and Tags should be defined.

Actual:
Missing UserSettings and Tags information.

### Test Cases

Resources:
  AppStreamStack:
    Type: 'AWS::AppStream::Stack'
    Properties:
      DisplayName: AppStreamStack
      Name: AppStreamStackNAme
      UserSettings:
        - Action: CLIPBOARD_COPY_FROM_LOCAL_DEVICE
          Permission: ENABLED
        - Action: CLIPBOARD_COPY_TO_LOCAL_DEVICE
          Permission: ENABLED
        - Action: FILE_DOWNLOAD
          Permission: DISABLED
        - Action: FILE_UPLOAD
          Permission: DISABLED
        - Action: PRINTING_TO_LOCAL_DEVICE
          Permission: DISABLED
      Tags:
        - Key: ApplicationName
          Value: ApplicationValue

**Comment by liuyimi** [comment]
Hey surbhbh, AppStream engineer here! 

I tried using the same template to create AppStream fleet in both us-east-1 and eu-central-1 but couldn't reproduce the issue. Could you please double check if it's transient?

**Comment by rgoltz** [comment]
Hi @liuyimi . Robert here. I've raised this issue with @surbhbh . We see this issue in eu-central-1 region for existing stacks. Could you please re-check in eu-central-1 and inform back on your results. In case of needed, I can share more details on this issue here.

@AidenAtSea - Why you removed the bug label?

**Comment by liuyimi** [comment]
@rgoltz Thanks for reply. 

Based on "We see this issue in eu-central-1 region for existing stacks", I tried below steps:
1. create a stack in FRA with below template 
```
    Type: 'AWS::AppStream::Stack'
    Properties:
      DisplayName: 'AppStreamStack'
      Name: 'AppStreamStackNAme'
```
2. verified UserSettings are as default and no tags.
3. update CFN template by adding UserSettings and tags
```
UserSettings:
        - Action: CLIPBOARD_COPY_FROM_LOCAL_DEVICE
          Permission: ENABLED
        - Action: CLIPBOARD_COPY_TO_LOCAL_DEVICE
          Permission: ENABLED
        - Action: FILE_DOWNLOAD
          Permission: DISABLED
        - Action: FILE_UPLOAD
          Permission: DISABLED
        - Action: PRINTING_TO_LOCAL_DEVICE
          Permission: DISABLED
      Tags:
        - Key: 'ApplicationName'
          Value: 'ApplicationValue'
```
4. Verified UserSettings on the stack is updated and tags are added.

I didn't observe any unexpected behavior in the process. Could you please provide more details on how to reproduce?
