### ISSUE TITLE
Missing intrinsic function for Condition, Rules, and Properties - `Fn::RegExp`/`!RegExp` -> `Boolean`

### ISSUE THREAD

**Issue by autumnjolitz** [aws-cloudformation/cloudformation-coverage-roadmap#1261]
### Name of the resource

Other

### Resource name

AWS::Cloudformation

### Description

Discussion within #1260 has indicated a more generic/powerful solution for a boolean intrinsic function named `Fn::RegExp` is needed.

Use cases of an `Fn::RegExp` function may include (but not limited to) 

- Checking that `!Ref` outputs are within expected return value domains
- Checking compliance for `!Ref 'AWS::StackName'`
- Checking that the regions input or output for ARNs are the same or matching to `!Ref 'AWS::Region'`
- Verifying that combination of input values like for a domain name are well formed

Suggested forms of`Fn::RegExp`` / `!RegExp` anchor to follow:

JSON: `{ "Fn::RegExp" : [ String,  String ] }`
YAML Full Function:
```
Fn::RegExp:
  - String
  - String
``` 
YAML short form:
```
!Sub
  - String
  - String
```

Example use cases:

1.  Newcorp requires Stack Names to have the department included in the name

```
Parameters:
    Department:
        Type: String
        AllowedValues:
          - 'Engineering'
          - 'Finance'
          - 'IT'
Rules:
  ValidateStackName:
    Assertions:
      -
        Assert: Fn::RegExp 
            - !Sub
                - "^newcorp-${Department}-.+$"
             -  !Ref 'AWS::StackName' 
        AssertDescription: "StackNames at newcorp- for a Department must have the correct Department name in the Stack."
```

2. Newcorp has a complex stack and it takes a while for the resources that use/consume an Amazon Certiificate Manager ARN to occur. Immediately catching the mismatch between ARN region and Stack Region quickly can prevent the cost of creating resources by allowing validation to catch the stack before it creates/updates with an unusable value

```
Parameters:
  TLSCertificateArn:
    Type: String
    # Insist that we are passed an acm ARN:
    AllowedPattern: 'arn:([^:\\n]*):acm:([^:\\n]*):([^:\\n]*):certificate\\/(.*)'
    # Oh, how can I prevent a mistake where the an incorrrect ARN is pushed in and the
    # stack takes a while to get to using the certificate?

Rules:
  # Let's make sure that we don't make a mistake here - prove the ARN
  # is inside our Stack's region.
  ValidateACMArn:
    Assertions:
      -
        Assert:
          Fn::RegExp:
            - !Sub "^arn:([^:\\n]*):acm:${AWS::Region}:([^:\\n]*):certificate\\/(.*)$"
            - !Ref 'TLSCertificateArn' 
        AssertDescription: "ACM certificates must be in the same region as the CloudForrmationStack"

```
