### ISSUE TITLE
AWS::ImageBuilder::Image  delete AMI when the stack is deleted

### ISSUE THREAD

**Issue by mhtrinhLIC** [aws-cloudformation/cloudformation-coverage-roadmap#1277]
### Name of the resource

AWS::ImageBuilder::Image

### Description

I am using AWS::ImageBuilder::Image through CDK [CfnImage](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_imagebuilder.CfnImage.html), so the please let me know if it's a CDK question.

Currently, AMI are created with AWS::ImageBuilder::Image in the stack. But when the stack is deleted, the AMI is still there. Is this expected ?

I would expect it to be deleted along side with the stack as any other resource type.  Or is it possible to have a Rention flag option ?

**Comment by tarunb12** [comment]
Deletion of underlying resources is supported in CloudFormation now, with the `DeletionSettings` property on [AWS::ImageBuilder::Image](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-imagebuilder-image.html). Example:

```yaml
Image:
  Type: AWS::ImageBuilder::Image
  Properties:
    # Deletes underlying AMIs/containers on replace/delete
    DeletionSettings:
      ExecutionRole: !Ref 'LifecycleExecutionRole'
    ...
```
