### ISSUE TITLE
CloudFormation reports incorrect drift for AWS::ECS::TaskDefinition which have EFSVolumeConfiguration

### ISSUE THREAD

**Issue by MarkCBell** [aws-cloudformation/cloudformation-coverage-roadmap#1283]
### Name of the resource

AWS::ECS::TaskDefinition

### Issue Description

When performing drift detection on a stack containing an `AWS::ECS::TaskDefinition` that includes a volume, CloudFormation does not measure any `EFSVolumeConfiguration`. This means that for stack whose template defines an `EFSVolumeConfiguration` even if the stack's resources are built correctly, the stack is immediately reported as drifted.

### Expected Behavior

When performing drift detection on an `AWS::ECS::TaskDefinition`, the deployed resource's `EFSVolumeConfiguration` should be measured.

### Observed Behavior

When performing drift detection on an `AWS::ECS::TaskDefinition`, it's "actual" `EFSVolumeConfiguration` is always reported as null regardless of what has actually been deployed. Therefore, if the template defines an `EFSVolumeConfiguration` then this results in the stack being incorrectly reported as drifted even if the resource has been successfully deployed matching the template.

### Test Cases

Deploy the following CloudFormation template as a stack:
```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem

  ECSCluster:
    Type: AWS::ECS::Cluster

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: TestContainer
          Image: helloworld
      Memory: 1024
      Volumes:
        - Name: efs_fs
          EFSVolumeConfiguration:
            FileSystemId: !Ref EFSFileSystem
```
Now run a drift detection and note that the `ECSTaskDefinition` is listed as "Modified" with the drift details showing that a `Volumes.0.EFSVolumeConfiguration` property was expected but was not found on the resources (even though it is present). Note that similar effects are seen for all other `EFSVolumeConfiguration` volume properties (e.g. `TransitEncryption: ENABLED`).
