### ISSUE TITLE
`AWS::Amplify::App` - Support for specifying a `buildImage`

### ISSUE THREAD

**Issue by david-perez** [aws-cloudformation/cloudformation-coverage-roadmap#1299]
### Name of the resource

AWS::Amplify::App

### Description

Currently, one is able to specify custom build images (e.g. from ECR) in which to run the build spec of an AWS Amplify application using the AWS Console: https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html

However, there is no way to do so in CFN: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amplify-app.html#cfn-amplify-app-buildspec. You can specify the `buildSpec`, but not the `buildImage`.

And hence no way to do so in the CDK: https://github.com/aws/aws-cdk/issues/15016

**Comment by dbartholomae** [comment]
I recently had a similar question (#1140), and there seems to be an environment variable called `_CUSTOM_IMAGE`. I haven't tried it yet, though.

**Comment by ferdingler** [comment]
Hi @david-perez , apologies for the delay here. @dbartholomae is correct, you can actually set the custom image as an environment variable `_CUSTOM_IMAGE` with a value of your ECR registry. In CloudFormation, this would be something like 

```yml
MyApp:
  Type : AWS::Amplify::App
  Properties:
      EnvironmentVariables:
          - Key: _CUSTOM_IMAGE
          - Value: 1234.ecr.aws/foo/build-image.al2-20220929223003
```
