### ISSUE TITLE
Add usage of Kms KeyAlias for KmsKeyId property under AWS::RDS::DBInstance resource

### ISSUE THREAD

**Issue by vmusaa** [aws-cloudformation/cloudformation-coverage-roadmap#1307]
### Name of the resource

AWS::RDS::DBInstance

### Description

The KmsKeyId property for the AWS::RDS::DBInstance resource is marked as drifted when just the Id (not full ARN) is specified in the template and the stack is created.

Ideally, drift detection should not have been performed on the KmsKeyId property as per - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#drift-considerations

`CloudFormation does not perform drift detection on the KMSKeyId property of any resources. Because AWS KMS keys can be referenced by multiple aliases, CloudFormation can't guarantee consistently accurate drift results for this property.`

### Expected Behavior

The KmsKeyId property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The KmsKeyId property is marked as NOT_EQUAL with
expected = alias/xxxx-xxxx-xxxx-xxxx
actual = xxxx-xxxx-xxxx-xxxx

### Test Cases

Steps to reproduce -

1) Create Stack using following template -
```
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: MyFirstDB
      Engine: MySQL
      MasterUsername: master
      MasterUserPassword: xxxxxxxx
      DBInstanceClass: db.m5.large
      StorageEncrypted: true
      VPCSecurityGroups: sg-xxxxx
      KmsKeyId: xxxx-xxxx-xxxx-xxxx
```
2) Run drift detection
3) View drift results

### Enhancement Request Ask - 
Add feature which allows using Kms KeyAlias while specifying KmsKeyID in AWS::RDS::DBInstance resource.
