### ISSUE TITLE
Adding OptionName "NATIVE_NETWORK_ENCRYPTION" in resource AWS::RDS::OptionGroup results in drift

### ISSUE THREAD

**Issue by vmusaa** [aws-cloudformation/cloudformation-coverage-roadmap#1310]
### Name of the resource

AWS::RDS::OptionGroup

### Resource Name

AWS::RDS::OptionGroup

### Issue Description

When you create an OptionName `NATIVE_NETWORK_ENCRYPTION `it adds automatically 10 option settings.

Please check the screenshot attached 
![image](https://user-images.githubusercontent.com/109794581/188619006-16eb4b1c-572b-4dc2-bda7-b6b098621de0.png)

### Expected Behavior

The drift detection should be aware of these option settings being added when the option Name `NATIVE_NETWORK_ENCRYPTION ` is mentioned. 

### Observed Behavior

The cloud formation stack creates 10 additional option settings which results in a false-positive drift. 

### Test Cases

Add option name `NATIVE_NETWORK_ENCRYPTION` in the resource AWS::RDS::OptionGroup. 

### Cloud formation sample template reference - 
```
Resources: 
  DBOptionGroup:
    Type: AWS::RDS::OptionGroup
    Properties:
      EngineName: MYSQL
      MajorEngineVersion: 19
      OptionGroupDescription: some description
      OptionConfigurations:
      - OptionName: NATIVE_NETWORK_ENCRYPTION
        OptionSettings:
        - Name: SQLNET.CRYPTO_CHECKSUM_SERVER
          Value: ACCEPTED
```
2) Now run drift detection 
3) Observe the results
