### ISSUE TITLE
AWS::AppSync::GraphQLApi fails to create if service linked role does not exist

### ISSUE THREAD

**Issue by corymhall** [aws-cloudformation/cloudformation-coverage-roadmap#1315]
### Name of the resource

AWS::AppSync::GraphQLApi

### Issue Description

If you create a GraphQL Api with `XrayEnabled: true` the deployment will fail with the error message:

```
Failed to assume service-linked role arn:aws:iam::XXXXXXXXXXXX:role/aws-service-role/appsync.amazonaws.com/AWSServiceRoleForAppSync, please retry. (Service: AWSAppSync; Status Code: 403; Error Code: AccessDeniedException; Request ID: 30c42675-ab80-4a2b-9ae5-51ca30bfaa9e; Proxy: null)
```

```yaml
Parameters:
  graphQlApiName:
    Type: String
  userPoolId:
    Type: String
  userPoolAwsRegion:
    Type: String
  defaultAction:
    Type: String
Resources:
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name:
	Ref: graphQlApiName
      XrayEnabled: true
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      UserPoolConfig:
        UserPoolId:
          Ref: userPoolId
        AwsRegion:
          Ref: userPoolAwsRegion
        DefaultAction:
          Ref: defaultAction


```

### Expected Behavior

The service linked role should be created for you if it does not exist and the deployment should succeed. 

### Observed Behavior

See error message in description

### Test Cases

N/A
