### ISSUE TITLE
AWS::S3::Bucket - NoncurrentVersionExpiration - Drift detection false-positive

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1317]
### Name of the resource

AWS::S3::Bucket

### Issue Description

AWS::S3::Bucket [NoncurrentVersionExpiration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration.html#cfn-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration-newernoncurrentversions) is reporting false-positive drift detection results.

### Expected Behavior

Freshly Cloudformation-provisioned Buckets which include the [NoncurrentVersionExpiration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration.html#cfn-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration-newernoncurrentversions) should **NOT** be reported as drifted.

### Observed Behavior

Provisioning a Bucket with [NoncurrentVersionExpiration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration.html#cfn-s3-bucket-lifecycleconfig-rule-noncurrentversionexpiration-newernoncurrentversions) property defined reports as being drifted, despite no changes being made.

### Test Cases

1.  Deploy sample template

```aws cloudformation deploy --stack-name drift-on-S3-NoncurrentVersionExpiration --template-file template.yaml --capabilities CAPABILITY_IAM```

```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
        - NoncurrentVersionExpiration:
            NewerNoncurrentVersions: 10
            NoncurrentDays: 30
          Status: Enabled
```

2. Detect drift
```aws cloudformation detect-stack-drift --stack-name drift-on-S3-NoncurrentVersionExpiration```

3. Show drift results
```aws cloudformation describe-stack-resource-drifts --stack-name drift-on-S3-NoncurrentVersionExpiration```

```
StackResourceDrifts:
- ActualProperties: '{"LifecycleConfiguration":{"Rules":[{"Status":"Enabled"}]}}'
  ExpectedProperties: '{"LifecycleConfiguration":{"Rules":[{"NoncurrentVersionExpiration":{"NewerNoncurrentVersions":10,"NoncurrentDays":30},"Status":"Enabled"}]}}'
  LogicalResourceId: Bucket
  PhysicalResourceId: drift-on-s3-noncurrentversionexpiration-bucket-xxxxxxxx
  PropertyDifferences:
  - ActualValue: 'null'
    DifferenceType: REMOVE
    ExpectedValue: '{"NewerNoncurrentVersions":10,"NoncurrentDays":30}'
    PropertyPath: /LifecycleConfiguration/Rules/0/NoncurrentVersionExpiration
  ResourceType: AWS::S3::Bucket
  StackId: xxxxxxxxxxxxxxxxxx
  StackResourceDriftStatus: MODIFIED
  Timestamp: '2022-09-12T14:35:12.342000+00:00'
```

4. Confirm physical resource is correct

```python sdk.py```

```
import boto3

s3 = boto3.client('s3')

response = s3.get_bucket_lifecycle_configuration(
    Bucket='drift-on-s3-noncurrentversionexpiration-bucket-xxxxxxxxxx',
    ExpectedBucketOwner='00000000'
)

print(response['Rules'])
```

Output:
```
[{'ID': 'YzUxZTc1NDctMDE0Zi00ZTQxLTasdjQtNzNiNDM5Yjk0M32k', 'Filter': {'Prefix': ''}, 'Status': 'Enabled', 'NoncurrentVersionExpiration': {'NoncurrentDays': 30}}]
```
