### ISSUE TITLE
(AWS::ApiGateway::RestApi) False-positive drift on ApiGateway RestApi.Policy property

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1322]
### Name of the resource

AWS::ApiGateway::RestApi

### Issue Description

Cloudformation drift detection is incorrectly reporting AWS::ApiGateway::RestApi [Policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-policy) property as having drifted.

### Expected Behavior

Drift detection should report as IN_SYNC.

### Observed Behavior

A freshly created stack is showing the Policy property as having drifted.

### Test Cases

1. Create stack including AWS::ApiGateway::RestApi with Policy property defined.

```
policy = iam.PolicyDocument(
            statements=[iam.PolicyStatement(
                actions=["kms:Create*", "kms:Describe*", "kms:Enable*", "kms:List*", "kms:Put*"
                         ],
                principals=[iam.ServicePrincipal("lambda.amazonaws.com")],
                resources=["*"]
            )]
        )

        api = apigateway.SpecRestApi(self, "ExampleRestApi",
                                     api_definition=apigateway.ApiDefinition.from_asset(
                                         "assets\petstore_api_definition.json"),
                                     policy=policy,
                                     )
```

[petstore_api_definition.json](https://gist.github.com/greg5123334/0d2a96bdc23b03927b1b3753b6052c6c)

2. Detect Drift
3. Observe drift results report Policy as drifted.

*Expected*
```
{
  "Name": "ExampleRestApi",
  "Policy": {
    "Statement": [
      {
        "Action": [
          "kms:Create*",
          "kms:Describe*",
          "kms:Enable*",
          "kms:List*",
          "kms:Put*"
        ],
        "Effect": "Allow",
        "Principal": {
          "Service": "lambda.amazonaws.com"
        },
        "Resource": "*"
      }
    ],
    "Version": "2012-10-17"
  }
}
```

*Actual*
```
{
  "Name": "ExampleRestApi"
}
```

**Comment by 3oris** [comment]
Hi we are experiencing the same:

A policy that we deploy as part of a CDK stack like so:
```
new PolicyStatement({
  principals: [new AccountPrincipal('111222333444')],
  actions: ['execute-api:Invoke'],
  resources: ['execute-api:/dev/POST/my-resource/*'],
})
```
and where we can verify that the policy was actually deployed:
```
$ aws apigateway get-rest-api --rest-api-id 1axxxxx78
{
    "id": "1axxxxx78",
    "name": "development",
    ...
    "endpointConfiguration": {
        "types": [
            "REGIONAL"
        ]
    },
    "policy": "{\\\"Version\\\":\\\"2012-10-17\\\",\\\"Statement\\\":[{\\\"Effect\\\":\\\"Allow\\\",\\\"Principal\\\":{\\\"AWS\\\":\\\"arn:aws:iam::111222333444:root\\\"},\\\"Action\\\":\\\"execute-api:Invoke\\\",\\\"Resource\\\":\\\"arn:aws:execute-api:eu-central-1:123456789012:1axxxxx78\\/dev\\/POST\\/my-resource\\/*\\\"}]}",
    "disableExecuteApiEndpoint": false
}
```

will result in a drift like this:

**Expected:**
```
{
  "EndpointConfiguration": {
    "Types": [
      "REGIONAL"
    ]
  },
  "Name": "development",
  "Policy": {
    "Statement": [
      {
        "Action": "execute-api:Invoke",
        "Effect": "Allow",
        "Principal": {
          "AWS": [
            "arn:aws:iam::111222333444:root"
          ]
        },
        "Resource": "execute-api:/dev/POST/my-resource/*"
      }
    ],
    "Version": "2012-10-17"
  }
}
```
**Actual:**
```
{
  "EndpointConfiguration": {
    "Types": [
      "REGIONAL"
    ]
  },
  "Name": "development"
}
```
**So the output of `Actual` is just wrong.**

One observation to make here:
As you can see from the cli output above, the given resource
```
execute-api:/dev/POST/my-resource/*
```
had been expanded to
```
arn:aws:execute-api:eu-central-1:123456789012:1axxxxx78/dev/POST/my-resource/*
```
including the rest api id during deployment.

**Comment by rgoltz** [comment]
I've re-tested this issue in eu-central-1. Unfortunately the stacks still showing a drift for `AWS::ApiGateway::RestApi` regarding `Policy` property after running a fresh Drift Detection in our accounts in eu-central-1. 

In case you like to take a look, I've shared the stack ARN via case 11993682621. May it would take some more time until the fix is deployed to eu-central-1 / getting active in our AWS accounts? - I'm at your disposal to re-run the tests at any time required. Please update us here as well (and -please- keep github issues open until the fix is confirmed/rolled out).

**Comment by yuileroy** [comment]
The [public doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-policy) mentions Policy shall be Type: Json.
While the current implementation of AWS::ApiGateway::RestApi Policy is
```
"Policy": {
    "type": [
        "object",
        "string"
    ]
},
```
You can find it in CloudFormation console, Registry: Activated extensions, AWS::ApiGateway::RestApi.

For drift detection, only one format is supported and it's chose to be string. 
So to avoid drift detection, customer can convert the Policy json payload to string in CFN template.

**Comment by yuileroy** [comment]
For valid `execute-api` ARN, please refer to https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html 
```
arn:partition:execute-api:region:account-id:api-id/stage/http-method/resource-path
```

**Comment by rgoltz** [comment]
@yuileroy - We are also affected of this CFN drift detection issue. We are using "plain CloudFormation YAML-definition" like below:

```yaml
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Policy:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: "*"
          Action: execute-api:Invoke
          Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*
          Condition:
            IpAddress:
              aws:SourceIp:
              #store1
              - 52.52.190.1
              - 52.52.190.2
              #store2
              - 71.100.197.161
              - 71.100.197.162
              - 71.100.197.163
              - 71.100.197.164
              - 71.100.197.165
              - 71.100.197.166
              - 71.100.199.161
              - 71.100.199.162
              - 71.100.199.163
              - 71.100.199.164
              - 71.100.199.165
              - 71.100.199.166
              - 71.100.196.192/26
              #store3
              - 61.150.192.224/27
      ApiKeySourceType: 'HEADER'
      Description: !Sub "${App}-${Env}-${InterfaceName}"
      Name: !Sub "${App}-${Env}-${InterfaceName}"
      EndpointConfiguration:
        Types:
          - 'REGIONAL'
```

From my understanding we are already using string payload for the policy. 

The Drift Detection reporting this example above like this:
![image](https://user-images.githubusercontent.com/16392819/222725965-6fb92fc7-89ed-4ce8-8c39-43124fa9809b.png)
(There is no Actual - Even the API Gateway have/using this Policy!)

**Comment by yuileroy** [comment]
Above Policy is actually an object, not string. Below is string example.
```
Policy: >-
        {"Version":"2012-10-17","Statement":
        [{"Effect":"Allow","Principal":"*","Action":"*","Resource":"*"}]}

or

Policy: '{"Version":"2012-10-17","Statement": [{"Effect":"Allow","Principal":"*","Action":"*","Resource":"*"}]}'
```

**Comment by ZalmnS** [comment]
Highlighting the differences in example templates for clarity:


Shows a Drfited Status:

```
Resources:
  APIGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Policy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'execute-api:Invoke'
            Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*'
            Condition:
              IpAddress:
                'aws:SourceIp':
                  - 52.52.190.3
                  - 52.52.190.2
                  - 71.100.197.161
                  - 71.100.197.162
                  - 71.100.197.163
                  - 71.100.197.164
                  - 71.100.197.165
                  - 71.100.197.166
                  - 71.100.199.161
                  - 71.100.199.162
                  - 71.100.199.163
                  - 71.100.199.164
                  - 71.100.199.165
                  - 71.100.199.166
                  - 71.100.196.192/26
                  - 61.150.192.224/27
      ApiKeySourceType: HEADER
      Name: TestAPI
      EndpointConfiguration:
        Types:
          - REGIONAL

```
<img width="1550" alt="Screen Shot 2023-03-17 at 11 41 07 AM" src="https://user-images.githubusercontent.com/105826262/225991379-350dd5b2-ada9-4f19-8425-a159257d35a7.png">




Shows a Non Drifted Status:


```
Resources:
  APIGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Policy: >-
        {"Version":"2012-10-17","Statement":
        [{"Effect":"Allow","Principal":"*","Action":"execute-api:Invoke","Resource":"!Sub
        arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*","Condition": {"IpAddress": {"aws:SourceIp": ["52.52.190.3","52.52.190.2","71.100.197.161","71.100.197.162","71.100.197.163","71.100.197.164","71.100.197.165","71.100.197.166","71.100.199.161","71.100.199.162","71.100.199.163","71.100.199.164","71.100.199.165","71.100.199.166","71.100.196.192/26","61.150.192.224/27"]}}}]}
      ApiKeySourceType: HEADER
      Name: TestAPI
      EndpointConfiguration:
        Types:
          - REGIONAL
```
<img width="1550" alt="Screen Shot 2023-03-17 at 11 25 42 AM" src="https://user-images.githubusercontent.com/105826262/225991776-719578e3-8914-4b19-8f30-04d5dcd65020.png">
