### ISSUE TITLE
AWS::CodeStarNotifications::NotificationRule - Drift detection false-positive once adding stack-level tags

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1329]
### Name of the resource

AWS::CodeStarNotifications::NotificationRule

### Issue Description

Once you create add tags on stack-level and your stack containing a `AWS::CodeStarNotifications::NotificationRule`, the CloudFormation drift detection reporting such stack as drifted (details see "Observed Behavior").

### Expected Behavior

* AWS::CodeStarNotifications::NotificationRule has tags from stack
* CloudFormation drift detection understand this and does not report this as drift

### Observed Behavior

Once you adding Stack-Level-Tags your AWS::CodeStarNotifications::NotificationRule is marked as drifted.

### Test Cases

1) create a new stack with this template (along with step 2)- here in my test-case in region eu-central-1:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack with Tagged CodeStarNotifications - case 10851630161

Resources:
  CodeStarNotificationWithTagsFromStack:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      Name: 'rogoECS-Sandbox-Pipeline-TestRuleTagViaStack1'
      DetailType: FULL
      Resource: 'arn:aws:codepipeline:eu-central-1:<ACCOUNTID>::AwsECS-Sandbox-Pipeline'
      EventTypeIds: 
        - codepipeline-pipeline-pipeline-execution-succeeded
      Targets: 
        - TargetType: SNS 
          TargetAddress: 'arn:aws:sns:eu-central-1:<ACCOUNTID>:Some_Email_Notification'
```

2) during create please **add tags to the stack**:
![github_addTags](https://user-images.githubusercontent.com/16392819/192209419-d6c01758-c85c-4737-b424-56128261415a.PNG)

3) after creation is finished, please run drift detection. You should see this result:
![github_drift](https://user-images.githubusercontent.com/16392819/192209604-91fd24d3-0612-4118-87b0-ddff92d940ee.PNG)

### Other Details

* I was not able to check, if this stack-based tags are applied to AWS::CodeStarNotifications::NotificationRule
* There was an other (resolved) issue related this this case here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1223
