### ISSUE TITLE
AWS::EC2::instance (specify TagSpecification in EBS BlockDeviceMapping)

### ISSUE THREAD

**Issue by Remi-Faydide** [aws-cloudformation/cloudformation-coverage-roadmap#133]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> Specifying TagSpecification on creation for AWS::EC2::Instance Ebs Attribute is available since 28 Mar 2017 with API (https://aws.amazon.com/blogs/aws/new-tag-ec2-instances-ebs-volumes-on-creation/)
2. Scope of request -> Allow specifying tags in CloudFormation for EC2 instances.
3. Expected behavior -> In Create, it should allow specifying separate tags per volumes or same for every volumes or same tags than EC2 Instance.  At least it should allow tag creation, like the API allows.
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html
6. Category tag (optional) -> Compute / Storage
7. Any additional context (optional)

**Comment by whereisaaron** [comment]
https://github.com/weaveworks/eksctl/issues/778

**Comment by DanyC97** [comment]
@PatMyron @luiseduardocolon i saw you folks referenced this issue on the master issue #228 , any chance you have an update on this ? 


Asking as this lack of functionality does really impact myself and others in sorting out the EBS tagging which is a must to not waste the $$ down the pipe.
In my case i was using ASG with LC and tagging EBS vols inside userdata didn't cut very well as there are some limitation on the `!Sub` function and you can't do much of bash scripting with variables interpolation.

Moved to ASG with LT and while `TagSpecifications` works in some cases it doesn't if you have different EBS vols as below where you want the Tag's Name value to be dynamic 

```
      LaunchTemplateData:
        BlockDeviceMappings:
{% for i in range(StorageEbsNumVolumes) %}
          - DeviceName: /dev/xvd{{ vol_drive_letters[i] }}
            Ebs:
              VolumeSize: !Ref StorageEbsVolumeSize
              VolumeType: !Ref StorageEbsVolumeType
              DeleteOnTermination: !Ref StorageEbsDeleteOnTermination
{% endfor %}
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 100

```
