### ISSUE TITLE
AWS::ElasticLoadBalancingV2::Listener - Drift detection false-positive once adding stack-level tags

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1344]
### Name of the resource

AWS::ElasticLoadBalancingV2::Listener

### Issue Description

Once you create a stack + addings tags on stack-level (!) and your stack containing a `AWS::ElasticLoadBalancingV2::Listener`, the CloudFormation drift detection reporting such stack as drifted (details see "Observed Behavior").

### Expected Behavior

CloudFormation (Drift detection) should be aware that `AWS::ElasticLoadBalancingV2::Listener` doesn't support Tags yet, hence it's not possible to tag them yet -  and/or there is no supported by Drift detection as well.

### Observed Behavior

After adding Stack-Level-Tags to your stack containing a `AWS::ElasticLoadBalancingV2::Listener` and you getting a DRIFTED state for those stacks. This is misleading. Same happens for `AWS::ElasticLoadBalancingV2::ListenerRule`, see #1343

### Test Cases

** Create ALB and export it's ARN (in order to follow the example below)

** Create a new Stack with Stack-Level Tags:
![StackCreateWithStackTags1](https://user-images.githubusercontent.com/16392819/193080462-31d57f42-2470-4cdc-8f1b-55e36dd63fe9.PNG)

** Upload/Use the following sample-YAML-template:
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - Listener + ListenerRule - Tags shown as REMOVE - case 10884457561

Resources:
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - FixedResponseConfig:
          ContentType: text/plain
          MessageBody: Bad Request on ALB
          StatusCode: '400'
        Type: fixed-response
      LoadBalancerArn:
        Fn::ImportValue: ALBExportsOutputRef-ADD-HERE
      Port: 80
      Protocol: HTTP
  ALBListenerRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - FixedResponseConfig:
          ContentType: text/plain
          MessageBody: Method X-Forwarded-For Not Allowed
          StatusCode: '405'
        Type: fixed-response
      Conditions:
      - Field: http-header
        HttpHeaderConfig:
          HttpHeaderName: X-Forwarded-For
          Values:
          - "*"
      ListenerArn:
        Ref: ALBListener
      Priority: 1

```

** Run "Stack actions" => "Detect drift" in Console
![image](https://user-images.githubusercontent.com/16392819/193081932-7d0a49af-c353-4dff-9387-1d7c99b9c2d5.png)

** Stack is in state DRIFTED (even there were no changes outside of the stack) - Check the CloudFormation drift detection in Console:

![git__DriftOverview1](https://user-images.githubusercontent.com/16392819/193081632-fa3b3847-3d57-4d24-a239-e428957f54a3.jpg)

Please check the details:
![DriftListenerDetails1](https://user-images.githubusercontent.com/16392819/193084022-8a3698c6-ab20-4824-a3bc-451f814f7562.PNG)

### Other Details

* Often a stack contains different resources. It's a Best Practices following the AWS Cloud Development Kit (CDK) to add Tags on Stack-Level as well: https://docs.aws.amazon.com/cdk/v2/guide/tagging.html
