### ISSUE TITLE
AWS::ElasticLoadBalancingV2::TargetGroup - False-positive drift if ProtocolVersion is set in template

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1345]
### Name of the resource

AWS::ElasticLoadBalancingV2::TargetGroup

### Issue Description

Once you create a stack containing a `AWS::ElasticLoadBalancingV2::TargetGroup` and `ProtocolVersion` for TargetGroup, the CloudFormation drift detection reporting such stack as drifted - Even the ProtocolVersion is set correctly on the created TargetGroup (details see "Observed Behavior").

### Expected Behavior

Stack is in state IN_SYNC, since template and resource have the same, correct setting.

### Observed Behavior

Following https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/713 the setting `ProtocolVersion` is supported since Feb 2021. The CFN docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#cfn-elasticloadbalancingv2-targetgroup-protocolversion reflect this as well.

If you set `ProtocolVersion` in your CFN template (e.g. to `HTTP1` or `HTTP2`), you stack / this resource is in state DRIFTED after running CFN Drift detection - Details see: "Test Case".

### Test Cases

** Create new Stack using following example (please mind to adjust VpcId fitting your account) in eu-central-1

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - TargetGroup - ProtocolVersion issue - case 10896395411

Resources:
  TargetGroupWithProtocolVersionSet:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 120
      HealthCheckPath: "/alive.html"
      HealthCheckPort: '443'
      HealthCheckProtocol: HTTPS
      HealthCheckTimeoutSeconds: 60
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Name: rogo-test1-dev-TGrp
      Port: 443
      Protocol: HTTPS
      ProtocolVersion: HTTP2
      Tags:
      - Key: Environment
        Value: dev
      - Key: ReferenceName
        Value: 10896395411
      TargetGroupAttributes:
      - Key: stickiness.enabled
        Value: 'false'
      TargetType: instance
      UnhealthyThresholdCount: 2
      VpcId: vpc-xxHERE-YOU-IDxx
```

** After stack is created, please check your TargetGroup resource in Console for ProtocolVersion - Here in the example it's set to HTTP2 correctly.
![ProtocolVersion_Resource](https://user-images.githubusercontent.com/16392819/193309887-f5a1c4d9-2fb8-4303-9edb-f8b9bc9693a5.PNG)

** Go to CFN Console and run CFN Drift detection via: (in Console using "Stack actions" => "Detect drift". After you triggered this process, please wait for ca. 1 min and check again the Drift status: Stack went in state DRIFTED. Check the Drift-Details - You will that ProtocolVersion is not listed under "Actual", even it's in place within the TargetGroup:
![ProtocolVersion_DriftDetails](https://user-images.githubusercontent.com/16392819/193310164-2b5bb03f-2f07-49c7-9b6a-2be4fead2deb.PNG)
