### ISSUE TITLE
AWS::Kinesis::Stream does not support StreamMode ON_DEMAND in GovCloud

### ISSUE THREAD

**Issue by nagmesh** [aws-cloudformation/cloudformation-coverage-roadmap#1354]
### Name of the resource

AWS::Kinesis::Stream

### Issue Description

AWS::Kinesis::Stream  with StreamMode ON_DEMAND is not supported in GovCloud. 
Kinesis service supports ondemand but CloudFormation errors out with 

> Encountered unsupported property StreamModeDetails

### Expected Behavior

Kinesis stream is created successfully with SteamMode as ON_DEMAND

### Observed Behavior

Cloudformation errors out with 

```
2:40:17 PM | CREATE_FAILED        | AWS::Kinesis::Stream | LogsKinesisStreamCfn
Encountered unsupported property StreamModeDetails
```

### Test Cases

Template used:

```yaml
Resources:
  LogsKinesisStreamCfn:
    Type: AWS::Kinesis::Stream
    Properties:
      RetentionPeriodHours: 144
      StreamModeDetails:
        StreamMode: ON_DEMAND
```
Region: us-gov-west-1

### Other Details

CLI works in both us-gov-west-1 and us-gov-east-1

```
aws kinesis create-stream --stream-name test11 --stream-mode-details StreamMode=ON_DEMAND --region us-gov-west-1
```

**Comment by dhruvturakhia** [comment]
having a similar issue for ap-southeast-3

**Comment by StefanNiehaus** [comment]
I am also seeing this issue in GovCloud

**Comment by StefanNiehaus** [comment]
Any updates here?

**Comment by gdoermann** [comment]
I got it to work like this:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: On Demand Kinesis Data Stream 
Resources:
  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: my-data-stream
      RetentionPeriodHours: 24
      StreamModeDetails:
        StreamMode: "ON_DEMAND"
```
