### ISSUE TITLE
allow to use variable in resolve:ssm like !Sub '{{resolve:ssm:-SG-stack-name:1}}-GroupWebApp'

### ISSUE THREAD

**Issue by mkuendig** [aws-cloudformation/cloudformation-coverage-roadmap#136]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> !Sub '{{resolve:ssm:-SG-stack-name:1}}

2. Scope of request -> resolve:ssm:-variable is not supported and therfore only static values can be used.

3. Expected behavior -> variables can be used. Much more flexibility for SSM parameters.

**Comment by ikben** [comment]
One problem here is that this works already the other way around. The following code can construct part of the resolve from an input parameter

```
!Sub "{{resolve:ssm:-SG-stack-name:${VersionParameter}}}"
```

However, I feel like this problem is solvable with moving things around, or a `Join`, or a `Sub` with Variables. Let's try that:

I'm going to assume that this is the behaviour you want to emulate, but with the value of `Parameter` coming from SSM instead of being given as a parameter:

```
Parameters:
  Parameter:
    Type: String
Resources:
  Dummy:
    Type: AWS::SSM::Parameter
    Value: !Sub "Parameter is ${Parameter}"
```

One way to do that would be to use

```
Parameters:
  Parameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: SG-stack-name
Resources:
  Dummy:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub "Parameter is ${Parameter}"
```
This looks a bit clunky, and you can't use versions, but this will work.

Another approach would be to write it like this, which I think does what you're asking:

```
Resources:
  Dummy:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub
        - "Parameter is ${Parameter}"
        - Parameter: "{{resolve:ssm:SG-stack-name:1}}"
 ```

There are a few other ways I can read your request, but I don't see the use case of those (or I don't see how that's something you can do with normal parameters).

If this doesn't solve your issue, could you give a longer example of what you'd like to achieve?
