### ISSUE TITLE
Drift detection on AutoScalingGroup reports PropagateAtLaunch tag property as false-positive

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1365]
### Name of the resource

AWS::AutoScaling::AutoScalingGroup

### Issue Description

Cloudformation Drift-Detection is seemingly not aware of the PropagateAtLaunch tag property and thus reports a drift, regardless of how the property is defined in the template.

### Expected Behavior

Drift-Detection should report accurate results for tagged AutoScalingGroup resources.

### Observed Behavior

When deploying a stack containing an AWS::Autoscaling::AutoScalingGroup resource, regardless of whether [PropagateAtLaunch](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-tags.html#cfn-as-tags-PropagateAtLaunch) property is set to True or False, drift detection always reports the resource as having drifted.

### Test Cases

Steps:
1. Deploy stack containing AWS::AutoScaling::AutoScalingGroup
2. Detect Drift
3. View drift detection results

```aws cloudformation  describe-stack-resource-drifts --stack-name XXXXXXXXX```

PropagateAtLaunch=True
Expected:
```
{
  "LaunchConfigurationName": "LabStack-asgpropagatetagstrueLaunchConfigEF07B928-xxxxxxxxx",
  "MaxSize": 1,
  "MinSize": 1,
  "Tags": [
    {
      "Key": "One",
      "PropagateAtLaunch": true,
      "Value": "This is a tag"
    },
    {
      "Key": "Two",
      "PropagateAtLaunch": true,
      "Value": "This is also a tag"
    },
    {
      "Key": "Name",
      "PropagateAtLaunch": true,
      "Value": "LabStack/asg-propagatetags-true"
    }
  ],
  "VPCZoneIdentifier": [
    "subnet-xxxxxxxx",
    "subnet-xxxxxx",
    "subnet-xxxxxxxxxxx"
  ]
}
```
Actual:
```
{
  "LaunchConfigurationName": "LabStack-asgpropagatetagstrueLaunchConfigEF07B928-xxxxxxxxxxx",
  "MaxSize": 1,
  "MinSize": 1,
  "Tags": [
    {
      "Key": "One",
      "Value": "This is a tag"
    },
    {
      "Key": "Two",
      "Value": "This is also a tag"
    },
    {
      "Key": "Name",
      "Value": "LabStack/asg-propagatetags-true"
    }
  ],
  "VPCZoneIdentifier": [
    "subnet-xxxxxxxxxxx",
    "subnet-xxxxxxxxxxxxxx",
    "subnet-xxxxxxxxxxxxxx"
  ]
}
```

PropagateAtLaunch=False
Expected:
```
{
  "LaunchConfigurationName": "LabStack-asgpropagatetagsfalseLaunchConfigDE437164-Md9ksaAFMTWz",
  "MaxSize": 1,
  "MinSize": 1,
  "Tags": [
    {
      "Key": "One",
      "PropagateAtLaunch": false,
      "Value": "This is a tag"
    },
    {
      "Key": "Two",
      "PropagateAtLaunch": false,
      "Value": "This is also a tag"
    },
    {
      "Key": "Name",
      "PropagateAtLaunch": true,
      "Value": "LabStack/asg-propagatetags-false"
    }
  ],
  "VPCZoneIdentifier": [
    "subnet-xxxxxxxxxxxx",
    "subnet-xxxxxxxxxxxx",
    "subnet-xxxxxxxxxxx"
  ]
}
```
Actual:
```
{
  "LaunchConfigurationName": "LabStack-asgpropagatetagsfalseLaunchConfigDE437164-xxxxxxxxx",
  "MaxSize": 1,
  "MinSize": 1,
  "Tags": [
    {
      "Key": "One",
      "Value": "This is a tag"
    },
    {
      "Key": "Two",
      "Value": "This is also a tag"
    },
    {
      "Key": "Name",
      "Value": "LabStack/asg-propagatetags-false"
    }
  ],
  "VPCZoneIdentifier": [
    "subnet-xxxxxxxxxxxxx",
    "subnet-xxxxxxxxxx",
    "subnet-xxxxxxxxxxx"
  ]
}
```

---

CDK code

```
        vpc = ec2.Vpc.from_lookup(self, 'ExistingVpc', vpc_id=vpc_id)

        offical_image = ec2.AmazonLinuxImage(
            generation=ec2.AmazonLinuxGeneration.AMAZON_LINUX_2
        )

        asg_propagate_false = autoscaling.AutoScalingGroup(
            self,
            "asg-propagatetags-false",
            vpc=vpc,
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL
            ),
            machine_image=offical_image,
            vpc_subnets=ec2.SubnetSelection(subnet_type=SubnetType.PRIVATE_WITH_EGRESS),
        )
        Tags.of(asg_propagate_false).add("One", "This is a tag", apply_to_launched_instances=False)
        Tags.of(asg_propagate_false).add("Two", "This is also a tag", apply_to_launched_instances=False)

        asg_propagate_true = autoscaling.AutoScalingGroup(
            self,
            "asg-propagatetags-true",
            vpc=vpc,
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.SMALL
            ),
            machine_image=offical_image,
            vpc_subnets=ec2.SubnetSelection(subnet_type=SubnetType.PRIVATE_WITH_EGRESS),
        )
        Tags.of(asg_propagate_true).add("One", "This is a tag", apply_to_launched_instances=True)
        Tags.of(asg_propagate_true).add("Two", "This is also a tag", apply_to_launched_instances=True)
```

Relevant snippets of Cfn template...

```
  asgpropagatetagstrueASGF7A3DA81:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "1"
      MinSize: "1"
      LaunchConfigurationName:
        Ref: asgpropagatetagstrueLaunchConfigEF07B928
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: LabStack/asg-propagatetags-true
        - Key: One
          PropagateAtLaunch: true
          Value: This is a tag
        - Key: Two
          PropagateAtLaunch: true
          Value: This is also a tag
      VPCZoneIdentifier:
        - subnet-xxxxxxxxxx
        - subnet-xxxxxxxxxx
        - subnet-xxxxxxxxxx
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
```

```
  asgpropagatetagsfalseASG2AD73E46:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "1"
      MinSize: "1"
      LaunchConfigurationName:
        Ref: asgpropagatetagsfalseLaunchConfigDE437164
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: LabStack/asg-propagatetags-false
        - Key: One
          PropagateAtLaunch: false
          Value: This is a tag
        - Key: Two
          PropagateAtLaunch: false
          Value: This is also a tag
      VPCZoneIdentifier:
        - subnet-xxxxxxxxxxxxx
        - subnet-xxxxxxxxxxxx
        - subnet-xxxxxxxxxxxxxx
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
```
