### ISSUE TITLE
AWS::CloudFront::Distribution drift detection false positive on origin ordering

### ISSUE THREAD

**Issue by tstibbs** [aws-cloudformation/cloudformation-coverage-roadmap#1369]
### Name of the resource

AWS::CloudFront::Distribution

### Issue Description

If you have a cloudfront distribution with multiple origins which are a mixture of S3 and Custom origins, a drift detection false positive can occur if the S3 origin domain name is alphabetically before the Custom origin domain name (may not be precisely alphabetical but that's one way to reproduce). It appears that the 'Actual' config lists the origins in some order based on their domain names, whereas the 'Expected' config lists the origins in the order specified in the template. This results in the drift detector comparing origin1 with origin2, and comparing origin2 with origin1 etc.

### Expected Behavior

If the origins are equivalent between Actual and Expected, drift should not be reported.

### Observed Behavior

Drift is reported even though the set of origins is equivalent between Actual and Expected.

### Test Cases

Deploy the following template. Trigger drift detection. Observe that drift is reported.
```
Resources:
  distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        CacheBehaviors:
          - CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            PathPattern: subpath/*
            TargetOriginId: origin2
            ViewerProtocolPolicy: https-only
        Enabled: true
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: origin1
          ViewerProtocolPolicy: https-only
        Origins:
          - Id: origin1
            DomainName: aaaaaaaaaa.s3.eu-west-2.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: ''
          - Id: origin2
            DomainName: bbbbbbbbbb.execute-api.eu-west-2.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
```

### Other Details

If both origins are S3 origins then it's fine, regardless of the ordering of the DomainName elements.
