### ISSUE TITLE
Drift detection on AWS::EC2::Instance reports false-positive drift for IamInstanceProfile property

### ISSUE THREAD

**Issue by Sanchi-Halikar** [aws-cloudformation/cloudformation-coverage-roadmap#1383]
### Name of the resource

AWS::EC2::Instance

### Issue Description

AWS::EC2::Instance reports a false positive Drift for IamInstanceProfile property immediately after stack creation with no out of band change. 

### Expected Behavior

The resource should be in Sync since IAM instance profile role is not altered out of band. 

### Observed Behavior

- 'IamInstanceProfile' property expects IAM instance profile role 'NAME'.  Whereas during drift detection the value returned to cloudformation is IAM instance profile role 'Arn'.
- This causes an incorrect drift since the values are actually same, just the template as Name of role and ec2 returns an Arn during drift detection. 

### Test Cases

Steps to reproduce: 

1. Create IAM instance profile role using AWS::IAM::InstanceProfile resource
2. Reference it under AWS::EC2::Instance for 'IamInstanceProfile' property - (Ref returns name of instance profile)
3. Once stack is in CreateComplete, detect drift -  AWS::EC2::Instance will be marked as Drifted. 
```
MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile 
      ImageId: ami-xxx

  InstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      InstanceProfileName: TestInstaneProfile
      Roles: 
        - RoleName
```
