### ISSUE TITLE
Cloudformation stack update failed when updating with tags for the resource AWS::GuardDuty::Detector

### ISSUE THREAD

**Issue by gurukarn** [aws-cloudformation/cloudformation-coverage-roadmap#1386]
### Name of the resource

AWS::GuardDuty::Detector

### Resource Name

AWS::GuardDuty::Detector

### Issue Description

When trying to update tags for the GuardDuty resource using cloudformation template in the member account, it’s failed with an error. 

### Expected Behavior

Expected to support tags property for the resource Type: AWS::GuardDuty::Detector when updating it in the member account. 

### Observed Behavior

```
Cloudformation is updated failed for the resource by an error "The request is rejected because member accounts cannot manage specified resources or properties. (Service: AmazonGuardDuty; Status Code: 400; Error Code: BadRequestException; Request ID:xxxxxxxxxxx; Proxy: null)" 
```

### Test Cases

- Following the sample cloudformation code being used to test it. 

```
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      Tags:
        - Key:  Appname
          Value: Appvalue
```
