### ISSUE TITLE
AWS::Neptune::DBCluster ServerlessV2ScalingConfiguration property unsupported

### ISSUE THREAD

**Issue by john-br** [aws-cloudformation/cloudformation-coverage-roadmap#1389]
### Name of the resource

AWS::Neptune::DBCluster

### Description

Neptune introduced serverless instances and the documentation states CloudFormation supports serverless cluster creation:

> You can also [use the AWS CloudFormation template](https://docs.aws.amazon.com/neptune/latest/userguide/get-started-cfn-create.html) to create a serverless cluster. Similarly, you need to set DbInstanceType to serverless and then set a capacity range for the cluster.
https://docs.aws.amazon.com/neptune/latest/userguide/neptune-serverless-using.html

When attempting to to create a new `AWS::Neptune::DBCluster` while specifying a `ServerlessV2ScalingConfiguration` property the following error is encountered:

```
CREATE_FAILED: NeptuneDBCluster (AWS::Neptune::DBCluster)
Property validation failure: [Encountered unsupported properties in {/}: [ServerlessV2ScalingConfiguration]]
```

When the `ServerlessV2ScalingConfiguration` property is removed the following error is encountered:

```
CREATE_FAILED: NeptuneDBInstance (AWS::Neptune::DBInstance)
Set the Serverless v2 scaling configuration on the parent DB cluster before creating a Serverless v2 DB instance. (Service: AmazonNeptune; Status Code: 400; Error Code: InvalidDBClusterStateFault; Request ID: REDACTED; Proxy: null)
```

The CF used for the `AWS::Neptune::DBCluster` and `AWS::Neptune::DBInstance` resources is the following:

```
      NeptuneDBCluster:
        Type: AWS::Neptune::DBCluster
        Properties:
          DBSubnetGroupName:
            Ref: NeptuneDBSubnetGroup
          VpcSecurityGroupIds:
            - Fn::GetAtt:
                - NeptuneVPC
                - DefaultSecurityGroup
            - Ref: NeptuneSG
          DBClusterParameterGroupName:
            Ref: NeptuneDBClusterParameterGroup
          Port: 8182
          StorageEncrypted: true
          ServerlessV2ScalingConfiguration:
            MinCapacity: 6
            MaxCapacity: 32
        DependsOn:
          - NeptuneDBSubnetGroup
          - NeptuneDBClusterParameterGroup

      NeptuneDBInstance:
        Type: AWS::Neptune::DBInstance
        Properties:
          DBClusterIdentifier:
            Ref: NeptuneDBCluster
          DBInstanceClass: db.serverless
          DBParameterGroupName:
            Ref: NeptuneDBParameterGroup
        DependsOn:
          - NeptuneDBCluster
          - NeptuneDBParameterGroup
```
