### ISSUE TITLE
Unable to add SageMaker Studio KernelGatewayApp LifeCycleConfig

### ISSUE THREAD

**Issue by manshahe** [aws-cloudformation/cloudformation-coverage-roadmap#1392]
### Name of the resource

AWS::SageMaker::Domain

### Issue Description

I want to add a LifeCycleConfig to the SageMaker Studio Domain KernelGatewayApp, however the CFN fails.

The ARN pattern for a LifeCycleConfig is documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-domain-resourcespec.html#cfn-sagemaker-domain-resourcespec-lifecycleconfigarn 

Here is the code Snippet:

```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  StudioDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      VpcId: "vpc-xxx"
      SubnetIds: ["subnet-xxx"]
      DomainName: "MyDomainName"
      AuthMode: SSO
      DefaultUserSettings:
        ExecutionRole: "arn:aws:iam::xxx:role/AmazonSageMaker-ExecutionRole-20210903T143299"
        KernelGatewayAppSettings:
          DefaultResourceSpec:
            LifecycleConfigArn: "arn:aws:sagemaker:eu-central-1:xxx:studio-lifecycle-config/test-config"
```

### Expected Behavior

The Studio Domain with a LifeCycleConfig added to the KernelGatewayApp

### Observed Behavior

CloudFormation errors out with the message:

```
Properties validation failed for resource StudioDomain with message: 

#/DefaultUserSettings/KernelGatewayAppSettings/DefaultResourceSpec/LifecycleConfigArn: failed validation constraint for keyword [pattern]
```

### Test Cases

ARN for LifeCycleConfig: `arn:aws:sagemaker:eu-central-1:xxx:studio-lifecycle-config/test-config`
Follows the pattern : `arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:studio-lifecycle-config/.*`
