### ISSUE TITLE
 AWS::RDS::DBCluster - DbiResourceId accessible via Fn::GetAtt #1390 

### ISSUE THREAD

**Issue by perrin4869** [aws-cloudformation/cloudformation-coverage-roadmap#1413]
### Name of the resource

AWS::RDS::DBCluster

### Name of the resource

AWS::RDS::DBProxy

### Description

This is related to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/105 and to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1390
`AWS::RDS::DBCluster` resources have a `ResourceId` similar to `AWS::RDS::DBInstance`, which is used inside `arns`.
The motivation is exactly the same as in https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/105

Specifically:

```yaml
"DbCluster": {
  "Type": "AWS::RDS::DBCluster",
   "Properties": { }
},
"DBUserPolicy": {
  "Type": "AWS::IAM::ManagedPolicy",
  "Properties": {
      "Description": "blah blah not relevant",
      "PolicyDocument": {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": [  "rds-db:connect" ],
            "Effect": "Allow",
            "Resource": [
              { "Fn::Sub": "arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:cluster-n0q2srwsyoc69jd0uk/db_user_name" }
            ]
          }
        ]
      }
    }       
  }
}
```

I would like to change the Resource entry like this:

```
"Fn::Sub": [
"arn:aws:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${DbiResourceId}/db_user_name",
{ "DbiResourceId": { "Fn::GetAtt": [ "DbCluster", "DbiResourceId" ] } } ]
```
