### ISSUE TITLE
AWS::RDS::DBCluster ignores the EnableCloudwatchLogsExports property when creating a clone

### ISSUE THREAD

**Issue by verbitan** [aws-cloudformation/cloudformation-coverage-roadmap#1426]
### Name of the resource

AWS::RDS::DBCluster

### Issue Description

When cloning an Aurora cluster by setting the `SourceDBClusterIdentifier` and `RestoreType` properties the cluster is cloned correctly, however the `EnableCloudwatchLogsExports` property is ignored.

This is similar to the issues raised in https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/336 for both `DBSubnetGroupName` and `VpcSecurityGroupIds`.

### Expected Behavior

The cloned Aurora cluster should have log exports configured.

### Observed Behavior

The cloned Aurora cluster does not have log exports configured.

### Test Cases

Below is a snippet of the CloudFormation I am using in order to create the clone.

```
  Conditions:
    CreateClone: !Not [ !Equals [ !Ref DbToClone, "" ]]
  
  Resources:
    DBClusterLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName:
          Fn::Transform:
            - Name: String
              Parameters:
                InputString: !Sub /aws/rds/cluster/${AWS::StackName}/postgresql
                Operation: Lower
        RetentionInDays: 30

  DBCluster:
      Type: AWS::RDS::DBCluster
      DependsOn:
        - DBClusterLogGroup
      Properties:
        DBClusterIdentifier: !Sub ${AWS::StackName}
        DBClusterParameterGroupName: !Ref DBClusterParameterGroup
        DBSubnetGroupName: !Ref DBSubnetGroup
        EnableCloudwatchLogsExports:
          - postgresql
        EnableIAMDatabaseAuthentication: true
        Engine: aurora-postgresql
        EngineVersion: '12.11'
        MasterUsername:
          !Sub "{{resolve:secretsmanager:${DBPassword}::username}}"
        MasterUserPassword:
          !Sub "{{resolve:secretsmanager:${DBPassword}::password}}"
        PreferredBackupWindow: !Ref DatabaseBackupWindow
        PreferredMaintenanceWindow: !Ref DatabaseMaintenanceWindow
        RestoreType:
          Fn::If:
            - CreateClone
            - copy-on-write
            - !Ref AWS::NoValue
        StorageEncrypted: true
        SourceDBClusterIdentifier:
          Fn::If:
            - CreateClone
            - !Ref DbToClone
            - !Ref AWS::NoValue
        UseLatestRestorableTime:
          Fn::If:
            - CreateClone
            - true
            - !Ref AWS::NoValue
        VpcSecurityGroupIds:
          - !Ref DatabaseSecurityGroup
```
