### ISSUE TITLE
Removing AWS::CodeBuild::Project Properties::Triggers from CloudFormation doesn't remove triggers

### ISSUE THREAD

**Issue by csydvs** [aws-cloudformation/cloudformation-coverage-roadmap#1444]
### Name of the resource

AWS::CodeBuild::Project

### Issue Description

If I create a new AWS::CodeBuild::Project without setting the Properties::Triggers, it will appropriately not create anything under the CodeBuild job > Build Details > Primary source webhook events. Also, if I create a job with those Triggers, they will get appropriately created in that location. However, if I create a Cloudformation template with triggers, and then later redeploy it to remove the triggers, they will not be removed.

### Expected Behavior

The default behavior here should be that if the triggers are removed from the template, they are removed from the resource as well. However, because there is no default specified, these properties seem to default to "whatever they were last" instead of the sensible default of no values.

### Observed Behavior

The observed behavior is that if I delete the Triggers property from the Cloudformation template, no action is taken on the triggers themselves to delete them under CodeBuild job > Build Details > Primary source webhook events. 

### Test Cases

I was creating my triggers like so, and observing that builds were running on any branches prefaced with `feature/` or `bugfix/`:
```
      Triggers:
        BuildType: BUILD
        FilterGroups:
          - - Pattern: PUSH
              Type: EVENT
            - Pattern: ^refs/heads/feature/*
              Type: HEAD_REF
          - - Pattern: PUSH
              Type: EVENT
            - Pattern: ^refs/heads/bugfix/*
              Type: HEAD_REF
        Webhook: true
```
However, deleting the entire block will not delete the triggers, instead, you have to specifically set:
```
      Triggers:
        Webhook: false
```

### Other Details

As a side note, the documentation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-triggers) states that these triggers are only supported for Github, but this is also supported for Bitbucket.
