### ISSUE TITLE
AWS::CloudFormation::Stack does not update NotificationARNs property

### ISSUE THREAD

**Issue by JeremieRodon** [aws-cloudformation/cloudformation-coverage-roadmap#1445]
### Name of the resource

AWS::CloudFormation::Stack

### Issue Description

After using AWS::CloudFormation::Stack to create a nested stack, if you later add the NotificationARNs property, it is ignored.
New Nested stacks will have the notification enabled, but existing one are not updated.

### Expected Behavior

When adding NotificationARNs with a topic ARN, the existing Nested Stack should be updated with a notification configuration.

### Observed Behavior

The existing Nested Stack are not updated effectively. Only newly created ones have the notification.

### Test Cases

1. Create a bucket S3 with a dummy template that will serve as a nested stack:
```
AWSTemplateFormatVersion: 2010-09-09
Description: Dummy template
Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle
```
3. Create a parent CF template with a Nested Stack:
```
AWSTemplateFormatVersion: 2010-09-09
Description: Parent dummy template
Resources:
  NestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1f3e030iyelxl-eu-west-1.s3.eu-west-1.amazonaws.com/dummy.yml
```
4. Deploy it
5. Update the NestedStack resource to have a notification:
```
AWSTemplateFormatVersion: 2010-09-09
Description: Dummy template
Resources:
  NestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-templates-1f3e030iyelxl-eu-west-1.s3.eu-west-1.amazonaws.com/dummy.yml
      NotificationARNs:
        - arn:aws:sns:eu-west-1:123456789012:topic-example
```
6. Update the parent stack
7. The update is seen by CF, the events shows that an update is performed on the nested stack (both before and after the cleanup, which is fishy). In the end, the nested stack still does not have the notification

If you deploy a new stack from the same template, the Nested Stack will have the notification.
NB: It seems that it does not work either if the Nested Stack was created with a notification and the NotificationARNs property is removed later.
