### ISSUE TITLE
(AWS::Events::Rule) False-positive drift on 'EnableECSManagedTags' for EcsParameters

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1446]
### Name of the resource

AWS::Events::Rule

### Issue Description

Defining the [EnableECSManagedTags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html#cfn-events-rule-ecsparameters-enableecsmanagedtags) property of an [AWS::Events::Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html) results in false-positive drift.

### Expected Behavior

Defining EnableECSManagedTags should not result in drift when no out-of-band changes have been made.

### Observed Behavior

EnableECSManagedTags is reported as drifted, regardless of value, despite no out-of-band changes.

### Test Cases

**DRIFTED**

Expected: false
Actual: -

Targets.0.EcsParameters.EnableECSManagedTags

```
  ruleF2C1DCDC:
    Type: AWS::Events::Rule
    Properties:
      EventBusName:
        Ref: TheMagicSchoolBus31FEFE07
      EventPattern:
        source:
          - aws.ec2
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - FargateCPCluster
              - Arn
          EcsParameters:
            EnableECSManagedTags: false
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::GetAtt:
                      - TaskDefSecurityGroupD50E7CF0
                      - GroupId
                Subnets:
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet1Subnet8BCA10E01F79A1B7
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet2SubnetCFCDAA7AB22CF85D
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet3Subnet3EDCD457113A215F
            TaskCount: 1
            TaskDefinitionArn:
              Ref: TaskDef54694570
          Id: Target0
          Input: '{}'
          RoleArn:
            Fn::GetAtt:
              - TaskDefEventsRoleFB3B67B8
              - Arn
```

---

**DRIFTED**

Expected: false
Actual: -

Targets.0.EcsParameters.EnableECSManagedTags
```

  ruleF2C1DCDC:
    Type: AWS::Events::Rule
    Properties:
      EventBusName:
        Ref: TheMagicSchoolBus31FEFE07
      EventPattern:
        source:
          - aws.ec2
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - FargateCPCluster
              - Arn
          EcsParameters:
            EnableECSManagedTags: false
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp: DISABLED
                SecurityGroups:
                  - Fn::GetAtt:
                      - TaskDefSecurityGroupD50E7CF0
                      - GroupId
                Subnets:
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet1Subnet8BCA10E01F79A1B7
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet2SubnetCFCDAA7AB22CF85D
                  - Fn::ImportValue: NetworkStack:ExportsOutputRefVPCPrivateSubnet3Subnet3EDCD457113A215F
            TaskCount: 1
            TaskDefinitionArn:
              Ref: TaskDef54694570
          Id: Target0
          Input: '{}'
          RoleArn:
            Fn::GetAtt:
              - TaskDefEventsRoleFB3B67B8
              - Arn
```
