### ISSUE TITLE
Incorrect drift for `StopTimeout` in `ContainerDefinition`

### ISSUE THREAD

**Issue by krystof-k** [aws-cloudformation/cloudformation-coverage-roadmap#1455]
### Name of the resource

AWS::ECS::TaskDefinition

### Issue Description

CloudFormation reports incorrect drift for [`StopTimeout` attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinition.html#cfn-ecs-taskdefinition-containerdefinition-stoptimeout) in `ContainerDefinition`.

When set, it is reported as unset in the drift, although when I inspect the `TaskDefinition` JSON, the attribute is set.

### Expected Behavior

The attribute won't be reported as removed if set.

### Observed Behavior

The attribute is reported as removed although it is set and visible in the `TaskDefinition` JSON.

### Test Cases

Create a `ContainerDefinition` with `StopTimeout` and then run a drift detection.

**Comment by ecsoctocat** [comment]
Hi,

Thanks for raising the issue. To help me get some more context would you mind providing the cloud formation stack ID? 

When you view the task definition through the console or through ECS APIs are you able to view the StopTimeout property? Would appreciate if you could provide the arn for the task definition as well.

**Comment by krystof-k** [comment]
Well, this is weird, now it started to display like this:

![image](https://user-images.githubusercontent.com/11633481/209107092-877a90bc-3c30-4cf6-a36a-b19b612742e8.png)

And yes, I can see the `StopTimout` in the task definition JSON in AWS console.

**Comment by ecsoctocat** [comment]
Thanks for confirming, can you please provide the stack id?

**Comment by rgoltz** [comment]
We ran into the same issue. Once having a stack containing a `AWS::ECS::TaskDefinition` with a `ContainerDefinition` setup which set the `StopTimeout` in eu-central-1 region we see the drift false-positive:

![stopTimeOutCOSMOS](https://user-images.githubusercontent.com/16392819/217606014-6a8e961e-228f-4aad-bed1-7f9af4344150.PNG)

@ecsoctocat 
* Yes, stopTimeout is working fine and shown in Console.
* You can find a ARN of a affected stack via AWS Support Case 11949650231 (I'm not able to share a ARN here).

Below you find a simplified example a CFN Template. Please get in touch with me via case 11949650231 if you like to get the full CFN template and/or the TaskDefintion JSON.
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - stopTimeout issue - case 11949650231

Resources:
  SampleServiceabnPrometheusTaskDefinitionMIG364535A7:
    Type: AWS::SampleService::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Cpu: 0
        Essential: true
        HealthCheck:
          <someHealthCheckCmds>
        Image:
          <someImage>
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: "/github/SampleService-LogGroup"
            awslogs-stream-prefix: SampleService-mig-github
            awslogs-region: eu-central-1
            mode: non-blocking
        Memory: 512
        Name: github
        ReadonlyRootFilesystem: true
        StopTimeout: 110
      Cpu: '1024'
      ExecutionRoleArn:
        <someArn>
      Family: PrometheusTaskDefinitionMIG
      NetworkMode: awsvpc
      RequiresCompatibilities:
      - EC2
      Tags:
      - Key: ReferenceID
        Value: 11949650231
      TaskRoleArn:
        <someArn>
```
