### ISSUE TITLE
AWS::Serverless::Api Drift detection BinaryMediaTypes character "/" converted to "~1"

### ISSUE THREAD

**Issue by BourgoisMickael** [aws-cloudformation/cloudformation-coverage-roadmap#1457]
### Name of the resource

AWS::ApiGateway::RestApi

### Resource Name

AWS::Serverless::Api

### Issue Description

In `BinaryMediaTypes` a drift detection is triggered because it converts the `/` character into `~1`

```yaml
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      BinaryMediaTypes:
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```
![Screenshot 2022-12-19 at 15 53 15](https://user-images.githubusercontent.com/35171168/208453478-b0b14a6b-4192-4e77-a055-8322aac47a4a.png)

### Expected Behavior

Current value should have `/` instead of `~1` and it should not detect any drift

### Observed Behavior

`/` is converted to `~1`

### Test Cases

Create a RestApi with a `BinaryMediaTypes` containing a `/`
