### ISSUE TITLE
AWS::SecretsManager::Secret silently fails Replica Secret when invalid KMS Key specified

### ISSUE THREAD

**Issue by ZalmnS** [aws-cloudformation/cloudformation-coverage-roadmap#1459]
### Name of the resource

AWS::SecretsManager::Secret

### Issue Description

When creating an AWS::SecretManager::Secret resource and utilizes the ReplicaRegion property , you can encounter an issue where the Secret fails to replicate in a given region if the ReplicaRegion property is provided with an Invalid KMS Key ID in the targeted Region. The Resource Handler for the AWS::SecretManager::Secret Resource still sends a Create or Update Complete message to the CFN Stack rather than a failure for the replicated Key.

If no KMS Key is specified within the ReplicaRegion property, the Secret is created but the KMS Key that is utilized is the "aws/secretsmanager" default key.

### Expected Behavior

The expected behavior is that the Creation of the Secret would fail due to an invalid KMS Key ID being specified in the target region

### Observed Behavior

Replication Template:

```

Resources:
  SecretReplication:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ReplicationKeyTest01
      Description: test
      SecretString: 'TestString'
      ReplicaRegions:
        - Region: !Ref ReplicaRegion
          KmsKeyId: !Ref KMSKey
Parameters:
  KMSKey:
    Type: String
  ReplicaRegion:
    Type: String
    Default: 'us-west-2'
    AllowedValues:
    - none
    - us-east-1
    - us-west-2
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1


```
Steps to Replicate:

1. Deploy the above Template in any Region, for the KMSKeyId, you may specify a nonexistent key or leave the parameter blank.

   Specify a Target Region as well or leave as default to Us-west-2 

2. The deployment should be successful. The Stack moves to Create_Complete

Review the Region specified within the ReplicaRegion parameter within it's Secretes Manager service. The Secret should not exist, as the KMS Key ID specified does not exist

If you were to specify a KMS Key ID that did exist in the Target Region, the Secret would successfully replicate.

The CloudTrail logs in the specified target region do not show any create calls for the secret that failed to create.

This effectively leaves you with no visibility to the failure if an invalid KMS Key ID is used for a particular target region as the CreateSecret call to make the Secret Resource is successful.

Another interesting note is that if you were to create a Secret within the Web Console, you're forced into using a list of KMS Key ID's that are available within a given target region, effectively preventing an invalid KMS Key ID being specified 

### Test Cases

If I were to want to replicate a specific secret throughout multiple regions and my KMS Key that I have also replicated throughout multiple regions isn't available in some of the targeted regions, I would have no way of knowing that the secrets failed to create until I attempt to look for the secret
