### ISSUE TITLE
(AWS::ElasticLoadBalancingV2::LoadBalancer) False-positive drift for `SubnetMappings`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1464]
### Name of the resource

AWS::ElasticLoadBalancingV2::LoadBalancer

### Issue Description

When creating a `AWS::ElasticLoadBalancingV2::LoadBalancer` in `eu-central-1` using 

```
      SubnetMappings:
        - SubnetId: !ImportValue VPC1-AZ1Subnet1
        - SubnetId: !ImportValue VPC1-AZ2Subnet1
        - SubnetId: !ImportValue VPC1-AZ3Subnet1
```

it will cause a drift:

<html> <body> 

Property | Change | Expected value | Current value
-- | -- | -- | --
SubnetMappings.0.SubnetId | REMOVE | subnet-XXXXXXX | - | 
SubnetMappings.1.SubnetId | REMOVE | subnet-XXXXXXX | - |
SubnetMappings.2.SubnetId | REMOVE | subnet-XXXXXXX | - |

 </body> </html>

### Expected Behavior

Drift is recognizing `SubnetMappings`.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: "NLB"
      IpAddressType: ipv4
      Scheme: internal
      Type: network
      SubnetMappings:
        - SubnetId: !ImportValue VPC1-AZ1Subnet1
        - SubnetId: !ImportValue VPC1-AZ2Subnet1
        - SubnetId: !ImportValue VPC1-AZ3Subnet1
```

### Other Details

May be related to #458
