### ISSUE TITLE
(AWS::ECS::TaskDefinition) False-positive drift for `RuntimePlatform`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1467]
### Name of the resource

AWS::ECS::TaskDefinition

### Issue Description

When creating a `AWS::ECS::TaskDefinition` in `eu-central-1` using

```
      RuntimePlatform:
        CpuArchitecture: ARM64
```

it will cause a drift:

<html> <body> 

Property | Change | Expected value | Current value
-- | -- | -- | --
RuntimePlatform | REMOVE | 	{"CpuArchitecture":"ARM64"} | - | 

 </body> </html>

### Expected Behavior

Drift is recognizing `CpuArchitecture`.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: <Family>
      NetworkMode: awsvpc
      TaskRoleArn: <IAMRole>
      Cpu: 512
      RuntimePlatform:
        CpuArchitecture: ARM64
      Memory: 1.0GB
      ExecutionRoleArn: <IAMRole>
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: <Name>
          Image: <Image>
          Essential: true
          PortMappings:
            - ContainerPort: <Port>
              HostPort: <Port>
              Protocol: <Protocol>
          LogConfiguration:
            LogDriver: awslogs
            Options:
              "awslogs-region": !Ref AWS::Region
              "awslogs-group": <LogGroup>
              "awslogs-stream-prefix": <prefix>
```
