### ISSUE TITLE
(AWS::ECS::Cluster) False-positive drift for `CapacityProviders`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1469]
### Name of the resource

AWS::ECS::Cluster

### Issue Description

When creating a `AWS::ECS::Cluster` in `eu-central-1` using

```
      CapacityProviders:
        - FARGATE
```

it will cause a drift:

<html> <body> 

Property | Change | Expected value | Current value
-- | -- | -- | --
CapacityProviders | REMOVE | ["FARGATE"] | - | 

 </body> </html>

### Expected Behavior

Drift is recognizing `CapacityProviders`.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```  
ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "Name"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      CapacityProviders:
        - FARGATE
```

**Comment by greg5123334** [comment]
Confirmed.

```
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
```

Expected:
```
{
  "CapacityProviders": [
    "FARGATE"
  ]
}
```

Actual:
```
{}
```
