### ISSUE TITLE
(AWS::AutoScaling::AutoScalingGroup) False-positive drift for `LaunchTemplate.Version` when using `aws autoscaling start-instance-refresh`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1470]
### Name of the resource

AWS::AutoScaling::AutoScalingGroup

### Issue Description

When creating a `AWS::AutoScaling::AutoScalingGroup` in `eu-central-1` using

```
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
```

it will cause a drift:

<html> <body> 

Property | Change | Expected value | Current value
-- | -- | -- | --
LaunchTemplate.Version | NOT_EQUAL | 8 | $Latest | 

 </body> </html>

### Expected Behavior

Drift is recognizing `LaunchTemplate.Version`.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "Name"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier:
        - !ImportValue 'VPC1-AZ1Subnet1'
        - !ImportValue 'VPC1-AZ2Subnet1'
        - !ImportValue 'VPC1-AZ3Subnet1'
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
      MinSize: '0'
      MaxSize: '1'
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 60
```
