### ISSUE TITLE
Support for provisioning AWS Batch resources in me-central-1(UAE) region via CFN 

### ISSUE THREAD

**Issue by ayrawat17** [aws-cloudformation/cloudformation-coverage-roadmap#1480]
### Resource Name

Unable to provision any AWS Batch resources in me-central-1(UAE) region via CFN .
Currently AWS Batch service is supported in the me-central-1 region.

Could confirm in the resource specification doc of the me-central-1 region that AWS Batch resources are not supported :
++++++++++++++++++++
https://cfn-resource-specifications-me-central-1-prod.s3.me-central-1.amazonaws.com/latest/CloudFormationResourceSpecification.json 
++++++++++++++++++++

### Details

Deploying Stack in me-central-1 region using below stack template results in "Template format error: Unrecognized resource types: [AWS::Batch::JobDefinition] error":-

```
AWSTemplateFormatVersion: 2010-09-09

Resources: 

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: nvidia-smi
      ContainerProperties:
        MountPoints:
          - ReadOnly: false
            SourceVolume: nvidia
            ContainerPath: /usr/local/nvidia
        Volumes:
          - Host:
              SourcePath: /var/lib/nvidia-docker/volumes/nvidia_driver/latest
            Name: nvidia
        Command:
          - nvidia-smi
        Privileged: true
        JobRoleArn: String
        ReadonlyRootFilesystem: true
        ResourceRequirements:
          - Type: MEMORY
            Value: '2000'
          - Type: VCPU
            Value: '2'
        Image: nvidia/cuda
```
