### ISSUE TITLE
AWS::S3::Bucket Allow Return of HostedZoneId using GetAtt

### ISSUE THREAD

**Issue by colinbjohnson** [aws-cloudformation/cloudformation-coverage-roadmap#1484]
### Name of the resource

AWS::S3::Bucket

### Description

When creating an S3 Bucket to be used as a website endpoint creation of a "A Record with Alias Target" is not currently available. Example below:

```
WWWS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: bucket.cloudavail.com
    WebsiteConfiguration:
      ErrorDocument: index.html
      IndexDocument: index.html
```
And this should be able to be referenced in an A Record as follows:
```
WWWRecordSet:
  Type: AWS::Route53::RecordSet
  Properties:
    # https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
    AliasTarget:
      DNSName: s3-website-us-west-2.amazonaws.com
      HostedZoneId: !GetAtt WWWS3Bucket.HostedZoneId # or !GetAtt WWWS3Bucket.CanonicalHostedZoneId
    HostedZoneId: !Ref CloudAvailHostedZoneId
    Name: www.cloudavail.com
    Type: A
```
