### ISSUE TITLE
Fn::GetAtt not supported in AWS::Route53::HealthCheck property HealthCheckId

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#1489]
### Name of the resource

AWS::Route53::HealthCheck

### Issue Description

In the example template below, the Fn::GetAtt for AWS::Route53::HealthCheck property HealthCheckId is not supported.

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  myHealthCheck:
    Type: 'AWS::Route53::HealthCheck'
    Properties:
      HealthCheckConfig:
        Port: 80
        Type: HTTP
        ResourcePath: /example/index.html
        FullyQualifiedDomainName: [example.com](http://example.com/)
        RequestInterval: 30
        FailureThreshold: 3
      HealthCheckTags:
        - Key: SampleKey1
          Value: SampleValue1
        - Key: SampleKey2
          Value: SampleValue2
  myRecordSet:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      Name: [example.com](http://example.com/)
      HostedZoneId: Z03832112SJPMNXZJ61SG
      Type: 'CNAME'
      TTL: 900
      Type: A
      ResourceRecords:
      - 192.0.2.99
      HealthCheckId:
        'Fn::GetAtt':
          - myHealthCheck
          - HealthCheckId
```

While the customer can use Fn::Ref in the meanwhile, this should be fixed.

Additionally, both Fn::Ref and Fn::GetAtt for AWS::Route53::HealthCheck point to the HealthCheckId, making the GetAtt redundant.

### Expected Behavior

Fn::GetAtt should be supported in AWS::Route53::HealthCheck return value HealthCheckId.

### Observed Behavior

Fn::GetAtt should be supported in AWS::Route53::HealthCheck return value HealthCheckId.

### Test Cases

Use above template and GetAtt will fail.
