### ISSUE TITLE
AWS::Events::Rule resources don’t receive the aws:cloudformation built-in tags

### ISSUE THREAD

**Issue by bogdanb** [aws-cloudformation/cloudformation-coverage-roadmap#1501]
### Name of the resource

AWS::Events::Rule

### Issue Description

When you have an `AWS::Events::Rule` resource in your stack, it does not get assigned the built-in tags: `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id`.

### Expected Behavior

All stack resources should automatically receive the `aws:cloudformation:*` built-in tags.

### Observed Behavior

No tags are added automatically to `AWS::Events::Rule` resources created by a stack.

### Test Cases

```
AWSTemplateFormatVersion: '2010-09-09'
  Resources:
    MyRule:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source:
            - aws.ec2
          detail-type:
            - EC2 Instance State-change Notification
          detail:
            state:
              - stopping
      ScheduleExpression: rate(15 minutes)
      Targets:
        - Arn: !GetAtt 
            - MyCluster
            - Arn
          RoleArn: !GetAtt 
            - ECSTaskRole
            - Arn
          Id: Id345
          EcsParameters:
            TaskCount: 1
            TaskDefinitionArn: !Ref MyECSTask
```
