### ISSUE TITLE
AWS::SQS::Queue resources don’t receive the aws:cloudformation built-in tags

### ISSUE THREAD

**Issue by bogdanb** [aws-cloudformation/cloudformation-coverage-roadmap#1502]
### Name of the resource

AWS::SQS::Queue

### Issue Description

When you have an `AWS::SQS::Queue` resource in your stack, it does not get assigned the built-in tags: `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id`.

### Expected Behavior

All stack resources should automatically receive the `aws:cloudformation:*` built-in tags.

### Observed Behavior

No tags are added automatically to `AWS::SQS::Queue` resources created by a stack.

### Test Cases

```
AWSTemplateFormatVersion: '2010-09-09'
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub ${AWS::StackName}-queue
```
