### ISSUE TITLE
(AWS::RDS::DBInstance) False-positive drift on StorageThroughput property

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1503]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

False-positive drift when defining [StorageThroughput](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-storagethroughput) property.

### Expected Behavior

IN_SYNC

### Observed Behavior

Expected:
```
{
  "LicenseModel": "license-included",
  "StorageType": "gp3",
  "DBInstanceClass": "db.m5.xlarge",
  "MasterUsername": "****",
  "StorageThroughput": 125,
  "Iops": 3000,
  "PubliclyAccessible": false,
  "Engine": "sqlserver-se",
  "AllocatedStorage": 20
}
```

Actual:
```
{
  "LicenseModel": "license-included",
  "StorageType": "gp3",
  "DBInstanceClass": "db.m5.xlarge",
  "MasterUsername": "****",
  "Iops": 3000,
  "PubliclyAccessible": false,
  "Engine": "sqlserver-se",
  "AllocatedStorage": 20
}
```

### Test Cases

```
Parameters:
  Username:
    NoEcho: 'true'
    Description: Username for PostgreSQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    Default: "bevelvoerder"
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  Password:
    NoEcho: 'true'
    Description: Password for PostgreSQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    Default: "Passw0rd"
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  InstanceClass:
    Type: String
    Default: db.m5.xlarge
    Description: The compute and memory capacity of each DB instance in the Multi-AZ DB cluster, for example db.m6gd.xlarge. Not all DB instance classes are available in all AWS Regions, or for all database engines.
    AllowedValues:
      - db.m5.xlarge
  EngineVersion:
    Type: String
    Default: 115.00.4073.23.v1
    # AllowedValues:
    #   - 15.00.4073.23.v1
    Description: 'The engine version of the postgress database.'
  StorageThroughput:
    Type: Number
    Default: 125
    Description: "Specifies the storage throughput value for the DB instance. This setting applies only to the gp3 storage type."
  StorageType:
    Type: String
    Default: gp3
    AllowedValues:
      - gp2
      - gp3
      - io1
      - standard
  AllocatedStorage:
    Type: Number
    Default: 20
    Description: The amount of storage in gibibytes (GiB) to be initially allocated for the database instance.
  Iops:
    Type: Number
    Default: 3000
    Description: The number of I/O operations per second (IOPS) that the database provisions. The value must be equal to or greater than 1000.    
  LicenseModel:
    Type: String
    Default: license-included
    AllowedValues:
      - license-included

Resources:

  Instance:
    Type: 'AWS::RDS::DBInstance'
    DeletionPolicy: Delete
    Properties:
      Engine: sqlserver-se      
      AllowMajorVersionUpgrade: true
      AllocatedStorage: !Ref AllocatedStorage
      PubliclyAccessible: 'false'
      DBInstanceClass: !Ref InstanceClass
      StorageThroughput: !Ref StorageThroughput
      Iops: !Ref Iops
      StorageType: !Ref StorageType
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      LicenseModel: !Ref LicenseModel

Outputs:
  InstanceName:
    Value: !Ref Instance
    Description: "The DB instance name."
```

### Other Details

Not sure if related or relevant, but there has been another recent issue with the StorageThroughput property. So just mentioning it anyway

[ (AWS::RDS::DBInstance) not properly rolling back failed updates between gp2<->gp3 #1499 ](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1499)
