### ISSUE TITLE
(AWS::RDS::DBInstance) False-positive drift on OptionGroupName property

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1509]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

False-positive drift when defining OptionGroupName property.
Once you create a stack containing a `AWS::RDS::DBInstance` and the property `OptionGroupName` is set in CloudFormation template, the CloudFormation drift detection reporting such stack as drifted - Even the OptionGroupName is set correctly on the created RDS (details see "Observed Behavior").

### Expected Behavior

Stack is in state IN_SYNC, since template and resource have the correct setting.

### Observed Behavior

If you set `OptionGroupName` in your CFN template, your stack / this resource is in state DRIFTED after running CFN Drift detection:

![OptionGroupName](https://user-images.githubusercontent.com/16392819/217491412-0a77c6fa-c529-4f0a-bc73-47496997bd4d.PNG)

### Test Cases

** Create new Stack having an using following example (please mind to adjust the properties fitting your account) in eu-central-1 region

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - RDS issues - case 11940178081

MicrosoftSqlRdsInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '250'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 90
      CopyTagsToSnapshot: true
      DBInstanceClass: db.m5.large
      DBInstanceIdentifier: someId-iat-rds
      DBParameterGroupName:
        Ref: rdsparametergroupiat
      DBSubnetGroupName:
        Ref: MicrosoftRdsInstanceSubnetGroup
      DeleteAutomatedBackups: false
      DeletionProtection: true
      EnablePerformanceInsights: true
      Engine: sqlserver-se
      EngineVersion: 15.00.4073.23.v1
      KmsKeyId:
        Fn::ImportValue: rds-key-iat
      LicenseModel: license-included
      MasterUsername: "{{resolve:secretsmanager:arn:XXX}}"
      MasterUserPassword: "{{resolve:secretsmanager:arn:XXX}}"
      MultiAZ: false
      OptionGroupName:
        Ref: rdsoptiongroupiat
      PerformanceInsightsKMSKeyId:
        Fn::ImportValue: rds-key-iat
      PerformanceInsightsRetentionPeriod: 7
      PreferredBackupWindow: 23:00-01:00
      PreferredMaintenanceWindow: sat:01:30-sat:03:00
      PubliclyAccessible: false
      StorageEncrypted: true
      StorageType: gp2
      Tags:
      - Key: ReferenceID
        Value: 11940178081
      Timezone: W. Europe Standard Time
      VPCSecurityGroups:
      - Fn::GetAtt:
        - SameTeam
        - GroupId
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
```

** Go to CFN Console and run CFN Drift detection via: (in Console using "Stack actions" => "Detect drift". After you triggered this process, please wait for ca. 1 min and check again the Drift status: Stack went in state DRIFTED. Check the Drift-Details - You will the Drift for OptionGroupName property.

** After stack is created, please check your RDS resource in Console for OptionGroupName setting. It's correctly set, hence it's a false-positive drift on OptionGroupName property
