### ISSUE TITLE
AWS::KMS::ReplicaKey Does not apply Stack Level Default tags

### ISSUE THREAD

**Issue by ZalmnS** [aws-cloudformation/cloudformation-coverage-roadmap#1528]
### Name of the resource

AWS::KMS::ReplicaKey

### Resource Name

AWS::KMS::ReplicaKey

### Issue Description

Within the Replica Key Resource, you are able to define the Tags for the Replica key Resource at the Stack level as well at the Resource Properties level.

However, despite support tagging between the Stack Level tags and the Resource Properties tags, the AWS::KMS::ReplicaKey Resource lacks the default Stack level tags that are applied to Resources that support tagging as elaborated in the following document:

Resource tag
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

I was able to also replicate the same issue as elaborated in the following Github issue where another user had ran into the same problem with the AWS::KMS::Key Resource where the default Stack level tags are not being applied to the Resource:

https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1522

### Expected Behavior

The Expected behavior is that because the AWS::KMS::ReplicaKey resource supports both Stack Level Tags and Resource Properties Tags, it would be reasonable to assume that the Resource would also have the default stack level tags

### Observed Behavior

Default Stack Level tags are not applying to the AWS::KMS::ReplicaKey resource thus breaking visibility on whether or not the ReplicaKey Resource is generated via CloudFormation

### Test Cases

````


Parameters:
  ReplicaKeyArn:
    Type: String
    Description: This is R E Q U I R E D

Resources:
  myReplicaKey:
    Type: 'AWS::KMS::ReplicaKey'
    Properties:
      PrimaryKeyArn: !Ref ReplicaKeyArn
      Tags:
        - Key: "Stack Name"
          Value: !Ref AWS::StackName
      Description: Example replica key
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:role/role'
            Action:
              - 'kms:Create*'
              - 'kms:Delete*'
              - 'kms:Disable*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:Get*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Revoke*'
              - 'kms:UpdateAlias'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:role/role'
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey' 
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'
````
