### ISSUE TITLE
(AWS::RDS::DBInstance) False-positive drift on DBName property since Oracle RDS DB Name always convert to uppercase

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1530]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

This issue is **only related** (as far we we know) to **database engine Oracle**!

If your have a CloudFormatiom template where you have created an Oracle `AWS::RDS::DBInstance` resource with "DBName: `myoradb`" . However, the "DB Name" is "`MYORADB`" as you see in the RDS console. After checking with the RDS team, they confirmed that the "DB Name" for Oracle is always in uppercase.

Due to this circumstances, CloudFormation Drift Detection reports a drift for `DBName` property, even this "engine-specific" behavior (here DBEngineName = oracle-se2) is always in place.

### Expected Behavior

Stack is in state IN_SYNC also for Oracle RDS to support this boundary for a Oracle database engine.

### Observed Behavior

Please see details under "Issue Description" and "Test Case".

In a nutshell: 
* Value for DBName in CFN template (YAML/JSON) is defined in lowercase. 
* Value for Oracle DBName always converts to uppercase. 
* Result: Drift False-Postive for DBName .  

### Test Cases

** Create new Stack having an using following example (please mind to adjust the properties fitting your account and set or define futher Parameters/Properties) in eu-central-1 region

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: CFN Drift detection - Oracle RDS issue for DB Name - case 11948253981

Parameters:
  DBEngineName:
    Description: Define the engine name of database
    Type: String
    Default: 'oracle-se2'
  DBInstanceEngineVersion:
    Description: Define the Instance Engine Version of database
    Type: String
    Default: 19.0.0.0.ru-2021-10.rur-2021-10.r1
  DBAllowMajorVersionUpgrade:
    Description: Define the Major Version Upgrade of database
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DBAutoMinorVersionUpgrade:
    Description: Define the Miner Version Upgrade of database
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
  DBName:
    Description: A DB-Name for the RDS. IN CASE OF RESTORE, LEAVE IT AS IS, SO SID STAYS THE SAME. MaxLength 8 digits. Use lower Case!
    Type: String
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: "([a-z]{1}[a-z0-9]*)"
    Default: myoradb
  DBInstanceIdentifier:
    Type: String
    Description: A name for the DB instance. Its used for DB instance id, DB identifier and the Endpoint. IN CASE OF RESTORE, CHANGE THE NAME HERE AND SET DNS ONTO THE NEW ENDPOINT
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: "([a-z]{1}[a-z0-9]*)"
    Default: myoradb
# skip here some Parameters since they are not relevant

Resources:
  DBINST:
    Type: AWS::RDS::DBInstance
    Properties:
      # !Ref should be replaced by your local testing setup
      DeleteAutomatedBackups: False
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      DBParameterGroupName:
        Fn::ImportValue: !Sub "${Environment}-DBParameterGroupSE2-19"
      OptionGroupName:
        Fn::ImportValue: !Sub "${Environment}-DBOptionGroupSE2-19"
      MultiAZ: !Ref MultiAZ
      AvailabilityZone: !If [IsMultiAZTRUE, !Ref "AWS::NoValue", !FindInMap [Map, MapAZ, !Ref DBInstanceAvailabilityZone]]
      AllocatedStorage: !Ref DBInstanceStorageSize
      DBInstanceClass: !Ref DBInstanceType
      Engine: !Ref DBEngineName
      AllowMajorVersionUpgrade: !Ref DBAllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      CopyTagsToSnapshot: true
      EngineVersion: !Ref DBInstanceEngineVersion
      LicenseModel: !Ref DBLicenseModel
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPwd
      DBSubnetGroupName: !ImportValue VPC1-RDSSubnetGroup
      StorageType: !Ref DBInstanceStorageType
      CharacterSetName: !Ref DBInstanceCharacterSet
      BackupRetentionPeriod: !Ref RDSBackupRetentionPeriod
      StorageEncrypted: true
      DBSnapshotIdentifier: !If [ActivateDataImportTRUE, !Ref DBSnapshotIdentifier, !Ref "AWS::NoValue"]
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      KmsKeyId:
         Fn::ImportValue: !Sub "${Environment}-myoradb-KMSAlias"
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub "${Environment}-myoradb-SecGroup"
      Tags:
        - Key: ApplicationID
          Value: 11948253981
```

** Go to CFN Console and run CFN Drift detection via: (in Console using "Stack actions" => "Detect drift". After you triggered this process, please wait for ca. 1 min and check again the Drift status: Stack went in state DRIFTED. Check the Drift-Details - You will the Drift for DBName property.

** After stack is created, please check your RDS resource in AWS Console for DBName (called "DB Name").
*** You will see MYORADB as value for the Oracle RDS.

### Other Details

I'll list this drift false-positive under https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/issues/400
