### ISSUE TITLE
OpenSearch Auto-Tune & Off-peak Window

### ISSUE THREAD

**Issue by autarchprinceps** [aws-cloudformation/cloudformation-coverage-roadmap#1546]
### Name of the resource

AWS::OpenSearchService::Domain

### Description

OpenSearch create API has AutoTuneOptions & OffPeakWindowOptions that are missing from the CloudFormation implementation. This should be as easy as to forward options for these to create & modify domain calls, as far as I can see.

### Other Details

https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_CreateDomain.html#API_CreateDomain_RequestBody

**Comment by jamesrenaud** [comment]
In case anyone ends up here looking for the `OffPeakWindowOptions` - this is available now as of 2022-03-24

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opensearchservice-domain.html#cfn-opensearchservice-domain-offpeakwindowoptions

**Comment by jamesrenaud** [comment]
@paul-uz what's the error?

Within your `AWS::OpenSearchService::Domain` you should have something like ...

```json
"MyDomain":{
   "Type":"AWS::OpenSearchService::Domain",
   "Properties":{
      "OffPeakWindowOptions":{
          "Enabled":true,
          "OffPeakWindow":{
               "WindowStartTime":{
                    "Hours":0
                    "Minutes":30
               }
          }
      }
   }
}
```

**Comment by paul-uz** [comment]
Nvm, I had it inside `ClusterConfig` when it should have been outside.

But now I get 

> Resource handler returned message: "Invalid request provided: You must turn on Auto-Tune for domains with standby.

Full resource:

```
OpenSearch:
    Type: AWS::OpenSearchService::Domain
    UpdatePolicy:
      EnableVersionUpgrade: true
    Properties:
      ClusterConfig:
        DedicatedMasterCount: 3
        DedicatedMasterEnabled: true
        DedicatedMasterType: "m5.large.search"
        InstanceCount: 3
        InstanceType: "m5.large.search"
        MultiAZWithStandbyEnabled: true
        ZoneAwarenessConfig:
          AvailabilityZoneCount: 3
        ZoneAwarenessEnabled: true
      OffPeakWindowOptions:
        Enabled: true
      DomainName: streamline
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 20
      EngineVersion: "OpenSearch_2.3"
```
