### ISSUE TITLE
AWS::EC2::IPAM error adding tags with no other changes

### ISSUE THREAD

**Issue by bruecktech** [aws-cloudformation/cloudformation-coverage-roadmap#1550]
### Name of the resource

Other

### Resource Name

AWS::EC2::IPAM

### Issue Description

Updating tags on an `AWS::EC2::IPAM` resource with no other changes result in bad request error

### Expected Behavior

Tags should be added

### Observed Behavior

```
Resource handler returned message: "The request must contain a modification to the ipam. (Service: Ec2, Status Code: 400, Request ID: 5fbe502a-2992-4c9f-8daf-484a5bbcd7b1)" (RequestToken: b19a3fa4-0cd7-352c-b2dd-b01322ed2249, HandlerErrorCode: InvalidRequest)
```

### Test Cases

Deploy a stack that creates an `AWS::EC2::IPAM` resource, then update the stack adding tags.

Initial template
```
Resources:
  EC2IPAM2O856:
    Type: 'AWS::EC2::IPAM'
    Properties: {}
```

Update template

```
Resources:
  EC2IPAM2O856:
    Type: 'AWS::EC2::IPAM'
    Properties:
        Tags:
        - Key: foo
          Value: bar
```
