### ISSUE TITLE
AWS::Events::EventBusPolicy - [BUG] Resource Type AWS::Event::EventBusPolicy has a Condition property which causes internal failures in change sets

### ISSUE THREAD

**Issue by badaldavda** [aws-cloudformation/cloudformation-coverage-roadmap#156]
Summary
============
In CreateChangeSet, a "Condition" in a resource "Properties" is an invalid behavior currently and will cause an internal failure, looks like it is a long-running issue and been discovered.

Example Template:
------------------------
Resources:
SampleEventBusPolicy: 
Type: AWS::Events::EventBusPolicy
Properties: 
Action: "events:PutEvents"
Principal: "*"
StatementId: "DemoStatement2"
Condition: 
Type: "true"
Key: "aws:PrincipalOrgID"
Value: "o-1234567890"

There is already a bug reported in internal issues. It would really be the best if the same could be added in the roadmap so that its easy to track.

**Comment by lazharichir** [comment]
Still facing this (using CDK):

```
{
	"companyeventbuspolicy": {
		"Type": "AWS::Events::EventBusPolicy",
		"Properties": {
			"Action": "events:PutEvents",
			"Principal": "*",
			"StatementId": "company-event-bus-policy-statement",
			"Condition": {
				"Key": "aws:PrincipalOrgID",
				"Type": "StringEquals",
				"Value": "o-123456789"
			},
			"EventBusName": {
				"Ref": "companyeventbus9ABF23AA"
			}
		},
		"Metadata": {
			"aws:cdk:path": "company-events-stack/company-event-bus-policy"
		}
	}
}
```

**Comment by szotrj** [comment]
Just spent hours troubleshooting this with an open AWS Enterprise Support case.

My template snippet:
```yaml
Resources:
  rEventBusPolicy:
    Type: 'AWS::Events::EventBusPolicy'
    Properties:
      Action: 'events:PutEvents'
      Principal: '*'
      StatementId: Organization
      Condition:
        Type: StringEquals
        Key: 'aws:PrincipalOrgID'
        Value:
          Fn::FindInMap:
            - OrgMap
            - !Ref AWS::Partition
            - ORG
```

**Comment by ashwanijha04** [comment]
The problem here is with the CreateChangeSet API call. 

'**aws cloudformation deploy**' command creates a **changeset** before creating or updating the stack as mentioned in the doc[2].

_"Deploys the specified AWS CloudFormation template by creating and then executing a change set"_

The current workaround is to use the '**aws cloudformation create-stack**' CLI command **instead of** '**_aws cloudformation deploy_**' until this is fixed:

**`aws cloudformation create-stack --stack-name myBug --template-body file://bug_test.yaml`**


_[1] deploy
     https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html#deploy_

_[2] create-stack:
    https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html_

**Comment by dejonghe** [comment]
This is blocking my team as well. How has this gone almost a year with no AWS Acknowledgement?

**Comment by chmoora** [comment]
Dear CFN team, any updates on this? It's been almost a year. This currently blocks CDK issue below.

https://github.com/aws/aws-cdk/issues/1785

**Comment by nbrational** [comment]
I have tried to put together a workaround using CloudFormation custom resource which has parameter called 'TheCondition' instead of 'Condition' as the latter collides with CloudFormation intrinsic function. Change Set creation works fine:- https://github.com/nbrational/CFN_EventBusPolicy_Bug156

**Comment by ALutchko** [comment]
Almost three years :(

**Comment by nikp** [comment]
Thanks everyone for your patience. @badaldavda as you probably already discovered, there was a bug in your initial CFN yaml

```yaml
Condition:
  Type: "true"
  Key: "aws:PrincipalOrgID"
  Value: "o-1234567890"
```

should have been

```yaml
Condition:
  Type: "StringEquals"
  Key: "aws:PrincipalOrgID"
  Value: "o-1234567890"
```

Other folks including @lazharichir and @szotrj had the correct syntax, but ran into another issue that CFN team fixed in September 2020.

In our testing today we were unable to reproduce this issue. Is it still something that you're facing?
