### ISSUE TITLE
AWS::KMS::Key/AWS::KMS::ReplicaKey do not support default Stack Tags

### ISSUE THREAD

**Issue by ZalmnS** [aws-cloudformation/cloudformation-coverage-roadmap#1572]
### Name of the resource

AWS::KMS::ReplicaKey

### Resource name

AWS::KMS::ReplicaKey, AWS::KMS::Key

### Description

Both the AWS::KMS::ReplicaKey and the AWS::KMS::Key Resources both do not apply default Stack level tags, despite supporting tagging within the Resource itself.

These two Resources were brought up specifically in these two issues:

https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1522
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1528

Both of these Issues had been closed, despite the issue persisting as of testing today.

### Other Details

Example Templates:
Deploy this Stack in one Region:
```
Resources:
  EncryptionKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: TestKeyForTags
      EnableKeyRotation: true
      MultiRegion: true
      Enabled: true
      Tags:
        - Key: "Stack Name Not Default Tag"
          Value: !Ref AWS::StackName
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
            Action:
              - 'kms:*'
            Resource: '*'
Outputs:
  KeyID:
    Value: !GetAtt 
      - EncryptionKey
      - KeyId
  KeyArn:
    Value: !GetAtt EncryptionKey.Arn
```
Deploy this Stack in a Replica Region. please take note of the IAM Roles and replace with your own:

```
Parameters:
  ReplicaKeyArn:
    Type: String
    Description: This is R E Q U I R E D

Resources:
  myReplicaKey:
    Type: 'AWS::KMS::ReplicaKey'
    Properties:
      PrimaryKeyArn: !Ref ReplicaKeyArn
      Tags:
        - Key: "Stack Name"
          Value: !Ref AWS::StackName
      Description: Example replica key
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:role/role'
            Action:
              - 'kms:Create*'
              - 'kms:Delete*'
              - 'kms:Disable*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:Get*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Revoke*'
              - 'kms:UpdateAlias'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::1234567819:role/role'
            Action:
              - 'kms:DescribeKey'
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey' 
              - 'kms:GenerateDataKeyWithoutPlaintext'
            Resource: '*'

```

You will see on both Resources that aside from CloudFormation defined Tags, no other Tags are placed onto the Resources
