### ISSUE TITLE
AWS::EC2::EBSEncryptionByDefault

### ISSUE THREAD

**Issue by rdearm1** [aws-cloudformation/cloudformation-coverage-roadmap#158]
You can turn on ebs encryption by default in the console for each region via API or SDK but not via CF.

https://docs.amazonaws.cn/AWSEC2/latest/APIReference/API_EnableEbsEncryptionByDefault.html

**Comment by atheiman** [comment]
Until this is supported by CloudFormation natively, this can be done with a simple [Lambda-backed custom resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources-lambda.html):

```yaml
Resources:
  EbsEncryptionByDefault:
    Type: Custom::EbsEncryptionByDefault
    Properties:
      ServiceToken: !Sub '${EbsEncryptionByDefaultLambdaFunction.Arn}'

  EbsEncryptionByDefaultLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !Sub '${EbsEncryptionByDefaultLambdaExecutionRole.Arn}'
      Handler: index.handler
      Timeout: 20
      Runtime: python3.7
      Code:
        ZipFile: !Sub |
          import boto3
          import cfnresponse

          def handler(event, context):
              try:
                  ec2 = boto3.client("ec2", region_name="${AWS::Region}")
                  res = ec2.enable_ebs_encryption_by_default()
                  res.update(ec2.modify_ebs_default_kms_key_id(KmsKeyId="alias/aws/ebs"))
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, res)
              except Exception as e:
                  print("Error:", repr(e))
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Message": "Error"})

  EbsEncryptionByDefaultLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: ['sts:AssumeRole']
      ManagedPolicyArns: ['arn:aws-us-gov:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole']
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DisableEbsEncryptionByDefault
                  - ec2:EnableEbsEncryptionByDefault
                  - ec2:GetEbsDefaultKmsKeyId
                  - ec2:GetEbsEncryptionByDefault
                  - ec2:ModifyEbsDefaultKmsKeyId
                  - ec2:ResetEbsDefaultKmsKeyId
                Resource: '*'
```
