### ISSUE TITLE
Need AWS::SecretsManager::Secret attribute for secret name

### ISSUE THREAD

**Issue by garretwilson** [aws-cloudformation/cloudformation-coverage-roadmap#1584]
### Name of the resource

AWS::SecretsManager::Secret

### Description

[`AWS::SecretsManager::Secret`](AWS::SecretsManager::Secret) should provide a `Name` attribute that can be queried using `Fn::GetAtt`. Currently it only provides its ARN via `Ref`.

When specifying an [injected ECS secret as an environment variable](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-secret.html) in [`AWS::ECS::TaskDefinition > ContainerDefinitions > Secrets`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-secret.html), the [format of the secret](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html) is:

`arn:aws:secretsmanager:region:aws_account_id:secret:secret-name:json-key:version-stage:version-id`

Note that we need to refer to the `secret-name`. Suppose that the secret is defined thus:

```yaml
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "foo-${someVariable}-bar"
      …
```

If we do a `!Ref MySecret`, it gives us the secret ARN. But we need the secret name.

It is clunky to reproduce the entire secret name in the Secrets Manager reference, especially if the name was constructed using variable interpolation (to avoid clashes, as secrets are visible cross-stack):

```yaml
ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:foo-${someVariable}-bar:json-key::"
```

It would be much more convenient if we could query a `Name` attribute of the secret, like this:

```yaml
ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${MySecret.Name}:json-key::"
```

**Comment by garretwilson** [comment]
It turns out the situation is a little more complicated than it would first appear. We still need a `Name attribute for `AWS::SecretsManager::Secret`. However the documentation is ambiguous in several locations regarding the name itself.

It turns out there are actually two "names" for `AWS::SecretsManager::Secret`. There is the name you specify such as `my-secret`. Then there is a name AWS generates, ending with a dash and six characters, such as `my-secret-abcdef`. In fact the documentation for [`AWS::SecretsManager::Secret Name`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secret.html#cfn-secretsmanager-secret-name) talks about this.
> Do not end your secret name with a hyphen followed by six characters. If you do so, you risk confusion and unexpected results when searching for a secret by partial ARN. Secrets Manager automatically adds a hyphen and six random characters after the secret name at the end of the ARN.

Moreover it's not clear in which instances the documentation is referring to the "name I gave the secret" or the "name with extra stuff at the end". Note that there's no way in CloudFormation to know what that "stuff in the end is" without referring to the ARN (discussed below), so should we actually _need_ that name by itself, there's currently no way to get it because of the lack of a `Name` attribute.

Take [`AWS::IAM::Role Policies`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-policies) for example. The [ECS Using Secrets Manager](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html) documentation says that to refer to a secret you need to use the secret name in this form:

`arn:aws:secretsmanager:region:aws_account_id:secret:secret_name`

But that's not entirely correct. If you plug the secret name `my-secret` in there, it won't work:

```yaml
Resource:
  - !Sub "arn:aws:secretsmanager:${AWS::Region}:${ASC::AccountId}:secret_name"
```

Here you actually need the `my-secret-abcdef` form—which we don't know because we don't have a secret `Name` attribute to reference with `Fn::GetAtt`.

We're in luck though. It turns out that the entire string `arn:aws:secretsmanager:region:aws_account_id:secret:secret_name` is actually the ARN of the secret, so you can simply reference it using `!Ref`. And I admit that, going back, I see that the documentation mentions the secret ARN, although as written I don't think it's clear what the documentation is referring to.

```yaml
Resource:
  - !Ref MySecret
```

So we escaped that problem. Let's go back to the example I gave in the description of this ticket, injecting a secret into an ECS task container:

```yaml
ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:foo-${someVariable}-bar:json-key::"
```

Here again, if we look closely the first section is _the secret ARN_! And I again admit that the documentation does mention the secret ARN, but I don't think it's clear what it's talking, because it breaks the string down into its components. After I realized that the first portion of the string is the secret ARN, we can change this:

```yaml
ValueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:foo-${someVariable}-bar:json-key::"
```

to simply this:

```yaml
ValueFrom: !Sub "${MySecret}:json-key::"
```

Note here though that there is a difference: the former uses the `my-secret` form (the form used when defining the secret in CloudFormation), while the latter uses the `my-secret-abcdef` (with extra stuff AWS added) form. And interestingly … either form works!!

So for the moment I have not found any places where we actually need the secret `Name` by itself; the ARN will do. Still I think a `!GetAtt MySecret.Name` might be useful should we ever actually need access to the `my-secret-abcdef`. Perhaps more importantly, though, the documentation could be improved to indicate which form of the "secret name" it's referring to in each case, and be more explicit that in the `secret_name` appears in the syntax of some identifier that those identifiers really contain the secret ARN.

**Comment by craigbosco** [comment]
It seems that we need the `!GetAtt MySecret.Name` attribute for reference in CloudFormation templates for `AWS::Glue::Connection` resources. To create a JDBC connection, it seems that the SecretID is the Name and not the full ARN. [(REF)](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html)

Currently, I am trying to strip out the Secret Name from the ARN provided from !GetAtt using other intrinsic functions. 

That will look something like this: 
```
WarehouseConnection:
    Type: AWS::Glue::Connection
    Properties: 
      CatalogId: !Ref AWS::AccountId
      ConnectionInput: 
        ConnectionProperties:
          JDBC_ENFORCE_SSL: "true"
          JDBC_CONNECTION_URL: !Sub "jdbc:redshift://${WarehouseEndpoint}"
          # SECRET_ID: !Ref WarehouseSecret
          ## NOTE: The Glue::Connection resource expects a Secret Name as a string, not an ARN
          SECRET_ID: 
            Fn::Select:
              - "0"
              - Fn::Split:
                  - "-"
                  - Fn::Select:
                      - "6"
                      - Fn::Split:
                          - ":"
                          - !Ref WarehouseSecret
        ConnectionType: JDBC
```

**Comment by ap-hyperbole** [comment]
Had to use this to make it work but it's very clunky. 

```
OracleRDSConnection:
    Type: AWS::Glue::Connection
    Properties: 
      CatalogId: !Ref AWS::AccountId
      ConnectionInput: 
        ConnectionType: JDBC
        ConnectionProperties:
          JDBC_CONNECTION_URL: !Sub "jdbc:oracle:thin://@${RDSEndpoint}:${RDSPort}/ORCL"
          SECRET_ID:
            !Join
              - '-'
              - - Fn::Select:
                    - "0"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
                - Fn::Select:
                    - "1"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
                - Fn::Select:
                    - "2"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
                - Fn::Select:
                    - "3"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
                - Fn::Select:
                    - "4"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
                - Fn::Select:
                    - "5"
                    - Fn::Split:
                        - "-"
                        - Fn::Select:
                            - "6"
                            - Fn::Split:
                                - ":"
                                - !Ref SecretManagerArn
```

Suggestion from @craigbosco did not work as annoyingly the ARN structure of the secret has an additional suffix after the name 

`arn:aws:secretsmanager:<Region>:<AccountId>:secret:SecretName-6RandomCharacters`
