### ISSUE TITLE
Issues with deploying Cloud Formation Template for AWS::EC2::NetworkInterface and AWS::EC2:: NetworkInterfaceAttachment in GovCloud regions

### ISSUE THREAD

**Issue by gulgulni** [aws-cloudformation/cloudformation-coverage-roadmap#1585]
### Name of the resource

AWS::EC2::NetworkInterface

### Issue Description

While deploying a stack in the Gov Cloud region followiong error is thrown:
"Template is not valid: Template error: resource outboundInterface1 does not support attribute type Id in Fn::GetAtt"
The same template works when deployed to commercial regions.

Sample template:
AWSTemplateFormatVersion: 2010-09-09
Resources:
    myENI:
      Type: AWS::EC2::NetworkInterface
      Properties:
         Tags:
            - Key: stack
              Value: production
         Description: A nice description.
         SourceDestCheck: 'false'
         SubnetId: subnet-1234 #Replace this with the subnet the instance was launched

    outboundInterface1Attachment:
        Type: AWS::EC2::NetworkInterfaceAttachment
        Properties:
          DeleteOnTermination: true
          DeviceIndex: 2
          InstanceId: i-abcd # replace this with the instance id you just launched.
          NetworkInterfaceId: !GetAtt myENI.Id

### Expected Behavior

Given the template, it should successfully deploy in GovCloud regions

### Observed Behavior

1. launch an EC2 instance in any of the GovCloud region.
2. Then try to deploy the following template in CloudFormation:

AWSTemplateFormatVersion: 2010-09-09
Resources:
    myENI:
      Type: AWS::EC2::NetworkInterface
      Properties:
         Tags:
            - Key: stack
              Value: production
         Description: A nice description.
         SourceDestCheck: 'false'
         SubnetId: subnet-1234 #Replace this with the subnet the instance was launched

    outboundInterface1Attachment:
        Type: AWS::EC2::NetworkInterfaceAttachment
        Properties:
          DeleteOnTermination: true
          DeviceIndex: 2
          InstanceId: i-abcd # replace this with the instance id you just launched.
          NetworkInterfaceId: !GetAtt myENI.Id

You won't be able to deploy the stack since it will fail with a validation error:

Template is not valid: Template error: resource myENI does not support attribute type Id in Fn::GetAtt

### Test Cases

Given the template, it should successfully deploy in GovCloud regions

**Comment by jayid-07** [comment]
Just to add, the template above works fine in a commercial region i.e us-east-2

**Comment by SuzakuTheKnight** [comment]
Can confirm this is still an issue on the GovCloud partition. Looking forward to seeing this addressed.

**Comment by gulgulni** [comment]
Issue is now resolved with a fix in place. 
Following scenario was tested to validate the fix in `us-gov-west-1`

Stack created successfully using template:
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  myVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
  mySubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-gov-west-1a
  myENI:
    Type: 'AWS::EC2::NetworkInterface'
    Properties:
      Tags:
        - Key: stack
          Value: production
      Description: A nice description.
      SourceDestCheck: 'false'
      SubnetId: !Ref mySubnet
  myInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: us-gov-west-1a
      ImageId: ami-0155b6194e7bf0681
      InstanceType: c6in.32xlarge
      DisableApiTermination: true
  outboundInterface1Attachment:
    Type: 'AWS::EC2::NetworkInterfaceAttachment'
    Properties:
      DeleteOnTermination: true
      DeviceIndex: 2
      InstanceId: !Ref myInstance
      NetworkInterfaceId: !GetAtt myENI.Id
```
