### ISSUE TITLE
Need name attribute for AWS::ServiceDiscovery::PrivateDnsNamespace et. al.

### ISSUE THREAD

**Issue by garretwilson** [aws-cloudformation/cloudformation-coverage-roadmap#1591]
### Name of the resource

AWS::ServiceDiscovery::PrivateDnsNamespace

### Description

I can create a private, internal service discovery namespace like this:

```yaml
  DiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties: 
      Name: "example.internal"
      Vpc: !Ref VPC
```

But later if I want to use the name `example.internal`, how do I refer to it? The [`AWS::ServiceDiscovery::PrivateDnsNamespace`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-privatednsnamespace.html) type seems to have attributes for `Arn`, `HostedZoneId`, and `Id`, but not `Name`.

For example let's say I wanted to output the name of a `AWS::ServiceDiscovery::Service` for `my-service` in this namespace. I might want to do this:

```yaml
Outputs:
  ServiceDiscoveryHost:
    Description: The DNS resolvable host of the service.
    Value: !Sub "${ServiceDiscovery.Name}.${DiscoveryNamespace.}"
```

You can see that `AWS::ServiceDiscovery::Service` provides a `Name` attribute. But not `AWS::ServiceDiscovery::PrivateDnsNamespace`. Why not? Isn't the name of the namespace one of its most important components? How can I communicated to other services how to contact this service without copying and hard-coding some string?

[`AWS::ServiceDiscovery::PrivateDnsNamespace`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-privatednsnamespace.html), [`AWS::ServiceDiscovery::PublicDnsNamespace`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-publicdnsnamespace.html), and [`AWS::ServiceDiscovery::HttpNamespace`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-httpnamespace.html) all need to have their own respective `Name` attributes.
