### ISSUE TITLE
AWS::Glue::Table support for Iceberg TableType in the TableInput property

### ISSUE THREAD

**Issue by sfgarcia** [aws-cloudformation/cloudformation-coverage-roadmap#1595]
### Name of the resource

AWS::Glue::Table

### Scope of request

Iceberg format has been available in Athena for 1 year now, but Cloudformation still hasn't supported the creation of an Iceberg table (https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-athena-acid-transactions-powered-apache-iceberg/). To create an Iceberg table the only available option is to run a DDL query directly in Athena (https://docs.aws.amazon.com/athena/latest/ug/querying-iceberg-creating-tables.html) which is not very convenient in large production environments where all cloud infrastructure is mantained in Cloudformation.

I already chatted with AWS Support team and they confirmed it's not possible to create Iceberg tables in Cloudformation, because the CreateTable API doesn't support the Iceberg connector yet.

### Expected behaviour

It should be possible to use `Iceberg` as a TableType in the TableInput inside AWS::Glue::Table resource:

```yaml
  Description: String
  Name: String
  Owner: String
  Parameters: Json
  PartitionKeys: 
    - Column
  Retention: Integer
  StorageDescriptor: 
    StorageDescriptor
  TableType: String --> Iceberg
  TargetTable: 
    TableIdentifier
  ViewExpandedText: String
  ViewOriginalText: String
```
