### ISSUE TITLE
AWS::Glue::SecurityConfiguration results in internal error during deployment when excluding S3Encryptions 

### ISSUE THREAD

**Issue by ericpapaluca** [aws-cloudformation/cloudformation-coverage-roadmap#1604]
### Name of the resource

AWS::Glue::SecurityConfiguration

### Issue Description

When deploying a Glue Security Configuration with the following example template structure, an Internal Error is raised by CloudFormation:

```Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration:
        CloudWatchEncryption:
          CloudWatchEncryptionMode: SSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - GlueSecurityConfigKey02AC3622
              - Arn
        JobBookmarksEncryption:
          JobBookmarksEncryptionMode: CSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - GlueSecurityConfigKey02AC3622
              - Arn
```

However, adding

```
S3Encryptions:
          - KmsKeyArn:
              Fn::GetAtt:
                - GlueSecurityConfigKey02AC3622
                - Arn
            S3EncryptionMode: SSE-KMS
```

Allows it to be deployed successfully.

This is not in alignment with creating Security Configurations in the console, as you can create them with any of the 3 encryption types disabled.

### Expected Behavior

A security configuration is created with Cloudwatch Encryption and Job Bookmark Encryption Attributes

### Observed Behavior

Cloudformation returns an internal error immediately.

### Test Cases

1. Create a new Cloudformation Stack and KMS Key
2.  Attempt to deploy the following template:
```
Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration:
        CloudWatchEncryption:
          CloudWatchEncryptionMode: SSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - <yourKMSKey>
              - Arn
        JobBookmarksEncryption:
          JobBookmarksEncryptionMode: CSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - <yourKMSKey>
              - Arn
```
          
3. This will result in an internal error
4. Attempt to deploy the following template:
```
Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration:
        CloudWatchEncryption:
          CloudWatchEncryptionMode: SSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - <yourKMSKey>
              - Arn
        JobBookmarksEncryption:
          JobBookmarksEncryptionMode: CSE-KMS
          KmsKeyArn:
            Fn::GetAtt:
              - <yourKMSKey>
              - Arn
        S3Encryptions:
          - KmsKeyArn:
              Fn::GetAtt:
                - <yourKMSKey>
                - Arn
            S3EncryptionMode: SSE-KMS
```
5. This will result in successful deployment
6. Verify you can create a security configuration through the console with S3Encryption disabled.
