### ISSUE TITLE
Cannot create bucket with `AccessControl: LogDeliveryWrite`

### ISSUE THREAD

**Issue by BourgoisMickael** [aws-cloudformation/cloudformation-coverage-roadmap#1606]
### Name of the resource

AWS::S3::Bucket

### Issue Description

Cannot create bucket with `AccessControl: LogDeliveryWrite`

### Expected Behavior

Bucket is created without error

### Observed Behavior

`CREATE_FAILED`: Bucket cannot have ACLs set with ObjectOwnership's BucketOwnerEnforced setting (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketAclWithObjectOwnership; Request ID: ...)

### Test Cases

Use cloudformation template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
```

### Other Details

pls fix asap
