### ISSUE TITLE
Drift false positive for 'SnapshotIdentifier' property of AWS::Redshift::Cluster resource

### ISSUE THREAD

**Issue by rwmason** [aws-cloudformation/cloudformation-coverage-roadmap#1639]
### Name of the resource

AWS::Redshift::Cluster

### Issue Description

If using the `SnapshotIdentifier` property of the AWS::Redshift::Cluster resource to create a cluster form a snapshot, the stack will show as drifted with the drift details stating the `SnapshotIdentifier` has been removed

Link to resource property: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-snapshotidentifier

Checking the details of the [DescribeClusters](https://docs.aws.amazon.com/redshift/latest/APIReference/API_DescribeClusters.html) API action and the [Cluster](https://docs.aws.amazon.com/redshift/latest/APIReference/API_Cluster.html) object, it doesn't look like there is any property to include the snapshot ID of the cnapshot that was used to create the cluster which looks to be the reason CFN is reporting the drift

### Expected Behavior

The resource would not show as drifted when creating the cluster from a snapshot and making no out-of-bounds changes to the resource.

### Observed Behavior

The cluster _does_ show as drifted when creating from a snapshot and making no outside changes

### Test Cases

To replicate this:

1. You can create a Redshift Cluster using the below template:
```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MasterUserPassword:
    Type: String
    NoEcho: true
Resources:
  myCluster:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: ds2.xlarge
      ClusterType: single-node
```

2. Once created, create a snapshot of this cluster in Redshift
3. Then, launch another stack using the below template and specify the ID of the snapshot you just created for the `SnapshotId` parameter:
```
AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MasterUserPassword:
    Type: String
    NoEcho: true
  SnapshotId:
    Type: String
    Description: Identifier of Redshift cluster snapshot to restore from
Resources:
  myCluster:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: mydb
      MasterUsername: master
      MasterUserPassword: !Ref MasterUserPassword
      NodeType: ds2.xlarge
      ClusterType: single-node
      SnapshotIdentifier: !Ref SnapshotId
```

4. Each of these takes ~5 mins to create. Once the stack from step 3 is in CREATE_COMPLETE, check the stack for drift. It will show as drifted due to the `SnapshotIdentifier` property being removed.
