### ISSUE TITLE
Rules support for asserting regular expression match

### ISSUE THREAD

**Issue by glb** [aws-cloudformation/cloudformation-coverage-roadmap#1640]
### Name of the resource

Other

### Description

CloudFormation rules has a function `Fn::Contains` ([ref](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-rules.html#fn-contains)) to validate that a string is in a list of allowed values. This is great, but is limited to exact string matches, so all valid inputs must be provided in the list.

It would be useful to be able to have a `Fn::Matches` intrinsic function (or similar) that rules could use to match a string against a list of allowable patterns, so that template designers can set boundaries without needing to have an exhaustive list of possible inputs.

For example, the template below illustrates a rule that asserts that the input parameter `AccountEmail` must end in `@example.com`. It's infeasible<sup>\[citation needed]</sup> to provide a template enumerating all possible allowed email addresses, but a pattern would do the trick easily.

Prefer to be able to provide a list of patterns for consistency with `Fn::Contains` and pattern legibility; it would of course be possible to write a single-pattern equivalent with `|` separators, but it would be easier to write (and read) separate patterns.

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AccountEmail:
    Type: String
    Default: example@example.net

Rules:
  "Force example.com email domain":
    Assertions:
      - Assert:
          Fn::Matches:
            # This does not work, wish it did!
            - ["^[^@]+@example\\.com$"]
            - !Ref AccountEmail
        AssertDescription: "Email domain must be example.com"

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
```

**Comment by trav-c** [comment]
@glb can't your example can be handled with the existing AllowedPattern and ConstraintDescription properties of the [Parameter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html), eg

```
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  AccountEmail:
    Type: String
    Default: example@example.net
    AllowedPattern: "^[^@]+@example\\.com$"
    ConstraintDescription: "Email domain must be example.com"

Resources:
  DummyResource:
    Type: AWS::CloudFormation::WaitConditionHandle
    Properties: {}
```    

I'd still like to see something like this in the Rules too, because it would enable more complex combinations of validation rules, but I don't think it's strictly needed for what your example is trying to do?
