### ISSUE TITLE
[AWS::Backup::BackupPlan] implement `drift detection`

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1669]
### Name of the resource

AWS::Backup::BackupPlan

### Issue Description

[AWS::Backup::BackupPlan](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupplan.html) does not support drift detection. 

[Resources supported for drift detection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html).

### Expected Behavior

AWS::Backup::BackupPlan included in drift detection results.

### Observed Behavior

AWS::Backup::BackupPlan is NOT included in drift detection results.

### Test Cases

```
vault = backup.BackupVault(self, "Vault",
                           removal_policy=RemovalPolicy.DESTROY,
                           )

# Daily, weekly and monthly with 5 year retention
plan = backup.BackupPlan.daily_weekly_monthly5_year_retention(self, "Plan", backup_vault=vault, )
```

```aws cloudformation detect-stack-drift --stack-name BackupStack```
```aws cloudformation describe-stack-resource-drifts --stack-name BackupStack```

```
StackResourceDrifts:
- ActualProperties: '{"AssumeRolePolicyDocument":{"Statement":[{"Action":"sts:AssumeRole","Effect":"Allow","Principal":{"Service":"backup.amazonaws.com"}}],"Version":"2012-10-17"},"ManagedPolicyArns":["arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"]}'
  ExpectedProperties: '{"AssumeRolePolicyDocument":{"Statement":[{"Action":"sts:AssumeRole","Effect":"Allow","Principal":{"Service":"backup.amazonaws.com"}}],"Version":"2012-10-17"},"ManagedPolicyArns":["arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"]}'
  LogicalResourceId: PlanSelectionRole6D10F4B7
  PhysicalResourceId: BackupStack-PlanSelectionRole6D10F4B7-F2FVI6L5TPYH
  PropertyDifferences: []
  ResourceType: AWS::IAM::Role
  StackId: arn:aws:cloudformation:eu-central-1:000000000000:stack/BackupStack/58837fe0-f228-11ed-94d8-xxxxxxxxxxxxx
  StackResourceDriftStatus: IN_SYNC
  Timestamp: '2023-05-14T08:23:11.028000+00:00'
```
