### ISSUE TITLE
(AWS::SSM::Document) Implement `Drift Detection`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1675]
### Name of the resource

AWS::SSM::Document

### Issue Description

`AWS::SSM::Document` is not appearing in drift detection results, despite being documented as a resource being supported for drift detection:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

### Expected Behavior

`AWS::SSM::Document` included in drift detection results.

### Observed Behavior

`AWS::SSM::Document` is NOT included in drift detection results.

### Test Cases

```
  Document:
    Type: AWS::SSM::Document
    Properties:
      Name: "Test"
      DocumentType: "Command"
      Content:
        schemaVersion: "2.2"
        description: "Test"
        mainSteps:
          - action: aws:runShellScript
            name: runCommands
            precondition:
              StringEquals:
                - platformType
                - Linux
            inputs:
              runCommand:
                - 'Echo "CloudFormation is better than CDK"'
```
