### ISSUE TITLE
Updates to Tags on AWS::FSx::FileSystem Resulting in "UpdateFileSystem" 

### ISSUE THREAD

**Issue by GrantThompson1** [aws-cloudformation/cloudformation-coverage-roadmap#1687]
### Name of the resource

AWS::FSx::FileSystem

### Issue Description

Upon updating the "tags" for "AWS::FSx::FileSystem", the CloudFormation Service is unnecessarily calling "UpdateFileSystem", which results in an error due to the "DataRepositoryAssociation" between the File System and S3. The only work-around at this point is to delete the "DataRepositoryAssocation", update the tags, then add it back in. This is not desired.

### Expected Behavior

The FSx EventSource offers an API, [TagResource](https://docs.aws.amazon.com/cli/latest/reference/fsx/tag-resource.html), in order to add tags for an existing Amazon FSx Resource. I would expect to see this call performed by the CFN Service Role with request parameters being the FSx resource arn as well as the key/pair value. This tag update should be done with "No Interruption" as seen [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html).

### Observed Behavior

The ChangeSet defines changes for both "AWS::FSx::DataRepositoryAssociation" as well as "AWS::FSx::FileSystem". Then, the CloudFormation Service Role unnecessarily calls, **UpdateFileSystem** while setting: 
```
"lustreConfiguration": {
            "automaticBackupRetentionDays": 0
        }
```
This results in an error as this is unsupported: `Backups cannot be created on S3-linked file systems.`

### Test Cases

Replication Template:
```
Parameters:
  S3BucketName:
    Type: String
    Description: Desired name of the CodeCommit Repo
Resources:
  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
      - Key: Module
        Value: TlxLustreFsxStackOperations
      - Key: Owner
        Value: Bond
      - Key: Service
        Value: LustreFsx
      VersioningConfiguration:
        Status: Enabled
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
  TlxFsxSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: TlxFsxSecurityGroup
      SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        Description: Allow all outbound traffic by default
        IpProtocol: '-1'
      SecurityGroupIngress:
      - CidrIp: 10.41.144.0/20
        Description: from 10.41.144.0/20:988
        FromPort: 988
        IpProtocol: tcp
        ToPort: 988
      - CidrIp: 10.41.144.0/20
        Description: from 10.41.144.0/20:1018-1023
        FromPort: 1018
        IpProtocol: tcp
        ToPort: 1023
      VpcId: !GetAtt VPC1.VpcId

  TlxFsxSecurityGroupfromTlxLustreFsxStackOperationsTlxFsxSecurityGroup:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 988
      GroupId:
        Fn::GetAtt:
        - TlxFsxSecurityGroup
        - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
        - TlxFsxSecurityGroup
        - GroupId
      ToPort: 1023
  tlxFsxSGSR:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: '-1'
      FromPort: 0
      GroupId:
        Fn::GetAtt:
        - TlxFsxSecurityGroup
        - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
        - TlxFsxSecurityGroup
        - GroupId
      ToPort: 65535
  TlxLustreFsx:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: LUSTRE
      SubnetIds:
      - !GetAtt Subnet1.SubnetId
      LustreConfiguration:
        AutomaticBackupRetentionDays: 0
        CopyTagsToBackups: false
        DataCompressionType: LZ4
        DeploymentType: PERSISTENT_2
        PerUnitStorageThroughput: 125
      SecurityGroupIds:
      - Fn::GetAtt:
        - TlxFsxSecurityGroup
        - GroupId
      StorageCapacity: 1200
      Tags:
      - Key: Module
        Value: TlxLustreFsxStackOperations
      - Key: Owner
        Value: Bond
      - Key: Service
        Value: LustreFsx
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  LustreFsxDataRepositoryAssociation:
    Type: AWS::FSx::DataRepositoryAssociation
    Properties:
      DataRepositoryPath:
        Fn::Join:
        - ''
        - - s3://
          - Ref: S3bucket
          - /fspath
      FileSystemId:
        Ref: TlxLustreFsx
      FileSystemPath: /fspath
      BatchImportMetaDataOnCreate: true
      S3:
        AutoExportPolicy:
          Events:
          - NEW
          - CHANGED
          - DELETED
        AutoImportPolicy:
          Events:
          - NEW
          - CHANGED
          - DELETED
      Tags:
      - Key: Module
        Value: TlxLustreFsxStackOperations
      - Key: Owner
        Value: Bond
      - Key: Service
        Value: LustreFsx


  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        !Ref VPC1
      CidrBlock: 10.192.60.0/24
      AvailabilityZone: "us-east-1a"

  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.192.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
```
