### ISSUE TITLE
Port Attribute Missing on AWS::Neptune::DBCluster CloudFormaiton Public Docs

### ISSUE THREAD

**Issue by GrantThompson1** [aws-cloudformation/cloudformation-coverage-roadmap#1692]
### Name of the resource

AWS::Neptune::DBCluster

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html

## Issue:

The resource, [AWS::Neptune::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html), supports the attribute **Port** within the immediate **Properties** section. This can be confirmed with the replication template:

```
Resources:
    NeptuneDBCluster:
      Type: "AWS::Neptune::DBCluster"
      Properties:
        Port: 8182
```
That being said, on the [public docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html), there does not appear to be a note of this as it appears to be missing.

Typically, customers would expect to see all supported attributes listed here.
