### ISSUE TITLE
[AWS::MSK::Configuration] creates new revision even if no changes were made

### ISSUE THREAD

**Issue by sansmoraxz** [aws-cloudformation/cloudformation-coverage-roadmap#1709]
### Name of the resource

Other

### Resource Name

AWS::MSK::Configuration

### Issue Description

Update of cloudformation stack results always results in new revision being created

### Expected Behavior

No new revision should be created if no changes were made in the configuration

### Observed Behavior

New revision created as mentioned above

### Test Cases

Use the following basic resource in a template

```yaml
Resources:
  MSKConfiguration:
    Type: AWS::MSK::Configuration
    Properties:
      Description: Configuration for MSK cluster
      KafkaVersionsList:
        - 3.4.0
      ServerProperties: |
        auto.create.topics.enable=true
```

After creation run update stack with this current template
