### ISSUE TITLE
EC2 Key Pair creation fails with unhelpful error

### ISSUE THREAD

**Issue by marios-zindilis** [aws-cloudformation/cloudformation-coverage-roadmap#1711]
### Name of the resource

Other

### Resource name

AWS::EC2::KeyPair

### Description

This was originally reported in CDK in aws/aws-cdk:25929. When the value of `PublicKeyMaterial` is not well formatted, the creation of `AWS::EC2::KeyPair` fails with unhelpful error like:

```
Resource handler returned message: "null" (RequestToken: c6817ee0-0c65-b552-f35f-336715c567ce, HandlerErrorCode: InvalidRequest)
```

CloudFormation snippet to reproduce:

```yaml
Resources:
  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: keyName
      PublicKeyMaterial: somethingInvalid
```

It would be great if CloudFormation propagated the error from the back-end service.
