### ISSUE TITLE
[AWS::S3::Bucket] drift false positive with the properties ReplicationConfiguration: Metrics and ReplicationTime

### ISSUE THREAD

**Issue by tgyanen** [aws-cloudformation/cloudformation-coverage-roadmap#1714]
### Name of the resource

AWS::S3::Bucket

### Issue Description

CloudFormation detect drift returns false positive for the resource `AWS::S3::Bucket` `ReplicationConfiguration` properties - **Metrics** and **ReplicationTime** .

Sample Template

```
Resources:
  MyTestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      ReplicationConfiguration:
        Role: !GetAtt WorkItemBucketBackupRole.Arn
        Rules:
          - DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: '<YourBucketARN1>'
              Metrics:
                EventThreshold:
                  Minutes: 15
                Status: Enabled
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
              StorageClass: STANDARD
            Filter:
              Prefix: ''
            Id: Replication-1
            Priority: 1
            Status: Enabled
          - DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: '<YourBucketARN2>'
              Metrics:
                EventThreshold:
                  Minutes: 15
                Status: Enabled
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
              StorageClass: STANDARD
            Filter:
              Prefix: ''
            Id: Replication-2
            Priority: 2
            Status: Enabled
          - DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: '<YourBucketARN3>'
              Metrics:
                EventThreshold:
                  Minutes: 15
                Status: Enabled
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
              StorageClass: STANDARD
            Filter:
              Prefix: ''
            Id: Replication-3
            Priority: 3
            Status: Enabled
      VersioningConfiguration:
        Status: Enabled

  WorkItemBucketBackupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
  BucketBackupPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action: '*'
            Effect: Allow
            Resource: '*'
      PolicyName: BucketBackupPolicy
      Roles:
        - !Ref WorkItemBucketBackupRole
```

### Expected Behavior

CloudFormation should be reporting these properties as drifted

### Observed Behavior

Expected values show all the **Metrics** and **ReplicationTime** as defined in the template where as the current values show them as empty. 

### Test Cases

- Create a stack with the provided sample template. 
- Replace the bucket arn with valid bucket arns. 
- Run Detect drift after the stack is created successfully. 
- Select the drifted resource and View drifted results.
