### ISSUE TITLE
AWS::Events::Rule - False-positive drift on SqsParameters

### ISSUE THREAD

**Issue by dwiesttq** [aws-cloudformation/cloudformation-coverage-roadmap#1716]
### Name of the resource

AWS::Events::Rule

### Issue Description

CloudFormation detects drift on a newly created EventBridge Rule.  When viewing differences, the "Actual" output is missing the SqsParameters section for a target.

### Expected Behavior

No drift should be detected.

### Observed Behavior

![Screenshot 2023-06-15 120951](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/131815082/3a3a506c-b7e1-426d-b2be-c524054304d2)

![sqs_drift_cant_be_fixed](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/131815082/7be0982a-0846-42a3-869a-41fb3298ae97)

### Test Cases

```
AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template for EventBridge rule
  'StackSet-ControlTowerCust-CustomControlTowerLECWEv-R34C72XNSZQ5'
Resources:
  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      Description: >-
        Custom Control Tower - Rule for lifecycle events from Control Tower
        Service
      EventBusName: default
      EventPattern:
        detail-type:
          - AWS Service Event via CloudTrail
        source:
          - aws.controltower
        detail:
          serviceEventDetails:
            createManagedAccountStatus:
              state:
                - SUCCEEDED
          eventName:
            - CreateManagedAccount
      Name: StackSet-ControlTowerCust-CustomControlTowerLECWEv-R34C72XNSZQ5
      State: ENABLED
      Targets:
        - Id: CustomControlTower_Lifecycle_Event_FIFO_Queue
          Arn: >-
            arn:aws:sqs:us-east-1:123456789012:CustomControlTowerLEFIFOQueue.fifo
          SqsParameters:
            MessageGroupId: CustomControlTower_Lifecycle_Event
```
