### ISSUE TITLE
Cross region [AWS::RDS::DBInstance] read replica fails to create with mysql parameter [lower_case_table_names]

### ISSUE THREAD

**Issue by tgyanen** [aws-cloudformation/cloudformation-coverage-roadmap#1724]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

Unable to create a read replica from cross region with the parameter `lower_case_table_names` because CFN first creates the default DBParameterGroup and then it is modified after it is created. 

MySQL parameter `lower_case_table_names` cannot be modified as we see in in [Known issues and limitations for Amazon RDS for MySQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MySQL.KnownIssuesAndLimitations.html#MySQL.Concepts.ParameterNotes) . 

```
When a parameter group is associated with a version 8.0 MySQL DB instance, you can't modify the lower_case_table_names parameter in the parameter group.
```
Due to this limitation, we cannot create a cross region replica with the parameter `lower_case_table_names`. 

### Expected Behavior

Be able to create a cross region replica with the parameter `lower_case_table_names`.  

### Observed Behavior

Error 
```
Resource handler returned message: "DB Instance is in state: incompatible-restore"
```

### Test Cases

Create a read replica using the following template
```
Resources:
  MyDB1:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      SourceDBInstanceIdentifier: arn:aws:rds:<region>:<AccountId>:db:<instanceid>
      StorageType: gp2
      DBInstanceClass: 'db.m5.large'
      AllocatedStorage: 20
      Engine: mysql
      EngineVersion: '8.0.32'
      MasterUsername: XXXXX
      MasterUserPassword: XXXXX
      DBParameterGroupName: !Ref DBParameterGroup
  DBParameterGroup1:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: MySQL parameters
      Family: 'mysql8.0'
      Parameters: 
        lower_case_table_names: '1'
```
