### ISSUE TITLE
(AWS::Scheduler::Schedule) False-positive drift for the CFN Resource

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1725]
### Name of the resource

AWS::ACMPCA::Certificate

### Resource Name

AWS::Scheduler::Schedule

### Issue Description

When creating a `AWS::Scheduler::Schedule` in `eu-central-1` using

```
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: "rate(5 minutes)"
      ScheduleExpressionTimezone: "Europe/Berlin"
      FlexibleTimeWindow: 
        Mode: "OFF"
      State: "ENABLED"
      Target:
        Arn: !GetAtt LambdaFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
```

it will cause a drift:

Logical ID | Physical ID | Type | Drift status | Timestamp | Module
-- | -- | -- | -- | -- | --
Schedule | Schedule-4R77P4CM01UD | AWS::Scheduler::Schedule | DELETED | 2023-06-26 07:40:05 UTC+0200 | -

### Expected Behavior

Drift is recognizing the AWS Resource.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      ScheduleExpression: "rate(5 minutes)"
      ScheduleExpressionTimezone: "Europe/Berlin"
      FlexibleTimeWindow: 
        Mode: "OFF"
      State: "ENABLED"
      Target:
        Arn: !GetAtt LambdaFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
```
