### ISSUE TITLE
(AWS::Events::Rule) Severity float values converted to integer

### ISSUE THREAD

**Issue by FarrOut** [aws-cloudformation/cloudformation-coverage-roadmap#1735]
### Name of the resource

AWS::Events::Rule

### Issue Description

Cloudformation seems to be erroneously converting float values of the *Severity* key of the [EventPattern](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern) property to integers, preventing one from creating rules as [documented](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings_cloudwatch.html#setup_cloudwatch_event).

Example:
*4,4.0* results in *4,4*

This breaks the design of the Events service as:
> Number matching is at the string representation level. For example, 300, 300.0, and 3.0e2 are not considered equal.
[EventPattern doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatchEventsandEventPatterns.html#CloudWatchEventsPatterns)

### Expected Behavior

The following eventpattern should produce a Rule filter which includes values defined as float, e.g ```4.0```

*EventPattern in template*
```
{
            source: ['aws.guardduty'],
            detailType: ['GuardDuty Finding'],
            detail: {
                configRuleName: [props?.eventBridgeGuardDutyName],
                severity: [
                    4,
                    4.0,
                    4.1,
                    5,
                    5.0,
                    6,
                    6.0,
                    7,
                    7.0,
                    7.1,
                    8,
                    8.0,
                    99.0,
                    99.9,
                    1.0E+2
                ],
            },
        }
```

*Expected Result*
```
{
  "detail-type": ["GuardDuty Finding"],
  "source": ["aws.guardduty"],
  "detail": {
    "severity": [4, 4.0, 4.1, 5, 5.0, 6, 6.0, 7, 7.0, 7.1, 8, 8.0, 99, 99.9, 100],
    "configRuleName": ["sentry"]
  }
}
```

### Observed Behavior

However, in the resulting Rules the float values with a ```.0``` decimal are converted to integer. Notice how *4.0*, *5.0*, *6.0* etc are converted to [duplicate] *4*, *5,*,*6* etc...

*Actual results*
```
{
  "detail-type": ["GuardDuty Finding"],
  "source": ["aws.guardduty"],
  "detail": {
    "severity": [4, 4, 4.1, 5, 5, 6, 6, 7, 7, 7.1, 8, 8, 99, 99.9, 100],
    "configRuleName": ["sentry"]
  }
}
```

### Test Cases

*CDK code*
```
import * as cdk from 'aws-cdk-lib';
import {CfnOutput, CfnParameter, StackProps} from 'aws-cdk-lib';
import {Construct} from 'constructs';
import {Rule} from "aws-cdk-lib/aws-events";

export interface EventsProps extends StackProps {
    eventBridgeGuardDutyName: string;
}


export class EventsStack extends cdk.Stack {


    constructor(scope: Construct, id: string, props?: EventsProps) {
        super(scope, id, props);

        const sev = new CfnParameter(this, "Sev", {
            type: "Number",
            default: 55.0
        });

        let EventPattern = {
            source: ['aws.guardduty'],
            detailType: ['GuardDuty Finding'],
            detail: {
                configRuleName: [props?.eventBridgeGuardDutyName],
                severity: [
                    4,
                    4.0,
                    4.1,
                    5,
                    5.0,
                    6,
                    6.0,
                    7,
                    7.0,
                    7.1,
                    8,
                    8.0,
                    99.0,
                    99.9,
                    sev.valueAsNumber,
                    1.0E+2
                ],
            },
        }
        let rule = new Rule(this, 'EventBridgeGuardDutyRule', {
                ruleName: props?.eventBridgeGuardDutyName,
                description: 'GuardDuty eventbridge rule.',
                enabled: true,
                eventPattern: EventPattern
            }
        )

        new CfnOutput(this, 'RuleArn', {
                value: rule.ruleArn,
                description: "The value of the event rule Amazon Resource Name (ARN).",
            }
        )
        new CfnOutput(this, 'RuleName', {
                value: rule.ruleName,
                description: "The name event rule.",
            }
        )
    }
}
```

* Synthed Cfn template*
```
Parameters:
  Sev:
    Type: Number
    Default: 55
Resources:
  EventBridgeGuardDutyRule5167B061:
    Type: AWS::Events::Rule
    Properties:
      Description: GuardDuty eventbridge rule.
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
        detail:
          configRuleName:
            - sentry
          severity:
            - 4
            - 4
            - 4.1
            - 5
            - 5
            - 6
            - 6
            - 7
            - 7
            - 7.1
            - 8
            - 8
            - 99
            - 99.9
            - Ref: Sev
            - 100
      Name: sentry
      State: ENABLED
Outputs:
  RuleArn:
    Description: The value of the event rule Amazon Resource Name (ARN).
    Value:
      Fn::GetAtt:
        - EventBridgeGuardDutyRule5167B061
        - Arn
  RuleName:
    Description: The name event rule.
    Value:
      Ref: EventBridgeGuardDutyRule5167B061
```

*Result*
```
{
  "detail-type": ["GuardDuty Finding"],
  "source": ["aws.guardduty"],
  "detail": {
    "severity": [4, 4, 4.1, 5, 5, 6, 6, 7, 7, 7.1, 8, 8, 99, 99.9, 55, 100],
    "configRuleName": ["sentry"]
  }
}
```

### Other Details

Some interesting points worth considering:
* Importing as Parameter doesn't help (see test case)
* Wrapping in double-quotes doesn't help, ends up as string in Rule
* **WORKAROUND** by updating the template using Designer one can trick Cfn into processing float values as-is. However, when switching JSON<->YAML the decimals are lost again! 
* This leads me to believe that the issue has something to do with how Cfn is interpreting the JSON/YAML before sending template off for processing.
* Would a macro to add eventpattern with floats in-tact before deploying be a more seamless workaround in the interim?
* Might be related to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/251
