### ISSUE TITLE
Add WaitCondition for EventBridge/SNS

### ISSUE THREAD

**Issue by andyRokit** [aws-cloudformation/cloudformation-coverage-roadmap#1741]
### Name of the resource

AWS::CloudFormation::WaitCondition

### Description

AWS has a healthy ecosystem of events bubbling away under the hood (expanding every day).  However CloudFormation doesn't currently have a neat way of tapping into these events.

Please consider adding a resource which listens for them.  E.g.

```
CodeBuildCompleteCondition:
  Type: AWS:CloudFormation:EventBridgeCondition
  EventPattern: [1]

MyLambda:
  Type: AWS::Lambda::Function
  Properties:
    FunctionName: MyLambda
    Runtime: python3.8
    Handler: index.handler
    Code:
      S3Arn: GetAtt! CodeBuildCompleteCondition.detail.additional-information.artifact.location
```
Note:  It would be useful if the output of the resource matched EB's event structure [2].  See CodeCommit example [3].

A similar mechanism could be adapted for SNS.

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern 
[2] https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events-structure.html
[3] https://docs.aws.amazon.com/codebuild/latest/userguide/sample-build-notifications.html#sample-build-notifications-ref
