### ISSUE TITLE
Create a "DefaultStackName"  Section 

### ISSUE THREAD

**Issue by ccharland** [aws-cloudformation/cloudformation-coverage-roadmap#1764]
### Name of the resource

Other

### Resource name

Template anatomy

### Description

I'd like to include a Default Stack Name in the template and allow it to use some Pseudo Parameters

For example: 

``` YAML
Description: SampleStack with a default stackname

DefaultStackName:
  !Sub: "MyStack-$(AWS::Account}-${AWS::Region}" 

Resources:
   <.....>

```

Some of the benefits would be:

1. Consistency in naming when deploying to multiple accounts and regions.
2. Improved development speed and testing of new templates by having one less thing to type.

### Other Details

Here are a couple of other people that have requested this feature:

https://stackoverflow.com/questions/51828313/is-it-possible-to-statically-specify-awsstackname-inside-a-cloudformation-temp

https://www.reddit.com/r/aws/comments/oix0wj/specify_stack_name_within_cloudformation_template/

**Comment by benkehoe** [comment]
I disagree strongly with this. The stack name doesn't belong inside the template; that defeats the purpose of it being a template. And it's especially bad to have the stack name only resolved _after_ the `CreateStack` call has been made. I often see people pushing in this direction, but it shouldn't be a goal that `CreateStack` only has one parameter (i.e., the template).

If someone really wants to do this, I think it's better to do it in a custom way using the `Metadata` section, in a way that's specific to your process and requirements. As an example:

```yaml
Metadata:
    DefaultStackName: "MyStack-${Account}-${Region}"
Resources:
    MyTopic:
        Type: AWS::SNS::Topic
        Properties: {}

```

and then process it as part of your deployment:

```python
#!/bin/env python3

import string
import sys
import argparse

import boto3
import yaml

parser = argparse.ArgumentParser()
parser.add_argument("--profile")
parser.add_argument("template", type=argparse.FileType())

args = parser.parse_args()

data = yaml.safe_load(args.template)

stack_name_template = string.Template(data["Metadata"]["DefaultStackName"])

session = boto3.Session(profile_name=args.profile)

caller_identity = session.client("sts").get_caller_identity()

account = caller_identity["Account"]
region = session.region_name

stack_name = stack_name_template.substitute(Account=account, Region=region)

print(stack_name)
```
