### ISSUE TITLE
Conditions in CloudFormation Output Naming Confict issue

### ISSUE THREAD

**Issue by ymrenn** [aws-cloudformation/cloudformation-coverage-roadmap#1768]
### Name of the resource

AWS::CloudFormation::Stack

### Description

We know that for logical ID in CloudFormation template should be unique. However, if using conditions in the output section, two output have the same logical ID would not resolve a Create/Update failure, instead, if does not show the output value as expected.

Here is the template that I used to test:
==================================================
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation workshop - Conditions at Outputs level (uksb-1q9p31idr).

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  EnvType:
    Description: Specify the Environment type of the stack.
    Type: String
    AllowedValues:
      - test
      - prod
    Default: test
    ConstraintDescription: Specify either test or prod.

Conditions:
  IsProduction: !Equals 
    - !Ref EnvType
    - prod
  IsNotProduction: !Equals 
    - !Ref EnvType
    - test

Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
  MountPoint:
    Type: 'AWS::EC2::VolumeAttachment'
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref Volume
      Device: /dev/sdh
    Condition: IsProduction
  Volume:
    Type: 'AWS::EC2::Volume'
    Properties:
      Size: 2
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Encrypted: true
    Condition: IsProduction

Outputs:
  VolumeId:
    Value: !Ref Volume
    Condition: IsProduction
  VolumeId:
    Value: !Ref EC2Instance
    Condition: IsNotProduction
=========================================================
1. With the above template, I have defined the output "VolumeId" twice in the template, the stack deployed successfully. It shows output value when I was in "test" condition, but it does not show value when I was in "prod" condition. 
2. I have changed the second "VolumeId" to "EC2Id", and the stack update successful, and the output value shows for each condition. 

Therefore, I am requesting is there should throw an error to not let the creation/update completed? Or giving some notifications on the naming conflicts?

**Comment by Risae** [comment]
You can use code formatting to better highlight the code section in your GitHub issue: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

it would look like this:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation workshop - Conditions at Outputs level (uksb-1q9p31idr).

Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::ValueAWS::EC2::Image::Id
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    EnvType:
    Description: Specify the Environment type of the stack.
    Type: String
    AllowedValues:
      - test
      - prod
    Default: test
    ConstraintDescription: Specify either test or prod.

Conditions:
  IsProduction: !Equals
    - !Ref EnvType
    - prod
  IsNotProduction: !Equals
    - !Ref EnvType
    - test

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref Volume
      Device: /dev/sdh
      Condition: IsProduction
      Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 2
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Encrypted: true
      Condition: IsProduction

Outputs:
  VolumeId:
    Value: !Ref Volume
    Condition: IsProduction
  VolumeId:
    Value: !Ref EC2Instance
    Condition: IsNotProduction
```

**Comment by benbridts** [comment]
It is indeed weird that you didn't get an error, because this isn't valid yaml, you can't have the same key on the same level multiple times:

```yaml
Outputs:
  VolumeId:  # first time
    Value: !Ref Volume
    Condition: IsProduction
  VolumeId:  # second time on the same level - not allowed
    Value: !Ref EC2Instance
    Condition: IsNotProduction
```

You can solve this with an `!If` though:

```yaml
Outputs:
  VolumeId:
    Value: !If [IsProduction, !Ref Volume,  !Ref EC2Instance]
```

Or if you want to keep the `IsNotProduction` condition:

```yaml
Outputs:
  VolumeId:
    Value: !If [IsProduction, !Ref Volume,  !if [IsNotProduction, !Ref EC2Instance, UNDEFINED]]
```
