### ISSUE TITLE
KMS Key created with cloudformation lack the defaults "attribution" Tags

### ISSUE THREAD

**Issue by bplessis-swi** [aws-cloudformation/cloudformation-coverage-roadmap#1782]
### Name of the resource

AWS::KMS::Key

### Issue Description

KMS Key created via cloudformation don't include the three standard cloudformation tags:

* aws:cloudformation:stack-id
* aws:cloudformation:stack-name
* aws:cloudformation:logical-id

### Expected Behavior

The created resource should have the resource specified tags, the stack specified tags and the cfn default tags on it

### Observed Behavior

Only direct tags and stack-level custom tags are present

### Test Cases

```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Test CFN Tags Key
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
       - Key: Test-custom-tag
         Value: Value
```

Stack created with
```sh
$ aws cloudformation deploy --stack-name test-bplessis-kms --template-file test.yml --tags product=test-prod environmentType=preprod
...
$ aws kms list-resource-tags --key-id xxxxx-yyyy-zzzz --no-cli-pager
{
    "Tags": [
        {
            "TagKey": "Test-custom-tag",
            "TagValue": "Value"
        },
        {
            "TagKey": "environmentType",
            "TagValue": "preprod"
        },
        {
            "TagKey": "product",
            "TagValue": "test-prod"
        }
    ]
}
```
