### ISSUE TITLE
AWS::MSK::ServerlessCluster & AWS::MSK::Cluster - Add bootstrapServers as an output

### ISSUE THREAD

**Issue by mattyboy84** [aws-cloudformation/cloudformation-coverage-roadmap#1792]
### Name of the resource

Other

### Resource name

AWS::MSK::ServerlessCluster & AWS::MSK::Cluster

### Description

Creating an `AWS::MSK::ServerlessCluster` in cloudformation can be done like:
```yaml
  ServerlessCluster:
    Type: AWS::MSK::ServerlessCluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}-cluster"
      ClientAuthentication:
        Sasl: 
          Iam: 
            Enabled: true
      VpcConfigs:
        - SecurityGroups:
            - !Ref securityGroup
          SubnetIds:
            - !Ref subnetA
            - !Ref subnetB
            - !Ref subnetC
```

If you also want to define a `AWS::KafkaConnect::Connector` on that cluster in the same template, the `BootstrapServers` parameter is required like this:
```yaml
  MyKafkaConnectConnector:
    Type: AWS::KafkaConnect::Connector
    Properties:
      KafkaCluster:
        ApacheKafkaCluster:
          BootstrapServers: **BootstrapServers**
          Vpc:
            SecurityGroups:
              - !Ref securityGroup
            Subnets:
              - !Ref subnetA
              - !Ref subnetB
              - !Ref subnetC
```

I would propose a new output on the `AWS::MSK::ServerlessCluster` & `AWS::MSK::Cluster` resource called `bootstrapServers` that can be retreived like: !GetAtt ServerlessCluster.bootstrapServers
