### ISSUE TITLE
AWS::AppSync::GraphQLSchema.DefinitionS3Location report bucket in another region

### ISSUE THREAD

**Issue by jerry153fish** [aws-cloudformation/cloudformation-coverage-roadmap#1793]
### Name of the resource

AWS::AppSync::GraphQLSchema

### Issue Description

When configured with the DefinitionS3Location for schema location, it may report that the bucket is not in the current location. However, it is actually configured with the same region as other AppSync resources.

```
The bucket is in this region: us-west-2. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: xxxx; S3 Extended Request ID: xxx; Proxy: null)
```

### Expected Behavior

It should locate the bucket in the same region.

### Observed Behavior

Encountering region mismatch errors while attempting to access the bucket. In two separate tests using different bucket names, I observed instances in both the us-west-2 and us-east-1 regions.

### Test Cases

```
Resources:
  PubSub:
    Properties:
      AuthenticationType: API_KEY
      Name: PubSub
    Type: AWS::AppSync::GraphQLApi
  PubSubDebugApiKey:
    Properties:
      ApiId: !GetAtt 'PubSub.ApiId'
    Type: AWS::AppSync::ApiKey
  PubSubSchemas:
    Properties:
      ApiId: !GetAtt 'PubSub.ApiId'
      DefinitionS3Location: pub-sub-appsync-ap-southeast-2/schema/schema.graphqls
    Type: AWS::AppSync::GraphQLSchema
```
