### ISSUE TITLE
(AWS::Lambda::Function) False-positive drift for `FileSystemConfigs`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1796]
### Name of the resource

AWS::Lambda::Function

### Issue Description

When creating a `AWS::Lambda::Function` in `eu-central-1` using

```yaml
FileSystemConfigs:
  - Arn: <EFSAccessPointARN>
    LocalMountPath: /mnt/efs
```

it will cause a drift:

Property | Change | Expected value | Current value
-- | -- | -- | --
FileSystemConfigs | REMOVE | [{"Arn":"\<EFSAccessPointARN\>","LocalMountPath":"/mnt/efs"}] | -

### Expected Behavior

Drift is recognizing the `FileSystemConfigs`.

### Observed Behavior

Is it showing up as a false positive drift in CloudFormation.

### Test Cases

```yaml
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      MemorySize: 512
      Role: <LambdaRole>
      Runtime: python3.11
      Architectures:
        - arm64
      Timeout: 120
      VpcConfig:
        SecurityGroupIds:
          - <SecurityGroup>
        SubnetIds:
          - <VPC1-AZ1Subnet1>
      FileSystemConfigs:
        - Arn: <EFSAccessPointARN>
          LocalMountPath: /mnt/efs
      Code:
        ZipFile: |
          def lambda_handler(event, context):

                    print("Hello World")
```
