### ISSUE TITLE
(AWS::EFS::FileSystem) Changing `ThroughputMode` in the AWS GUI is not recognized by Drift Detection

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1809]
### Name of the resource

AWS::EFS::FileSystem

### Issue Description

When you create a `AWS::EFS::FileSystem` using CloudFormation

```yaml
  EFSVolume:
    Type: AWS::EFS::FileSystem
    Properties:
      AvailabilityZoneName: !Sub "${AWS::Region}a"
      BackupPolicy:
        Status: "DISABLED"
```

The default `ThroughputMode` will be `bursting`. Changing `bursting` to `elastic` in the AWS GUI will result in the CloudFormation Stack to be drifted, but this is not recognized by Drift Detection and the Resource is showing up as `Resource drift status: IN_SYNC`

### Expected Behavior

Drift Detection of `AWS::EFS::FileSystem` is working for the `ThroughputMode`.

### Observed Behavior

It's not working.

### Test Cases

1. Create an EFS Volume:

```yaml
  EFSVolume:
    Type: AWS::EFS::FileSystem
    Properties:
      AvailabilityZoneName: !Sub "${AWS::Region}a"
      BackupPolicy:
        Status: "DISABLED"
```

2. Change the `ThroughputMode` to a different value in the AWS GUI
3. Check the Resource Drift in the Drift Detection GUI

**Comment by FarrOut** [comment]
Confirmed.

*template*
```
Type: AWS::EFS::FileSystem
Properties:
  Encrypted: true
  FileSystemTags:
    - Key: Name
      Value: EfsStack/EfsNestedStack/Efs
UpdateReplacePolicy: Delete
DeletionPolicy: Delete

```

## Drift

**IN_SYNC**

### Expected
```
{
  "Encrypted": true,
  "FileSystemTags": [
    {
      "Value": "EfsStack/EfsNestedStack/Efs",
      "Key": "Name"
    }
  ]
}
```

### Actual
```
{
  "Encrypted": true,
  "FileSystemTags": [
    {
      "Key": "Name",
      "Value": "EfsStack/EfsNestedStack/Efs"
    }
  ]
}
```
