### ISSUE TITLE
(AWS::SSM::Document) False-positive drift for `Content`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1811]
### Name of the resource

AWS::SSM::Document

### Issue Description

When creating a `AWS::SSM::Document` in `eu-central-1` using

```yaml
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Command"
      Content:
        schemaVersion: "2.2"
        description: "SSM Document"
        mainSteps:
          - name: Test
            action: aws:runPowerShellScript
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              runCommand:
                - 'echo "Test"'
```

it will cause a drift:

Property | Change | Expected value | Current value
-- | -- | -- | --
Content | REMOVE | \<content\> | -

### Expected Behavior

Drift Detection works.

### Observed Behavior

It doesn't work.

### Test Cases

```yaml
  SSMDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: "Command"
      Content:
        schemaVersion: "2.2"
        description: "SSM Document"
        mainSteps:
          - name: Test
            action: aws:runPowerShellScript
            precondition:
              StringEquals:
                - platformType
                - Windows
            inputs:
              runCommand:
                - 'echo "Test"'
```

### Other Details

Be aware that Drift Detection for AWS::SSM::Document is new-ish: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1675
