### ISSUE TITLE
Failure creating ECR Repository using Fn::ToJsonString to form LifeCyclePolicyText

### ISSUE THREAD

**Issue by rswift** [aws-cloudformation/cloudformation-coverage-roadmap#1815]
### Name of the resource

AWS::ECR::Repository

### Issue Description

CloudFormation is converting a `Number` type value to a string when putting a policy on an ECR repository resulting in API failure.

Parameter:

```yaml
  ImagesToRetain:
    Type: Number
    Description: How many images to retain before expiring, between 1 and 9
    Default: 3
    MinValue: 1
    MaxValue: 9
    ConstraintDescription: A number between 1 and 9
```

Resource (snipped for readability):

```yaml
ContainerImageRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ...
      LifecyclePolicy:
        LifecyclePolicyText:
          Fn::ToJsonString:
            rules:
            - rulePriority: 1
              description: !Sub Retain the latest ${ImagesToRetain} images
              selection:
                tagStatus: any
                countType: imageCountMoreThan
                countNumber: !Ref ImagesToRetain
              action:
                type: expire
```

### Expected Behavior

The repo is created as the value is defined as a `Number` 😒

### Observed Behavior

An error message in the CloudFormation console is:

```
Resource handler returned message: "Invalid parameter at 'LifecyclePolicyText' failed to satisfy constraint: 'Lifecycle policy validation failure: instance type (string) does not match any allowed primitive type (allowed: ["integer"]) 
```

The CloudTrail entry for the `PutLifecyclePolicy` API call clearly shows the `countNumber` value in double quotes:

```
"errorMessage": "Invalid parameter at 'LifecyclePolicyText' failed to satisfy constraint: 'Lifecycle policy validation failure: instance type (string) does not match any allowed primitive type (allowed: [\"integer\"])\n'",
"requestParameters": {
    "repositoryName": "prefix/repo",
    "lifecyclePolicyText": "{\"rules\":[{\"rulePriority\":1,\"description\":\"Retain the latest 3 images\",\"selection\":{\"tagStatus\":\"any\",\"countType\":\"imageCountMoreThan\",\"countNumber\":\"3\"},\"action\":{\"type\":\"expire\"}}]}"
},
```

### Test Cases

`Number` type parameter should pass through to the API call with an integer value in the `countNumber` field as per https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html#lp_count_number

### Other Details

I have a workaround, but it's somewhat bonkers to have to do this:

```yaml
                countNumber: !Select [ !Ref ImagesToRetain, [ 0,1,2,3,4,5,6,7,8,9 ] ]
```
