### ISSUE TITLE
AWS Image Builder resources doesn't get the stack level tags.

### ISSUE THREAD

**Issue by srcndogan** [aws-cloudformation/cloudformation-coverage-roadmap#1817]
### Name of the resource

AWS::ImageBuilder::ImagePipeline

### Description

Created a stack for resource type AWS::ImageBuilder::ImagePipeline 
```
Resources:  
  ImagePipelineAllParameters:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: 'image-pipeline-name-2'
      Description: 'description'
      ImageRecipeArn: arn:aws:imagebuilder:us-east-1:12345678:image-recipe/amazon-linux-2-with-latest-ssm-agent/0.0.1
      InfrastructureConfigurationArn: arn:aws:imagebuilder:us-east-1:12345678:infrastructure-configuration/amazon-linux-2-with-latest-ssm-agent-infrastructure-configuration
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 90
      Schedule:
        ScheduleExpression: 'cron(0 0 * * ? *)'
        PipelineExecutionStartCondition: 'EXPRESSION_MATCH_ONLY'
      Status: 'DISABLED'
      Tags:
        Key: Name
        # Value: test
        # test1: value1
```

Applied stack level tags as 'test1: value1' while creating the stack.
Resource got created and no tags being applied to resource.
Commented out the above Tags part and updated my stack, Tags got applied. So stack level tags are not being applied during the CREATE nor UPDATE operation.

I have tested this behavior for other resource types for Image Builder and none of them applying the stack level tags. List of resource types for CFN as below.

- AWS::ImageBuilder::Component
- AWS::ImageBuilder::Image
- AWS::ImageBuilder::ImageRecipe
- AWS::ImageBuilder::InfrastructureConfiguration
- AWS::ImageBuilder::DistributionConfiguration
- AWS::ImageBuilder::ImagePipeline
- AWS::ImageBuilder::ContainerRecipe

### Other Details

Types for Tags in the Image Builder resource are Map of String where usually Tags would be a List of string.
Workaround at the moment applying tags at resource level. However, expecting to apply stack level tags to resources above.
