### ISSUE TITLE
ExternalId return value for AWS::DMS::Endpoint not working?

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/cloudformation-coverage-roadmap#1823]
### Name of the resource

AWS::DMS::Endpoint

### Issue Description

The documentation for the AWS::DMS::Endpoint resource indicates that there are 2 [returned values](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#aws-resource-dms-endpoint-return-values) available:

1. `!Ref` returns the ARN
2. `!GetAtt` can return the `ExternalId`

### Expected Behavior

I expect both documented return values to function.

### Observed Behavior

The former is working fine for me. The latter is returning an error for me.

On stack update, I see an error event, with a "status reason" ...

> Cannot export output EndpointTargetId. Exported values must not be empty or whitespace-only.

See example code below to understand the `EndpointTargetId` being referenced in that message.

### Test Cases

Some example code to illustrate (note that the first output works fine, while the second output returns the error) ..

```YAML

Resources:

  EndpointTarget:
    Type: AWS::DMS::Endpoint
    Properties:
      [...]

Outputs:

  EndpointTargetArn: # works fine
    Export:
      Name: target-arn
    Value: !Ref EndpointTarget

  EndpointTargetId: # returns error
    Export:
      Name: target-id
    Value: !GetAtt EndpointTarget.ExternalId

```

### Other Details

This could be user error - I'm hoping someone else would be willing to try to repro.
