### ISSUE TITLE
Enhanced FindInMap fails within ImportValue

### ISSUE THREAD

**Issue by tedmoyses** [aws-cloudformation/cloudformation-coverage-roadmap#1826]
### Name of the resource

Other

### Resource Name

AWS::LanguageExtensions

### Issue Description

When using FindInMap to lookup a value to use for the StackName to import from, we cannot use Sub in the TopLevelKey value. This fails with the message:
`every Fn::FindInMap object requires three parameters, the map name, map key and the attribute for return value`

In the test cases enclosed - the first instance fails but the second will work

### Expected Behavior

Sub should be useable in the TopLevelKey value in a call to FindInMap when used with ImportValue when using AWS::LanguageExtensions transform

### Observed Behavior

The FindInMap fails validation or otherwise throws the error:
`every Fn::FindInMap object requires three parameters, the map name, map key and the attribute for return value`

### Test Cases

Failing test below:

``` yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::LanguageExtensions'
Parameters:
  Environment:
    Type: String
    Default: staging
    Description: prod, staging etc
Mappings:
  Config:
    eu-west-1.staging:
      NetworkStackName: 'testnonprodnetwork'
    eu-west-1.production:
      NetworkStackName: 'prodnetwork'
Resources:
  SidekiqCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${AWS::StackName} Sidekiq Cache Security Group"
      VpcId:
        Fn::ImportValue: !Sub
          - '${NetworkStackName}-VPCID'
          - NetworkStackName: !FindInMap [Config, !Sub "${AWS::Region}.${Environment}", NetworkStackName]
```

Work-around shown

``` yaml
---
AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::LanguageExtensions'
Parameters:
  Environment:
    Type: String
    Default: staging
    Description: prod, staging etc
Mappings:
  Config:
    eu-west-1.staging:
      NetworkStackName: 'testnonprodnetwork'
    eu-west-1.production:
      NetworkStackName: 'prodnetwork'
  RegionEnvironment:
    eu-west-1:
      staging: 'eu-west-1.staging'
Resources:
  SidekiqCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "${AWS::StackName} Sidekiq Cache Security Group"
      VpcId:
        Fn::ImportValue: !Sub
          - '${NetworkStackName}-VPCID'
          - NetworkStackName: !FindInMap [Config, !FindInMap [RegionEnvironment, !Ref AWS::Region, !Ref Environment], NetworkStackName]
```

### Other Details

Outside of ImportValue this style of addressing the TopLevelKey in calls to FindInMap have been used successfully to lookup values.

A work-around has been implemented using a second Mapping that maps the Region and Environment values to a compound key which can be used as the value for the TopLevelKey successfully - this leads me to believe that the LanguageExtention is not being applied to a FindInMap within an ImportValue call
