### ISSUE TITLE
AWS::MediaConvert::Preset "The following property in '/SettingsJson/AudioDescriptions/0/CodecSettings' isn't supported: FlacSettings."

### ISSUE THREAD

**Issue by seagyn** [aws-cloudformation/cloudformation-coverage-roadmap#1828]
### Name of the resource

AWS::MediaConvert::Preset

### Issue Description

When trying to create a preset via Cloudformation using no container and the FLAC codec I get the following error:

```sh
The following resource(s) failed to create: [OutputPreset]. Rollback requested by user." "The following property in '/SettingsJson/AudioDescriptions/0/CodecSettings' isn't supported: FlacSettings.
```

This is the config I passed to it (YAML) based on the settings from a manually created Preset in the Console.

```yaml
CodecSettings:
   FlacSettings:
      bitDepth: 24
      channels: 2
      sampleRate: 44100
  Codec: FLAC
```

### Expected Behavior

Expected the ability to create a Flac based preset.

### Observed Behavior

Errors without creating the preset.

### Test Cases

NA
