### ISSUE TITLE
Transform AWS::LanguageExtensions failed with: Condition layout is incorrect. Rollback requested by user

### ISSUE THREAD

**Issue by Luchiap** [aws-cloudformation/cloudformation-coverage-roadmap#1834]
### Name of the resource

Other

### Resource Name

AWS::LanguageExtensions

### Issue Description

The following code 
```
AWSTemplateFormatVersion: 2010-09-09
Conditions:
  CreateProdAlarm: !Equals #this is true when Environment (which is a parameter) is equal to prod
    - !Ref Environment
    - prod
Transform: 'AWS::LanguageExtensions'
Parameters:
  pRepoARNs1:
    Description: ARN of SSO instance
    Type: CommaDelimitedList
  prepoARNs2:
    Description: ARN of SSO instance
    Type: CommaDelimitedList
  Environment:
    Description: Environment type.
    Type: String
    AllowedValues:
      - prod
      - test
Resources:
  'Fn::ForEach::Topics':
    - TopicName2
    - !If 
      - CreateProdAlarm #if the condition evaluates to true, then use pRepoARNs1, if false use prepoARNs2
      - !Ref pRepoARNs1
      - !Ref prepoARNs2
    - 'SnsTopic${TopicName2}':
        Condition: CreateProdAlarm
        Type: 'AWS::SNS::Topic'
        Properties:
          TopicName: 
           'Fn::Join':
            - '.'
            - - !Ref TopicName2
              - fifo
          FifoTopic: true
``` 
if deployed in cloudformation will give error:
`Transform AWS::LanguageExtensions failed with: Condition layout is incorrect. Rollback requested by user.`

While the virtually same template down below will work with no issues.
```
AWSTemplateFormatVersion: 2010-09-09
Conditions:
  CreateProdAlarm: !Equals #this is true when Environment (which is a parameter) is equal to prod
    - !Ref Environment
    - prod
Transform: 'AWS::LanguageExtensions'
Parameters:
  pRepoARNs1:
    Description: ARN of SSO instance
    Type: CommaDelimitedList
  prepoARNs2:
    Description: ARN of SSO instance
    Type: CommaDelimitedList
  Environment:
    Description: Environment type.
    Type: String
    AllowedValues:
      - prod
      - test
Resources:
  'Fn::ForEach::Topics':
    - TopicName2
    - !If 
      - CreateProdAlarm #if the condition evaluates to true, then use pRepoARNs1, if false use prepoARNs2
      - !Ref pRepoARNs1
      - !Ref prepoARNs2
    - 'SnsTopic${TopicName2}':
        Type: 'AWS::SNS::Topic'
        Condition: CreateProdAlarm
        Properties:
          TopicName: 
           'Fn::Join':
            - '.'
            - - !Ref TopicName2
              - fifo
          FifoTopic: true
        
``` 

The difference?
The line order. In the second template notice that Type: 'AWS::SNS::Topic' goes at the end. After the Condition statement of the resource.

### Expected Behavior

I expected the first template to work with no issues.

### Observed Behavior

The first template failed with error 
`Transform AWS::LanguageExtensions failed with: Condition layout is incorrect. Rollback requested by user.`

The second template worked with no issues.

### Test Cases

Parameters:
Use prod for Environment
Use string comma delimited values for pRepoARNs1 and prepoARNs2.
