### ISSUE TITLE
[AWS::Logs::MetricFilter] - [Enhancement] - Implement Hard Coded `Dimensions` Support for `match terms in unstructured log events`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1839]
### Name of the resource

AWS::Logs::MetricFilter

### Description

Currently it's not possible to do this:

```yaml
  LogGroupFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "?ERROR ?WARN"
      LogGroupName: !Ref <LogGroup>
      MetricTransformations:
        - MetricNamespace: "MetricFilter"
          MetricName: "Log Error / Warning"
          Dimensions:
            - Key: "ClusterName"
              Value: !Ref <ECSCluster>
            - Key: "ServiceName"
              Value: !GetAtt <ECSService.Name>
          MetricValue: 1
          Unit: "Count"
```

CloudFormation Error message:

```
Resource handler returned message: "Invalid request provided: AWS::Logs::MetricFilter.
The specified filter pattern does not support dimensions
(Service: CloudWatchLogs, Status Code: 400, Request ID: <RequestID>)"
(RequestToken: <RequestToken>, HandlerErrorCode: InvalidRequest)
```

I am not entirely sure why this limitation exists, but it doesn't make any sense. This works:

```yaml
  LogGroupFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "?ERROR ?WARN"
      LogGroupName: !Ref LogGroup
      MetricTransformations:
        - MetricNamespace: "MetricFilter"
          MetricName: "Log Error / Warning"
          MetricValue: 1
          Unit: "Count"
```

### Other Details

You are able to create Custom Metrics with, for example, Python and nobody is complaining about **hard coding** `Dimensions`. So i don't really get why this doesn't work.
