### ISSUE TITLE
"Template error: resource HostedZone does not support attribute type Id in Fn::GetAtt" in Melbourne region

### ISSUE THREAD

**Issue by adenot** [aws-cloudformation/cloudformation-coverage-roadmap#1865]
### Name of the resource

AWS::Route53::HostedZone

### Issue Description

Simple template with a Route53::HostedZone and outputs the HostedZone ID.

Works in us-east-1 and other regions, but in ap-southeast-4 (melbourne), returns an error:

> Template error: resource HostedZone does not support attribute type Id in Fn::GetAtt

Template for testing:
```
AWSTemplateFormatVersion: "2010-09-09"
Description: "Domain (Hosted Zone) for Workload Account (rev:1)"

Parameters:
  HostedZoneName:
    Type: String
    Description: Name of hosted zone domain

Resources:
  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref HostedZoneName

Outputs:
  HostedZone:
    Description: HostedZone Id
    Value: !GetAtt HostedZone.Id
  HostedZoneNameServers:
    Description: HostedZone Name Servers
    Value: !Join [ ",", !GetAtt HostedZone.NameServers]
```

### Expected Behavior

CloudFormation should be consistent across regions (except for when a resource is not available).

Expected that GetAtt HostedName.Id is recognized and returns the correct result, as per documentation.

### Observed Behavior

> Template error: resource HostedZone does not support attribute type Id in Fn::GetAtt

### Test Cases

Using the AWS Console, create a new stack in ap-southeast-4 (melbourne) and use the template from the Issue Description.

In other regions (tested on us-east-1, ap-southeast-2, us-east-2, us-west-2, ap-southeast-1), works ok.
