### ISSUE TITLE
Supported resource AWS::EC2::VPCGatewayAttachment can't be imported to stack

### ISSUE THREAD

**Issue by AlexGurtoff** [aws-cloudformation/cloudformation-coverage-roadmap#1869]
### Name of the resource

Other

### Resource Name

AWS::EC2::VPCGatewayAttachment

### Issue Description

Existing resource AWS::EC2::VPCGatewayAttachment can't be imported to stack. There is a weird error with such description:
`READ operation is not supported`  
<img width="583" alt="image" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/11095842/df724da4-0805-46f5-997c-30eae94e55ef">

### Expected Behavior

Reffering to:
https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/supported-resources.html
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/11095842/6a5331b4-9175-43cc-a243-0eb8bbfe9a5d)
and
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/11095842/80bd0d04-fd49-4b5e-964c-2c06d8a23a33)
Resource is supported by import. So, I should be able to import this resource into my cloudformation stack.

### Observed Behavior

Existing resource AWS::EC2::VPCGatewayAttachment can't be imported to stack. There is a weird error with such description:
`READ operation is not supported`  
<img width="583" alt="image" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/11095842/df724da4-0805-46f5-997c-30eae94e55ef">

### Test Cases

I used such template file to import this resource:
```
Resources:
...
  VpcVPCGWBF912B6E:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: VpcIGWD7BA715C
      VpcId:
        Ref: Vpc8378EB38
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CommonVpcStack/Vpc/VPCGW
...
```
And here is the import.json file that I provide with the template when creating a change set:
```
...
{
    "ResourceType":"AWS::EC2::VPCGatewayAttachment",
    "LogicalResourceId":"VpcVPCGWBF912B6E",
    "ResourceIdentifier": {
        "AttachmentType":"IGW",
        "VpcId":"vpc-xxxxxxxxxxxxxxxxx"
    }
},
...
```
I removed redundant information from it
