### ISSUE TITLE
Add the ability to specify Placement group name

### ISSUE THREAD

**Issue by NdemeraS** [aws-cloudformation/cloudformation-coverage-roadmap#1877]
### Name of the resource

AWS::EC2::PlacementGroup

### Issue Description

Currently, CloudFormation automatically generates a name for the Placement Group created with this resource.  The API has the option to manually select the name

### Expected Behavior

Resource should have a "Name" parameter to allow for the manual selection of the placement group name

### Observed Behavior

Current the parameter as not been added

### Test Cases

n/a

**Comment by bradlee-wilson-aws** [comment]
The ability exists today, there appears to be a miss in updating the documentation. This works:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  PlacementGroup:
    Type: AWS::EC2::PlacementGroup
    Properties:
      Strategy: cluster
      GroupName: MyPlacementGroup
```

Documentation will be updated. The ability required in this request is there, and the issue be closed. We are tracking the document update internally.
