### ISSUE TITLE
AWS::EFS::MountTarget - Stack Tags not recognized by drift detection 

### ISSUE THREAD

**Issue by ruchirshetye-aws** [aws-cloudformation/cloudformation-coverage-roadmap#1885]
### Name of the resource

AWS::EFS::MountTarget

### Issue Description

AWS::EFS::MountTarget is reporting false positive drift when Stack level tags is added. 

### Expected Behavior

The resource "AWS::EFS::MountTarget" should show IN_SYNC and should consider Stack Level Tags in drift detection. 

### Observed Behavior

Resource drift status: MODIFIED when stack tags are added. 

### Test Cases

Deploy the below template and then update the stack with the Stack Level Tag. 
```
Resources:
  AccessPointResource:
    Type: 'AWS::EFS::AccessPoint'
    Properties:
      FileSystemId: fs-abc12345 #Add a FileSystem ID
      AccessPointTags:
          - Key: "keyname1"
            Value: "value1"
          - Key: "keyname2"
            Value: "value2"
      PosixUser:
        Uid: "13234"
        Gid: "1322"
        SecondaryGids:
          - "1344"
          - "1452"
      RootDirectory:
        CreationInfo:
          OwnerGid: "708798"
          OwnerUid: "7987987"
          Permissions: "0755"
        Path: "/testcfn/abc"
```

The Resource drift status will be MODIFIED
