### ISSUE TITLE
AWS::Organizations::Organization - Allow Enabling or Disabling Policy types

### ISSUE THREAD

**Issue by mattyboy84** [aws-cloudformation/cloudformation-coverage-roadmap#1901]
### Name of the resource

Other

### Resource name

AWS::Organizations::Organization

### Description

As a cloudformation user i want to be able to control what policies are enabled at an Organisation level using cloudformation.
Currently the `AWS::Organizations::Organization` resource only supports one parameter, FeatureSet. regardless of what this is set to when the Org is created all the Policies are `Disabled` are default.
This Template
```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  organisation:
    Type: AWS::Organizations::Organization
    Properties:
      FeatureSet: ALL
```
Creates this Org:
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/41299838/0e957d51-ca43-4fc4-9a11-65cff03e9436)

I would suggest new supported parameters like
```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  organisation:
    Type: AWS::Organizations::Organization
    Properties:
      FeatureSet: ALL
      AIServicesOptOut: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
      BackupPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
      ServiceControlPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
      TagPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
```
or a new `Policies` object to contain them.
```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  organisation:
    Type: AWS::Organizations::Organization
    Properties:
      FeatureSet: ALL
      Policies:
        AIServicesOptOut: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
        BackupPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
        ServiceControlPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
        TagPolicies: ENABLED # Can be ENABLED or DISABLED. Defaults to DISABLED
```

Under the hood, this would call [enable-policy-type](https://docs.aws.amazon.com/cli/latest/reference/organizations/enable-policy-type.html)
E.g. 
aws organizations enable-policy-type --root-id `root-id` --policy-type `policy-type`
where policy-type can be:
`AISERVICES_OPT_OUT_POLICY`, `BACKUP_POLICY`, `SERVICE_CONTROL_POLICY` or `TAG_POLICY` which corresponds to the requested parameters
