### ISSUE TITLE
AWS::MediaPackageV2::Channel return value "IngestEndpoints" not accessible

### ISSUE THREAD

**Issue by SuryaTeja18** [aws-cloudformation/cloudformation-coverage-roadmap#1902]
### Name of the resource

Other

### Resource Name

AWS::MediaPackageV2::Channel

### Issue Description

Created a stack with sample template as below:
```
Resources:
 Channel:
  DeletionPolicy: Retain
  Type: AWS::MediaPackageV2::Channel
  Properties:
   ChannelName: "mychannel1"
   ChannelGroupName: "channelgrp"
```

added outputs in different combinations, all of them threw error "Template format error: Every Value member must be a string."

example:
```
1.
Outputs:
 Ingests:
  Value: !GetAtt Channel.IngestEndpoints

2.
Outputs:
 Ingests:
  Value: !Select [0, !GetAtt Channel.IngestEndpoints]
```

### Expected Behavior

Ingest endpoints either having separate return values as endpoint1, endpoint2 or returning a list of two strings so that users can parse it using !Select and access the values.

### Observed Behavior

The format of the output object currently when trying to access !GetAtt <ChannelLogicalid>.IngestEndpoints is unknown. This is a potential bug that needs to be addressed and fixed so that users would be able to make use of this return value elsewhere in the template/other resources, etc.

### Test Cases

Steps to replicate the issue:
- create a sample channel (v2)
- then update the stack to add outputs trying to access [ingest endpoint] value and observe the error. 

[ingest endpoint]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackagev2-channel.html#aws-resource-mediapackagev2-channel-return-values:~:text=of%20the%20channel.-,IngestEndpoints,-The%20ingest%20endpoints
