### ISSUE TITLE
AWS CloudFormation 'package' support for AWS::KinesisAnalyticsV2::Application

### ISSUE THREAD

**Issue by cmogeni** [aws-cloudformation/cloudformation-coverage-roadmap#1904]
### Name of the resource

AWS::KinesisAnalyticsV2::Application

### Description

The `aws cloudformation package ` command should support packaging code in the `AWS::KinesisAnalyticsV2::Application`, for example the [package](https://awscli.amazonaws.com/v2/documentation/api/2.0.33/reference/cloudformation/package.html) command should covert the below resource from:

```
MyApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      RuntimeEnvironment: FLINK-1_15
      ServiceExecutionRole: !GetAtt ServiceExecutionRole.Arn
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent: ./index.py
          CodeContentType: 'PLAINTEXT'​

``` 
to the below after [packaging](https://awscli.amazonaws.com/v2/documentation/api/2.0.33/reference/cloudformation/package.html)
```
MyApplication:
    Type: AWS::KinesisAnalyticsV2::Application
    Properties:
      RuntimeEnvironment: FLINK-1_15
      ServiceExecutionRole: !GetAtt ServiceExecutionRole.Arn
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: arn:aws:s3:::testusecasecxxxx
              FileKey: a059a71a55e13083f3fc510fc1050bd2
          CodeContentType: 'ZIPFILE'
​

``` 
This should work in a similar way to the `AWS::Lambda::Function` resource
