### ISSUE TITLE
[AWS::Signer::SigningProfile] Need the ability to define a custom profile name

### ISSUE THREAD

**Issue by bartleboeuf** [aws-cloudformation/cloudformation-coverage-roadmap#1911]
### Name of the resource

AWS::Signer::SigningProfile

### Description

The signing profile resource must allow the signing profile name to be specified. For some use cases and corporate naming conventions, we need to be able to specify the profile name.

**Comment by aparnard3** [comment]
@bartleboeuf , You will be able to provide the custom signing profile name and create a SigningProfile using cloudformatiom template type AWS::Signer::SigningProfile like below example:

```
Resources:
  TestProfile:
    Type: AWS::Signer::SigningProfile
    Properties:
      ProfileName: "YourCustomProfileName"
      PlatformId: "platformid"
```
