### ISSUE TITLE
AWS::ElastiCache::ParameterGroup missing automatic tags (regression)

### ISSUE THREAD

**Issue by samuelstuetz** [aws-cloudformation/cloudformation-coverage-roadmap#1926]
### Name of the resource

AWS::ElastiCache::ParameterGroup

### Issue Description

Until last week 16 feb we created a stack with (ReplicationGroup, ParamGroup, ...) and a set of tags.
Since this week the paramgroup naming has slightly changed and there is no tags to the created resource.

- tag based policy is broken
- resource (ParamGroup) is not cleanup on delete as it does not seem to belong to the cloudformation stack
- this issue is new and wasn't not here only days ago

### Expected Behavior

When cloudformation creates resources it should add all the tags to it.

### Observed Behavior

It still adds the tags to all other resources in the Stack as before, but not the ParamGroup.
ParamGroup resource is still listed in the Stack as a resource belonging to it.

### Test Cases

Create ParamGroup such as in the console (UI) with just this template.
```
AWSTemplateFormatVersion: "2010-09-09"
Description: Test
Resources:
  TestPGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis7
      Properties:
        maxmemory-policy: "allkeys-lru"
        reserved-memory-percent: "10"
      Description: "group which should be tagged"
```
add any set of tags e.g. { "myTag":"MyValue"}
