### ISSUE TITLE
AWS::Elasticsearch::Domain resources do not receive stack level tags

### ISSUE THREAD

**Issue by miguel-aws** [aws-cloudformation/cloudformation-coverage-roadmap#1959]
### Name of the resource

AWS::Elasticsearch::Domain

### Resource Name

AWS::Elasticsearch::Domain

### Issue Description

When providing the CloudFormation stack with tags, AWS::Elasticsearch::Domain resources do not get tagged with stack-level tags.

### Expected Behavior

AWS::Elasticsearch::Domain resources get tagged with stack-level tags.

### Observed Behavior

AWS::Elasticsearch::Domain resources do not get tagged with stack-level tags. However, they get tagged with resource level tags.

### Test Cases

Resource-level tagging:

```
  Resources:
      ElasticSearchDomain:
          Type: AWS::Elasticsearch::Domain
          Properties:
              ElasticsearchVersion: "7.10"
              EBSOptions:
                  EBSEnabled: true
                  Iops: 1200
                  VolumeSize: 75
                  VolumeType: io1
              Tags:
                  -   Key: resource
                      Value: my-es
          UpdatePolicy:
              EnableVersionUpgrade: true
```
