### ISSUE TITLE
Timestream for InfluxDB in missing CloudFormation support

### ISSUE THREAD

**Issue by sentros** [aws-cloudformation/cloudformation-coverage-roadmap#1968]
### Name of the resource

AWS::Timestream::Database

### Description

It's now possible to select a different engine for a timestream database in the aws console. The previous engine is now called LiveAnalytics and a new engine was added called InfluxDB. Cloudformation has no support for the InfluxDB engine or for its configuration options.

### Other Details

https://aws.amazon.com/blogs/aws/run-and-manage-open-source-influxdb-databases-with-amazon-timestream/

**Comment by sentros** [comment]
Example of a cloudformation configuration could be as follows:

```yaml
TimestreamInfluxDB:
  Type: 'AWS::Timestream::Database'
  Properties:
    DatabaseName: db-name-example
    Engine: influxdb

    Username: example-username
    Password: example-password
    OrganizationName: example-org
    BucketName: example-bucket

    DBInstanceClass: db.influx.medium
    StorageType: included-3000
    AllocatedStorage: 200
    MultiAZ: true

    DBSubnetGroupName: !Ref DBSubnetGroupName
    VPCSecurityGroups:
      - !GetAtt TimestreamInfluxDBSG.GroupId
    PubliclyAccessible: false

    DBParameterGroupName: !Ref TimestreamInfluxDBParameterGroup
    S3LogsLocation: !Ref TimestreamInfluxDBBucket

    Tags:
      - Key: Name
        Value: 'db-name-example'

TimestreamInfluxDBParameterGroup:
  Type: 'AWS::Timestream::DBParameterGroup'
  Properties:
    DBParameterGroupName: example-name
    Description: example-description
    Parameters:
      flux-log-enabled: TRUE
      log-level: error
    Tags:
      - Key: Name
        Value: 'example-name'
```
