### ISSUE TITLE
(IaC generator) Generate templates with references to other resources in template without static values

### ISSUE THREAD

**Issue by mrlikl** [aws-cloudformation/cloudformation-coverage-roadmap#1977]
### Description

This FR is to enhance IaC generator to generate dynamic templates. At the moment, it is able to find associated resources, however the associated resources have static values. For example, a subnet in a VPC that are part of the same stack would look like - 

```
EC2VPC00vpc06afdfd27951d5dfe00uY5jW:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "172.31.0.0/16" 
EC2Subnet00subnet0df38eda3ce2e293300RjkIQ:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: "vpc-xxxxxxxxxxxx" <---- static vpc id
      MapPublicIpOnLaunch: false
      EnableDns64: false
      AvailabilityZoneId: "use1-az6"
      PrivateDnsNameOptionsOnLaunch:
        EnableResourceNameDnsARecord: false
        HostnameType: "ip-name"
        EnableResourceNameDnsAAAARecord: false
      CidrBlock: "172.31.96.0/19"
      Ipv6Native: false 
```

This makes the template useful to manage the resources, however generating a dynamic template that has a `!Ref EC2VPC00vpc06afdfd27951d5dfe00uY5jW` instead of VPC ID would benefit 

1. In redeploying the same stack in case of disaster where all the resources are deleted. 
2. Be able to use the same template across regions/ accounts to replicate resources. 

### Other Details

Atm, re-using this template would fail with resource not found errors for the ones that have static reference.
