### ISSUE TITLE
AWS::Cognito::IdentityPoolRoleAttachment -> RoleMappings | AWS::IAM::Role->AssumeRolePolicyDocument->Conditions dynamic keys

### ISSUE THREAD

**Issue by fimbulvetr** [aws-cloudformation/cloudformation-coverage-roadmap#198]
# Description
Currently, it is impossible to specify a Left Hand value (read: Key) as a !Ref or !Sub. It is possible in a handful of places if one the parents of said Left Hand key can take a a pre-stringified JSON document. This workaround comes at a cost - 

1. Tools such as cdk or troposphere or any home grown solutions cannot natively use such workarounds.
2. You need to be a CF expert to know/explain this
3. You lose native object representation of the value you are attempting to declare because you have to resort to stringifying it.

# Expected behavior:
I should be able to write:
```
Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                Fn::Sub:
---->            "${oidcProvider.Url}:sub":
                    Fn::Sub:
                      "system:serviceaccount:default:my-serviceaccount"
            Effect: Allow
            Principal:
              Federated: ${oidcProvider.Arn}
        Version: "2012-10-17"
```

This should evaluate to:

```
Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "oidc.eks.us-west-2.amazonaws.com/id/abc123":"system:serviceaccount:default:my-serviceaccount"
            Effect: Allow
            Principal:
              Federated: "arn:aws:iam::12345:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/abc123"
        Version: "2012-10-17"
```

# Workaround

There is a workaround documented here: https://forums.aws.amazon.com/message.jspa?messageID=783626#917611

but it only works because `AssumeRolePolicyDocument` on an IAM policy can take a stringified JSON object in lieu of a literal json object. This allows CF templating to string replace tokens.

Thanks to the person that found that BTW.

Example of workaround:

```
Resources:
  MyIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument: !Sub |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "${oidcProvider.Arn}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "${oidcProvider.Url}:sub": "system:serviceaccount:default:my-serviceaccount"
                  }
                }
              }
            ]
          }
```
Notice that it's no longer a JSON object per se, which means that you lose features of your editor, linters, etc. etc.
![image](https://user-images.githubusercontent.com/253243/65801717-fec02680-e136-11e9-86aa-a4ad3c066d26.png)

# Additional context

This is needed by the new EKS IAM fine-grained roles feature: https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/

As well as Cognito's RoleMappings and possibly several other areas - anywhere there is a Key that needs to dynamically resolved.
