### ISSUE TITLE
AWS::InternetMonitor::Monitor initial `INACTIVE` status is not considered

### ISSUE THREAD

**Issue by yvele** [aws-cloudformation/cloudformation-coverage-roadmap#1985]
### Name of the resource

Other

### Resource Name

AWS::InternetMonitor::Monitor

### Issue Description

When creating a new CloudWatch Internet Monitor with an `INACTIVE` status:

```yaml
InternetMonitor:
  Type: AWS::InternetMonitor::Monitor
  Properties:
    MonitorName: Test
    Status: INACTIVE
```

the resource is created as active despite that fact that I asked for an `INACTIVE` one:

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/4225430/77fa0156-9e18-4c65-a859-75e63eee815d)

The [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-internetmonitor-monitor.html#cfn-internetmonitor-monitor-status) says that:

> The status of a monitor. The accepted values that you can specify for Status are `ACTIVE` and `INACTIVE`.

It's probably because during creation the status starts as `PENDING`. But I still need the ability to create the monitor as `INACTIVE`.

### Expected Behavior

When creating a new CloudWatch Internet Monitor with an `INACTIVE` status:

```yaml
InternetMonitor:
  Type: AWS::InternetMonitor::Monitor
  Properties:
    MonitorName: Test
    Status: INACTIVE
```

the created resource SHOULD be `INACTIVE`:

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/4225430/29e13408-dd4c-40d3-a56e-55449aa9d937)

### Observed Behavior

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/4225430/a5cd1e4a-cda5-4d80-8650-a01aed5c608d)

### Test Cases

Just create any new `AWS::InternetMonitor::Monitor` with initial `Status: INACTIVE`.

### Other Details

Please note that, upon updating any property other than `Status` at a later time (for example, `MaxCityNetworksToMonitor`), the status unexpectedly becomes inactive, despite not modifying the initial `Status: INACTIVE` property. 🤔

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/4225430/1f541dc5-8c1f-48da-aa72-56d8b07245fc)

Also please fix the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-internetmonitor-monitor.html#cfn-internetmonitor-monitor-status

```diff
- Allowed values: PENDING | ACTIVE | INACTIVE | ERROR
+ Allowed values: ACTIVE | INACTIVE
```
