### ISSUE TITLE
AWS::FSx::FileSystem - Add GetAtt for DNSName and IP address for ONTAP File System.

### ISSUE THREAD

**Issue by sbtiac** [aws-cloudformation/cloudformation-coverage-roadmap#1989]
### Name of the resource

AWS::FSx::FileSystem

### Description

Title : Add GetAtt for DNSName and IP address for ONTAP File System.

Cloudformation ,currently, supports only Windows Filesystems to retrieve `DNSNam` using GetAtt Intrinsic Function per this [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html#aws-resource-fsx-filesystem-return-values)

DNSName
Returns the FSx for Windows file system's DNSName.

```
Outputs:
  FSxPublicDNS:
    Description: 'DNS Name of FSx'
    Value: !GetAtt FSxFileSystem.DNSName
```

Request:

- Include `ONTAP` File System support to retrieve DNSName 
- Add `IPAddress` attribute to retrieve `Management Endpoint - IP address`  of an ONTAP File System.
