### ISSUE TITLE
AWS::EKS::Cluster ClusterLogging

### ISSUE THREAD

**Issue by ueokande** [aws-cloudformation/cloudformation-coverage-roadmap#208]
## 1. Title

AWS::EKS::Cluster ClusterLogging

## 2. Scope of request 
   c) new attribute for an existing resource is desired 

## 3. Expected behavior

Allow users to manage cluster logging on EKS cluster via CloudFormation.

Currently, the cluster logging is disabled on EKS by default.  The EKS officially supports via *API*, but CloudFormation doesn't.  CloudFormation should also supports managements of the clouster logging.

The type of the cluster loggings are "api", "audit", "authenticator", "controllerManager" and "scheduler".  The API can enable or disable such types of logging.  The resource template should be able to enable and disable certain log types.

The stack template is described in *declarative* format.  The given types of the logging will be enabled by Cfn, and non-given types will be disabled on updating the stack. Here is an example:

```yaml
MyEksCluster:
  Type: "AWS::EKS::Cluster"
  Properties:
    # Enable "api", "audit", and "authenticator" logging
    ClusterLoggingEnabled:
      - "api"
      - "audit"
      - "authenticator"

```

If the `ClusterLoggingEnabled` field is missing or empty, no types are enabled.

## 4. Suggest specific test cases

Create a stack with `AWS::EKS::Cluster` and  `ClusterLoggingEnabled` field, the stack creates EKS cluster configured cluster logging.  On updating a stack with `ClusterLoggingEnabled`, given log types are enabled and missing log types are disabled.

If the `ClusterLoggingEnabled` field is not given,  all of log types are disabled.

## 5. Helpful Links to speed up research and evaluation

API Document of cluster logging on EKS:
https://docs.aws.amazon.com/eks/latest/APIReference/API_Logging.html
https://docs.aws.amazon.com/eks/latest/APIReference/API_LogSetup.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Compute ( EKS )

## 7. Any additional context (optional)
