### ISSUE TITLE
AWS::ElastiCache::ReplicationGroup - add reader endpoint output

### ISSUE THREAD

**Issue by JimSpriggs** [aws-cloudformation/cloudformation-coverage-roadmap#210]
## Scope of request 
AWS::ElastiCache::ReplicationGroup supports return values of PrimaryEndPoint.Address and PrimaryEndPoint.Port and ReadEndPoint.Addresses and ReadEndPoint.Ports, but does not include a return value enabling access to the newly-introduced ReaderEndpoint feature for Redis.

Please add the ReaderEndpoint.Address and ReaderEndpoint.Port to the outputs (return values) of AWS::ElastiCache::ReplicationGroup.

## Expected behavior

Example ElastiCache Redis cluster: vev2crbghjephpi2
Example currently-supported PrimaryEndPoint.Address: vev2crbghjephpi2.ubzxam.ng.0001.euw1.cache.amazonaws.com:6379
Example required ReaderEndPoint.Address:
vev2crbghjephpi2-ro.ubzxam.ng.0001.euw1.cache.amazonaws.com:6379

## Helpful Links to speed up research and evaluation

Existing API docs (with no mention of reader end point): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html

Announcement of new reader endpoint feature for Redis:
https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-elasticache-launches-reader-endpoint-for-redis/

## Category
DB (ElastiCache redis)

## Additional Context
It is not sufficient to use the existing ReadEndpoint.Addresses, as this returns a list of read-only endpoints, and an endpoint must then be chosen programmatically.  The ReaderEndPoint which was introduced in June 2019 automatically splits incoming connections across all read replicas, enabling read-only clients to manage only a single endpoint address.

Based on the values observed so far, it is possible to derive the reader endpoint address value, but if this name format were to change in future it would break any automation based on the format.

Outputting the ReaderEndPoint will enable reliable automation.

**Comment by jamesmcminn96** [comment]
I've come up with a really horrible pure Cloudformation work around for this for anyone that comes across this issue. This pattern doesn't work with elasticache replication groups with encryption at rest enabled, but can likely be changed to suit.

```
Outputs:
  CacheReaderEndpoint:
    Description: Elasticache reader endpoint derived from the primary endpoint
    Value: !Sub
      - ${Part0}-ro.${Part1}.${Part2}.${Part3}.${Part4}.${Part5}.${Part6}.${Part7}
      - Part0: !Select [0, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part1: !Select [1, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part2: !Select [2, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part3: !Select [3, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part4: !Select [4, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part5: !Select [5, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part6: !Select [6, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
        Part7: !Select [7, !Split [ ".", !GetAtt ElasticCacheReplicationGroup.PrimaryEndPoint.Address ]]
```

**Comment by chrisandrewcl** [comment]
I've found this issue while investigating why Redis.ReadEndPoint.Addresses.List is returning a list including the primary endpoint while the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#aws-resource-elasticache-replicationgroup-return-values) say it should only include read-only replicas.

While I didn't find an answer to this, I decided to try getting ReaderEndPoint.Address/Port and, to my surprise, it worked!

It seems the docs are outdated and this issue can now be closed.

**Comment by sormy** [comment]
Another workaround (easier) but it relies on expected replication group ID that is prefixed to DNS (in this example it is `rediscache`):

```yml
        Fn::Sub:
            - '${Host}.${Domain}'
            - Host: 'rediscache-ro'
              Domain: !Select [1, !Split ['rediscache.', !GetAtt RedisCacheCluster.PrimaryEndPoint.Address]]
```
