### ISSUE TITLE
AWS::Cognito::UserPoolClient - ReadAttributes has no effect

### ISSUE THREAD

**Issue by iconara** [aws-cloudformation/cloudformation-coverage-roadmap#214]
## Expected behavior

When I set `ReadAttributes` I expect the read attributes of the user pool client to be set, but they are not. This property does not seem to have any effect. There seems to be no effect when creating, nor updating.

## Suggest specific test cases

With this CFN resource:

```
SomeClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: my-client
    GenerateSecret: false
    UserPoolId: !Ref UserPool
    ReadAttributes:
      - email
```

I expect the following command to return `["email"]`

```
aws cognito-idp describe-user-pool-client --user-pool-id … --client-id … --region … --query UserPoolClient.ReadAttributes
```
