### ISSUE TITLE
AWS::Cognito::UserPool - Schema should only allow string or number attributes

### ISSUE THREAD

**Issue by JacobParis** [aws-cloudformation/cloudformation-coverage-roadmap#348]
CloudFormation allows us to create custom attributes that are Boolean, instead of restricting them to string or numbers which are the only supported values as per [the docs](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-custom-attributes)

```yml
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: user-pool
      Schema:
        - Name: string-attribute
           AttributeDataType: String # This is valid as custom attributes can be strings
           Mutable: false
        - Name: number-attribute
           AttributeDataType: Number # This is valid as custom attributes can be numbers
           Mutable: false
        - Name: boolean-attribute
           AttributeDataType: Boolean # This should fail as custom attributes cannot be Booleans
           Mutable: false
```

Creating a user pool with a boolean succeeds via cloudformation, but users cannot be assigned boolean custom attributes.

Attempting to do this should cause the stack deploy to fail

Screenshot of web console with Boolean attribute created via cloudformation

![Screen Shot 2020-01-17 at 9 55 12 AM](https://user-images.githubusercontent.com/5633704/72621663-b445fe00-390f-11ea-83e0-c943b33efa0a.png)

Screenshot of **add custom attribute** form in the web console

![Screen Shot 2020-01-17 at 9 55 18 AM](https://user-images.githubusercontent.com/5633704/72621831-038c2e80-3910-11ea-95ad-fb7d061eda96.png)

Category: Security, Identity, Compliance (Cognito)
