### ISSUE TITLE
AWS::SSM::Parameter and AWS::SSM::MaintenanceWindowTask GovCloud

### ISSUE THREAD

**Issue by bgardner-noggin** [aws-cloudformation/cloudformation-coverage-roadmap#404]
## 2. Scope of request 
Should be able to use AWS::SSM::Parameter and AWS::SSM::MaintenanceWindowTask in GovCloud regions

## 3. Expected behavior

In GovCloud, using either of these resource types errors with "resource type not available"

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

5. Management (CloudTrail, Config...)

**Comment by PatMyron** [comment]
minimal [`AWS::SSM::Parameter`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html) template for testing:
```yaml
Resources:
  Parameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: Value
```
