### ISSUE TITLE
AWS::FSx::FileSystem - Add GetAtt for DNSName

### ISSUE THREAD

**Issue by vsarago** [aws-cloudformation/cloudformation-coverage-roadmap#446]
## 1. Title 
`AWS::FSx::FileSystem` - DNSName accesible via Fn::GetAtt

## 2. Scope of request 
Make the DNSName accessible using `Fn::GetAtt` on an `AWS::FSx::FileSystem` resource. Currently it only supports Ref: File system ID as outputs

```
Outputs:
  FSxPublicDNS:
    Description: 'DNS Name of FSx'
    Value: !GetAtt FSxFileSystem.DNSName
```

## 3. Expected behavior
Get back the DNS name created for the `AWS::FSx::FileSystem` resource, e.g. amznfsx1oeyrhui.corp.test.com

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html

Current list of supported Ref/GetAtt parmaters: https://theburningmonk.com/cloudformation-ref-and-getatt-cheatsheet/

## 6. Category (required) 

Storage (S3, EFS, Backup, FSx)
