### ISSUE TITLE
AWS::ApiGatewayV2::Model - Name (expose via !GetAtt)

### ISSUE THREAD

**Issue by bjorg** [aws-cloudformation/cloudformation-coverage-roadmap#452]
## 2. Scope of request 
Ability to retrieve the `Name` attribute from a `AWS::ApiGatewayV2::Model` resource. This alleviates the need to create an explicit dependency when using it with a `AWS::ApiGatewayV2::Route` resource.

Samples: 
#### With !GetAtt support
```yaml
ServerFunctionStartRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref ModuleWebSocket
    RouteKey: start
    RequestModels:
      default: !GetAtt RequestModel.Name

RequestModel:
  Type: AWS::ApiGatewayV2::Model
  Properties:
    Name: ServerFunctionStartRouteRequestModel
```

#### Without !GetAtt support (current behavior)
```yaml
StartRoute:
  Type: AWS::ApiGatewayV2::Route
  Properties:
    ApiId: !Ref ModuleWebSocket
    RouteKey: start
    RequestModels:
      default: ServerFunctionStartRouteRequestModel
  DependsOn:
    - RequestModel

RequestModel:
  Type: AWS::ApiGatewayV2::Model
  Properties:
    Name: ServerFunctionStartRouteRequestModel
```

## 3. Expected behavior
By using `!GetAtt`, CloudFormation can automatically track the dependencies between `AWS::ApiGatewayV2::Route` and  `AWS::ApiGatewayV2::Model` resources. Without it, the developer has to explicitly manage these.

## 4. Suggest specific test cases
See sample above.
