### ISSUE TITLE
AWS::CodeDeploy::DeploymentGroup - DeploymentType Support BLUE_GREEN for ECS/Fargate for CICD use cases and Codepipeline integration

### ISSUE THREAD

**Issue by zzenonn** [aws-cloudformation/cloudformation-coverage-roadmap#483]
1. Title -> AWS::CodeDeploy::DeploymentGroup-DeploymentType
2. Scope of request -> AWS::CodeDeploy::DeploymentGroup-DeploymentType supports BLUE_GREEN for Lambda but not for ECS/Fargate.
3. Expected behavior -> BlueGreen deployments for ECS/Fargate services.
4. Links to existing API doc (optional) 

> Announcement: https://aws.amazon.com/blogs/devops/use-aws-codedeploy-to-implement-blue-green-deployments-for-aws-fargate-and-amazon-ecs/
> Announcement: https://aws.amazon.com/about-aws/whats-new/2020/05/aws-cloudformation-now-supports-blue-green-deployments-for-amazon-ecs/

5. Category tag (optional) -> Compute, Developer Tools
6. Any additional context (optional) -> Similar request as #37 however #37 was closed because of the announcement referenced above. The use case I want to reference is to explicitly have a BLUE_GREEN deployment type for ECS as a CodeDeploy::DeploymentGroup-DeploymentType to integrate with CICD (e.g. Codepipeline integration)

**Comment by sethstone** [comment]
I'm looking for the same capability as @zzenonn.   

I'm able to build out all necessary resources for a BlueGreen ECS CICD pipeline using Cloudformation except I must create the Deployment Group using the CLI.  I've attempted to derive the correct syntax from a working CLI command (see below), but when I try to run it as part of a stack deploy I get: "Encountered unsupported property BlueGreenDeploymentConfiguration".


```
 DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      ApplicationName: !Ref CodeDeployApplication
      AutoRollbackConfiguration: 
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      BlueGreenDeploymentConfiguration: 
        DeploymentReadyOption: 
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentGroupName: !Ref CodeDeployDeploymentGroupName
      DeploymentStyle: 
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN
      LoadBalancerInfo: 
        TargetGroupPairInfoList: 
          TargetGroups:
            - Name: !Sub ${ProjectPrefix}-tg1
            - Name: !Sub ${ProjectPrefix}-tg2
          ProdTrafficRoute: 
            ListenerArns: !Ref ALBProductionListener
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      ECSServices:
        - ServiceName: !Sub ${ProjectPrefix}-service
        - ClusterName: !Sub ${ProjectPrefix}-ecs-fargate-cluster
```

**Comment by hupe1980** [comment]
I created such a setup with custom resources and aws-cdk. The challenge was that the service had to be available when a DeploymentGroup was created, but that future control over updates to the taskdefinition should be done with CodeDeploy.


You can see an example here:
https://github.com/cloudcomponents/cdk-constructs/blob/master/examples/blue-green-container-deployment-example/src/blue-green-container-deployment-stack.ts

**Comment by cappellaiomatto** [comment]
Yep, I stumbled upon this. The accepted JSON via CLI cannot be converted to a working cloudformation template.
The (puzzling) error messages are either:
*) "Property LoadBalancerInfo cannot be specified"
or
*) "ec2TagFilters can not be specified"
Looking forward to a solution

**Comment by caJaeger** [comment]
Was sent by AWS support to add pressure to this open issue. This is very much needed.

**Comment by jtaylormayfield** [comment]
I am also looking at implementing a set of CodePipeline templates in CloudFormation that will require some manual process or extra scripting to accomplish this part of the automation. Please update this service.

**Comment by thomasstep** [comment]
I am also here to add pressure to this.

**Comment by benbridts** [comment]
The best way to add pressure is to use the 👍 on the original issue (and/or reach out to your TAM or Account Team if you have/know them).
That way it's actually measurable by AWS

**Comment by chathurilanchana** [comment]
Really looking forward for a solution to this issue. We share load balancer between multiple services, and use imports and nested stacks extensively. So we cant really get the benefits of Blue green cloudformation deploys with its current limitations.

**Comment by pablods90** [comment]
Hello,

This feature is really required. There are limitations in the [current scenario](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html#blue-green-considerations), that make the solution not usable for relatively complex scenarios.

Also, there are two concerning issues:
- There are (apparently) random failures and inconsistencies when [referencing parameters from the Task Definition or the Task set](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/37#issuecomment-718158785).
- Capacity Providers are not currently supported via CloudFormation for the [Task Set resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskset.html). This is unfortunate, as the [Capacity Provider Strategy parameter](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateTaskSet.html#ECS-CreateTaskSet-request-capacityProviderStrategy) is present in the API call. This limits the option, as many use cases require using Capacity Providers.

Thanks!

**Comment by mbidewell** [comment]
Would like this as well.  Unless I am misreading the documentation, its seems that, unlike an appspec CodeDeploy deployment which you specify the new details only, the CFN method requires the full specification of both the Blue and Green setups.  This makes it far more complex than an Appspec deploy.

**Comment by yogeshjoshi** [comment]
There are couple of limitations, which preventing us to choose Blue Green for our ECS Stack.
We have LB Defined in Infra Package and shares between services. We would need Import Resources as it's basic to choose Cloudformation Implementation.

- Declaring output values or importing values from other stacks is not currently supported for templates defining blue/green ECS deployments.
- You cannot use the AWS::CodeDeploy::BlueGreen hook in a template that includes nested stack resources.
- You cannot use the AWS::CodeDeploy::BlueGreen hook in a nested stack.

Are there plans / work in progress to handle these use cases?

**Comment by yogeshjoshi** [comment]
@rohits-spec Document still says Importing values and importing from other stack is not supported and nested stack problem still persist.

We are following this problem from so many issues but always issue marked as closed, do you want to create new issue for same or should we reopen this.

**Comment by zzenonn** [comment]
@rohits-spec I wrote this issue referencing that exact feature. The feature closed #37 but I don't think it closes this one. Specifically, this covers several other use cases. If needed, we can create a new issue, but a lot of the feedback is documented here.

**Comment by rohits-spec** [comment]
Reopening this issue to address various usecases mentioned in this issue.

**Comment by Nestor10** [comment]
@rohits-spec noticed this is still listed as shipped in the coverage road map. Is this complete but waiting for release?

**Comment by ashwallace** [comment]
How close is this to launch? it has been on roadmap now for 6 months. I want to retire workarounds.

**Comment by corey-cole** [comment]
> How close is this to launch? it has been on roadmap now for 6 months. I want to retire workarounds.

I *just* tested this and it worked for an account in us-west-2.

**Comment by sethstone** [comment]
Great to hear that this is working @corey-cole.  I just tested in us-east-1 as well and I was able to deploy my CFN stack with the DeploymentGroup successfully.  I'm not sure if this means the overall issue is resolved or if there's more nuance that I'm not encountering.  I wonder if @zzenonn could re-test from his end.

Here's my working CFN example:

```
 DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties: 
      ApplicationName: !Ref CodeDeployApplication
      AutoRollbackConfiguration: 
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      BlueGreenDeploymentConfiguration: 
        DeploymentReadyOption: 
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentGroupName: !Ref CodeDeployDeploymentGroupName
      DeploymentStyle: 
        DeploymentOption: WITH_TRAFFIC_CONTROL
        DeploymentType: BLUE_GREEN
      LoadBalancerInfo: 
        TargetGroupPairInfoList: 
          - TargetGroups:
              - Name: !Sub ${ProjectPrefix}-tg1
              - Name: !Sub ${ProjectPrefix}-tg2
            ProdTrafficRoute: 
              ListenerArns:
                - Fn::ImportValue: !Sub ${ProjectPrefix}-ecs:ALBProductionListener
            TestTrafficRoute: 
              ListenerArns:
                - Fn::ImportValue: !Sub ${ProjectPrefix}-ecs:ALBTestListener
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      ECSServices:
        - ClusterName:
            Fn::ImportValue: !Sub ${ProjectPrefix}-ecs:ClusterName
          ServiceName:
            Fn::ImportValue: !Sub ${ProjectPrefix}-ecs:ServiceName
```

This is really exciting to see working -- I hope this example is helpful.
