### ISSUE TITLE
AWS::Cognito::UserPool - GetAtt returns incorrect partition for Arn in GovCloud

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/cloudformation-coverage-roadmap#553]
I created a stack in `us-gov-west-1` and the `Arn` returned has the partition specified as `aws` instead of `aws-us-gov`.

## Expected behavior

Arn returned via `GetAtt` should be valid.

## Suggest specific test cases

What I see in outputs and cross stack references (which fail!): `arn:aws:cognito-idp:us-gov-west-1:{AccountId}:userpool/us-gov-west-1_{UserPoolId}`

```
Description: Reproduces CloudFormation bug where Cognito UserPool Arn is incorrect
Resources:
  IdentityCognitoUserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
Outputs:
  CognitoUserPoolArn:
    Value: !GetAtt 
      - IdentityCognitoUserPool
      - Arn
  CognitoUserPoolID:
    Value: !Ref IdentityCognitoUserPool
```

## Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

8. Security (IAM, KMS...)
