### ISSUE TITLE
AWS::ElasticLoadBalancingV2::ListenerRule resource - false positive drift result / drift detection operation

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#609]
1.	Title
-> AWS::ElasticLoadBalancingV2::ListenerRule resource - false positive drift result

2.	Scope of request
-> Some ListenerRules within the are shown as drifted but are defined in CloudFormation template and existing within the Listener configuration. The ListenerRule [the definition of Actions and the Conditions] (which is working fine) is reported as modified, but they are not actually modified.

3.	Expected behavior
-> Drift Status after stack creation should be "sync"

4.	Example/Test case recommendation

```
  Listener443Rule1:
      Type: 'AWS::ElasticLoadBalancingV2::ListenerRule'
      Properties:
        ListenerArn: !Ref Listener443
        Priority: 1
        Actions:
          - Type: fixed-response
            FixedResponseConfig:
              ContentType: "text/plain"
              MessageBody: "Method X-Forwarded-For Not Allowed"
              StatusCode: "405"
        Conditions:
          - Field: http-header
            HttpHeaderConfig:
              HttpHeaderName: "X-Forwarded-For"
              Values: 
                - "*"
```
![git-example_ListenerRulesDrift](https://user-images.githubusercontent.com/16392819/90476130-2cd09f80-e129-11ea-9de7-9fb90a538539.JPG)
