### ISSUE TITLE
AWS::CodeBuild::Project - Support Batch Builds (From Trigger)

### ISSUE THREAD

**Issue by wulfmann** [aws-cloudformation/cloudformation-coverage-roadmap#621]
## 1. AWS::CodeBuild::Project - Support Batch Builds

When creating a CodeBuild project there is no way to specify that the webhook trigger should run the project as a 'Batch Build'

## 2. Scope of request 

a) new option for an existing attribute is desired

There is already a webhook option in the project triggers section of the provider, but it is a boolean value. It would seem that support for a new 'BuildType' option should be added.

## 3. Expected behavior

Allow me to specify a trigger type of STANDARD or BATCH

## 4. Suggest specific test cases

Samples:
## 5. Helpful Links to speed up research and evaluation

[Trigger batch build with cli](https://docs.aws.amazon.com/codebuild/latest/userguide/run-batch-build-cli.html)

## 6. Category (required)

1. Developer Tools (CodeBuild)

**Comment by wulfmann** [comment]
I can include screenshots from the console if that is helpful.

**Comment by tjenkinson** [comment]
It's not supported at the moment unfortunately. If you're using the CDK it's possible to create a custom resource using [`AwsCustomResource`](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html) which worked for us. Using the `CodeBuild` `service` and `createWebhook` `action`

**Comment by wulfmann** [comment]
Thanks for the tip @tjenkinson ! That seems like it will be adequate until this ticket is worked.

**Comment by subinataws** [comment]
@wulfmann - Thanks for reporting this issue. Team is working on a fix and will address it in the next week or so.

**Comment by tjenkinson** [comment]
just opened https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/633 which is support for triggering batch builds from codepipeline

**Comment by tjenkinson** [comment]
@subinataws any update on this?

**Comment by johnhanks1** [comment]
Hello @tjenkinson 

We have enabled this for projects. This can be used with CloudFormation with the BuildType option, the valid inputs are `BUILD` or `BUILD_BATCH` example below

```
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ...
      Source:
        Type: GITHUB
        Location: !Ref SourceLocation
        InsecureSsl: true
        GitCloneDepth: 1
        ReportBuildStatus: false
      Triggers:
        Webhook: true
        BuildType: BUILD_BATCH
```

We are working on updating or official documentation. Sorry for the confusion.
