### ISSUE TITLE
AWS::EC2::GatewayRouteTableAssociation in af-south-1, eu-south-1

### ISSUE THREAD

**Issue by ndrest-amzn** [aws-cloudformation/cloudformation-coverage-roadmap#628]
Currently using this resource results in 

Template format error: Unrecognized resource types: [AWS::EC2::GatewayRouteTableAssociation]

```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyGW:
   Type: 'AWS::EC2::GatewayRouteTableAssociation'
   Properties:
    GatewayId: 
    RouteTableId: 
```
