### ISSUE TITLE
AWS::ECS::TaskDefinition - AWS::CodeDeployBlueGreen Cannot deploy if TaskDefinition have volumes.

### ISSUE THREAD

**Issue by PorraphitChuasuk** [aws-cloudformation/cloudformation-coverage-roadmap#632]
## 1. Quick Summary

Cannot run Blue-Green deployment on TaskDefinition that have volumes attached.

## 2. Scope of request
Refer to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html

I have added EFS mount to the TaskDefinition, So it have
```yaml
  BlueTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ExecutionRoleArn: !GetAtt
        - ECSTaskExecutionRole
        - Arn
      ContainerDefinitions:
        - Name: DemoApp
          Image: 'nginxdemos/hello:latest'
          Essential: true
          PortMappings:
            - HostPort: 80
              Protocol: tcp
              ContainerPort: 80
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      Family: ecs-demo
      # Add volumes here...
      Volumes:
        - name: test
          EFSVolumeConfiguration:
            FilesystemId: !Ref EFS
```

This Resource can be created. However after update the task definition, such as change memory to '1024' and run cli update-stack. I got this error.

```
Invalid request provided: Create TaskDefinition: volume.name should not be null or empty. (Service: AmazonECS; Status Code: 400; Error Code: ClientException; Request ID: 6a47a31c-7fec-4f44-ae7a-c1c3089acda0; Proxy: null)
```

<img width="1000" alt="Screen Shot 2563-09-25 at 13 21 43" src="https://user-images.githubusercontent.com/20763506/94234667-53f26c00-ff34-11ea-9d0a-362930018b39.png">

## Expected behavior

On deployment, The GreenTaskDefinition can be created and it attached the same volume as Blue.

## 4. Suggest specific test cases

 - None

## 5. Helpful Links to speed up research and evaluation

AWS Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html
My test.yaml: https://gist.github.com/PorraphitChuasuk/4abb53b1ad51ec43ef7b57d5134191ac#file-ecs-deploy-w-volume-yaml

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Developer Tools:
 - CodeDeploy
 - ECS, Fargate, EFS

## 7. Any additional context (optional)

 - None
