### ISSUE TITLE
AWS::Lambda::Permission does not allow setting conditions on the resource policy

### ISSUE THREAD

**Issue by galaxy4public** [aws-cloudformation/cloudformation-coverage-roadmap#636]
## 1. Title
AWS::Lambda::Permission-Condition

## 2. Scope of request 
AWS::Lambda::Permission is the only way how one can attach a resource policy to a function.  However, it does not explicitly support conditions on the policy which makes it impossible to express things like exposing a Lambda function in one account for all other accounts in the organisation, e.g. using a condition like the following:

```JSON
"Condition": {"StringEquals":
      {"aws:PrincipalOrgID":["o-xxxxxxxxxxx"]}
    }
```

The proposed AWS::Lambda::Permission-Condition should address this by providing an interface as follows:

```YAML
LambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName: !GetAtt Function.Arn
      Principal: '*'
      Condition:
        StringEquals:
          "aws:PrincipalOrgID": [ o-xxxxxxxxxx ]
```

*NOTE* To make it easier to implement I suggest to make AWS::Lambda::Permission-Condition mutually exclusive with other properties that affect conditions such as AWS::Lambda::Permission-SourceArn.

## 3. Expected behavior

It expected that one can attach the resource policy with conditions to a Lambda function.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

Compute
