### ISSUE TITLE
AWS::EC2::TransitGatewayAttachment - Options

### ISSUE THREAD

**Issue by Robertjan123** [aws-cloudformation/cloudformation-coverage-roadmap#661]
AWS::EC2::TransitGatewayAttachment supports creating an VPC attachment, but it does not allow you to specify the attachments request options: DnsSupport and Ipv6Support. In our case we want to enable IPv6 Support but by default it is disabled. The API documentation mentions that it should be enabled by default (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayVpcAttachmentRequestOptions.html)

It should be possible to enable or disable the options by updating the template. 

```
Type: AWS::EC2::TransitGatewayAttachment
Properties: 
  SubnetIds: 
    - String?
  Tags: 
    - Tag
  TransitGatewayId: String
  VpcId: String?
  Options: 
    DnsSupport: Boolean
    Ipv6Support: Boolean
```
