### ISSUE TITLE
AWS::Cognito::UserPoolClient - ReadAttributes/WriteAttributes

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/cloudformation-coverage-roadmap#676]
## 2. Scope of request

Whenever a read attribute or write attribute is updated, the User Pool Client's provider is reset to the default (Cognito provider only).

   e) other coverage-related issue with the resource/attribute/option

## 3. Expected behavior

I expect changes to read attributes and write attributes to not affect the enabled identity providers of a UserPoolClient.

I think this should apply to other UserPoolClient properties as well.

### Create stack

```
SomeClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: my-client
    GenerateSecret: false
    UserPoolId: !Ref UserPool
    ReadAttributes:
      - email
    WriteAttributes:
      - email
    SupportedIdentityProviders:
      - COGNITO
```

### Update stack

```
SomeClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: my-client
    GenerateSecret: false
    UserPoolId: !Ref UserPool
    ReadAttributes:
      - email
      - given_name
      - family_name
    WriteAttributes:
      - email
      - given_name
      - family_name
    SupportedIdentityProviders:
      - COGNITO
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

8. Security (IAM, KMS...)
