### ISSUE TITLE
AWS::Shield::ProtectionAssociation

### ISSUE THREAD

**Issue by mkriedel** [aws-cloudformation/cloudformation-coverage-roadmap#677]
#### AWS::SheildAdvanced::ProtectionAssociation

We are hoping that the title makes it easy for others to scan it quickly in kanban board or issue list. 

## 2. Scope of request 
CloudFormation does not support creating protections for AWS Shield Advanced ([create-protection](https://docs.aws.amazon.com/cli/latest/reference/shield/create-protection.html))

## 3. Expected behavior

I should be able to have a resource similar to:

```yaml
WAFProtectionAssociation:
  Type: AWS::ShieldAdvanced::ProtectionAssociation
  Properties:
    Name: WafProtection
    ProtectedResourceARN: arn:xxx
```

Deleting this resource should remove the Shield Advanced protection association (e.g., it should remove the resource from the Protected Resources UI)

## 4. Suggest specific test cases

A resource that has a protection association should appear in the Shield Advanced Protected Resources UI.

## 5. Helpful Links to speed up research and evaluation

`create-protection` API call: https://docs.aws.amazon.com/cli/latest/reference/shield/create-protection.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

Security, Identity, & Compliance
