### ISSUE TITLE
AWS::SecretsManager::Secret - Cannot reference secret AWS::SecretsManager::Secret via resolve:secretsmanager in Cloudformation Output

### ISSUE THREAD

**Issue by lbornov2** [aws-cloudformation/cloudformation-coverage-roadmap#689]
The following Output section:
```
Outputs:
  InitialSysadminPassword:
    Description : "The ARN of the admin's password.  Navigate to the Secret in the AWS UI to view the value."
    Value: !Join ['', ['{{', 'resolve:secretsmanager:', !Ref InitialSysadminPassword, ':SecretString', '}}']]
```

Does not resolve the Value correctly.

Expected behaviour:
It should resolve the value of the secret, and display that in the `Outputs` section of the Cloudformation Stack in the AWS Console

Actual behaviour:
The output looks like this:
```
{{resolve:secretsmanager:arn:aws:secretsmanager:us-west-2:373610796317:secret:initial-sysadmin-password-foobar811-dLBAld:SecretString}}
```

This exact same statement is used elsewhere in the stack, and it resolves correctly there:
```
!Join ['', ['{{', 'resolve:secretsmanager:', !Ref InitialSysadminPassword, ':SecretString', '}}']]
```

`InitialSysadminPassword` is defined as follows:
```
  InitialSysadminPassword:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Initial Sysadmin Password Password (managed by cloudformation)"
      GenerateSecretString:
        ExcludeLowercase: false
        ExcludeNumbers: false
        ExcludePunctuation: true
        ExcludeUppercase: false
        IncludeSpace: false
        PasswordLength: 20
        RequireEachIncludedType: true
      Name: !Join [ "-", [ "initial-sysadmin-password", !Ref AWS::StackName ] ]
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
      - Key: Owner
        Value: openiam
```

Steps to reproduce:
1. Follow the instructions to deploy our cloudformation template, here: `https://bitbucket.org/openiam/openiam-cloudformation/src/RELEASE-4.2.1/README.md`.  This will take approximately 50 minutes to deploy.
2. Navigate to the `Outputs` Section of the Cloudformation Stack in the AWS Console.  You will see that the `Output` section does not contain the resolved value.
