### ISSUE TITLE
AWS::RDS::DBInstance - Allow setting the replica mode for Oracle read replicas

### ISSUE THREAD

**Issue by grauj-aws** [aws-cloudformation/cloudformation-coverage-roadmap#691]
## 1. Title

AWS::RDS::DBInstance - Allow setting the replica mode for Oracle read replicas

## 2. Scope of request 

- Support for creating Oracle standby replicas was [added recently](https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-rds-for-oracle-supports-managed-disaster-recovery-with-oracle-guard-physical-standby-database/), on October 22nd

- To set this option, it's required to set the mode of the replica to be of type `mounted`. [Example](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/oracle-read-replicas.html#awsui-expandable-section-1) on how this is done currently via the AWS CLI.

- CloudFormation doesn't support adding a replica mode on new RDS instance creation yet

## 3. Expected behavior

- The `AWS::RDS::DBInstance` resource should have a `Property`m on its definition, that allows setting the replica mode for new Oracle RDS replica databases.

## 4. Suggest specific test cases

- Example of how this might look:

```yaml
Resources:
  ReplicaDB:
    Type: AWS::RDS::DBInstance
    Properties:
      SourceDBInstanceIdentifier: !Ref 'MasterDB'
      DBInstanceClass: !Ref 'DBInstanceClass'
      ReplicaMode: mounted 		# 	Here the replica mode values should be either read-only or mounted
```

## 5. Helpful Links to speed up research and evaluation

RDS support for Oracle standby replicas announced: https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-rds-for-oracle-supports-managed-disaster-recovery-with-oracle-guard-physical-standby-database/

Creating an Oracle read replica of type `mounted` documentation: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/oracle-read-replicas.html#oracle-read-replicas.creating-in-mounted-mode

How to set the replica mode with the Java SDK: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/rds/model/CreateDBInstanceReadReplicaRequest.html#setReplicaMode-java.lang.String-

## 6. Category

Use the categories as displayed in the AWS Management Console (simplified):

3. DB (RDS, DynamoDB...)

## 7. Any additional context

- Currently, the workaround is to either create the resource manually through the CLI, or to use a CloudFormation custom resource
