### ISSUE TITLE
AWS::IoT::DomainConfiguration is missing return value for endpoint

### ISSUE THREAD

**Issue by tobilg** [aws-cloudformation/cloudformation-coverage-roadmap#694]
## 1. Title 

`AWS::IoT::DomainConfiguration`

## 2. Scope of request 

When creating a custom IoT Core domain configuration, it's currently not possible to automate the creation of a `AWS::Route53::RecordSet` due to a missing return value for the endpoint FQDN via CloudFormation.

E.g.
```yaml
MqttDnsRecord:
  Type: 'AWS::Route53::RecordSet'
  Properties:
    Comment: 'MQTT subdomain for my custom domain'
    HostedZoneId: 
       Ref: HostedZone
    Type: CNAME
    Name: 'mqtt.mydomain.com'
    AliasTarget:
      DNSName: 'a1234567-beta.iot.us-east-1.amazonaws.com' # Currently this need to be specified manually, see below
      EvaluateTargetHealth: False
      HostedZoneId: 'Z2FDTNDATAQYW2'
```

Currently, users are only able to manually specify the endpoint FQDN by running

```bash
$ aws iot describe-endpoint --endpoint-type iot:Data-Beta
```

as outlined in https://docs.aws.amazon.com/iot/latest/developerguide/iot-custom-endpoints-configurable-custom.html#iot-custom-endpoints-configurable-custom-dns

## 3. Expected behavior

The `AWS::IoT::DomainConfiguration` resource should have a return value which contains the actual endpoint FQDN.

## 6. Category

Use the categories as displayed in the AWS Management Console (simplified):

11. Other (IoT, Migration, Budgets...)

**Comment by tobilg** [comment]
Eventually, the required HostedZone entry for the `AWS::Route53::RecordSet` is also missing from the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html

**Comment by Pythoner6** [comment]
Just ran into this and had to use a custom resource to call `iot:DescribeDomainConfiguration` to look this up. It's not *hard* to do this, just rather annoying.

**Comment by patrickwerz** [comment]
Your Route 53 record should look like this:

```yml   MqttDnsRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        Comment: 'MQTT subdomain for custom domain'
        HostedZoneId: ${self:custom.hostedZoneId.${self:custom.stage}}
        Type: CNAME
        Name: ${self:custom.customIoTDomains.${self:custom.stage}}
        TTL: 300
        ResourceRecords:
          - !GetAtt IotEndpointCustomResource.IoTEndpoint`
```
To get the IoT Endpoint you can simply integrate a custom resource. This might help:

```python
import os
from crhelper import CfnResource
from aws_lambda_powertools.logging import Logger
import boto3

# suppress location key
logger = Logger()
helper = CfnResource(json_logging=True, log_level='DEBUG', boto_level='CRITICAL', sleep_on_delete=10)
region = os.getenv('aws_region')
iot = boto3.client('iot', region_name=region)

@helper.delete
def no_op(_, __):
    pass


@helper.create
@helper.update
def load_endpoint(_, __):
    try:
        end_point = iot.describe_endpoint(
            endpointType='iot:Data-ATS'
        )
        helper.Data.update({"IoTEndpoint": end_point['endpointAddress']})
    except Exception:
        logger.exception("error while loading the iot core endpoint")
        raise


def handler(event, context):
    helper(event, context)
```
