### ISSUE TITLE
AWS::EC2::TransitGateway Multicast Domain

### ISSUE THREAD

**Issue by tiagoasousa** [aws-cloudformation/cloudformation-coverage-roadmap#695]
New resource type for an existing service is desired

Multicast Transit Gateway Domain should be possible to manage via Cloudformation.

It is possible to enable on the TGW via cfn, but nothing else at this time:

https://docs.aws.amazon.com/vpc/latest/tgw/working-with-multicast.html

**Comment by jbpnaylon** [comment]
+1 for this. For completeness, subnet associations for multicast domains should also be manageable in CF.

**Comment by davidadas** [comment]
@networkpadawan please see https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewaymulticastdomain.html :)

**Comment by networkpadawan** [comment]
@davidadas thanks! is a good first step! but still no way to enable igmp support like https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_transit_gateway_multicast_domain

**Comment by davidadas** [comment]
@networkpadawan it should be...it's just only in US East (N. Virginia), US West (N. California), US West (Oregon), and Europe (Ireland) at the moment. Were you looking to run in a different region?

**Comment by networkpadawan** [comment]
hmm do you see the setting anywhere? igmpv2enabled?

**Comment by davidadas** [comment]
@networkpadawan give it a shot like this:

```json
{
  "Options": {
    "Igmpv2Support": "enable"
  }
}
```

It might just not be in the docs for some reason. If that doesn't work lmk.

**Comment by jbpnaylon** [comment]
Just tried the above:

  Properties validation failed for resource MCastTGWMulticastDomain with message: #: extraneous key [Igmpv2Support] is not permitted

(this was in eu-west-1)

**Comment by jp-xbox-gaming** [comment]
Got this to work through CFT. It appears that [the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewaymulticastdomain.html) is not up-to-date.

We can do this through CloudFormation template using `Options` property. Here is YAML example.

```
TransitGatewayMulticastDomain:
Type: AWS::EC2::TransitGatewayMulticastDomain
Properties:
  TransitGatewayId: !Ref TransitGatewayId
  Options:
    Igmpv2Support: enable
    StaticSourcesSupport: disable
    AutoAcceptSharedAssociations: enable
```

Hope this helps.
