### ISSUE TITLE
AWS::MediaConvert::JobTemplate DashIsoGroupSettings' isn't supported: MinFinalSegmentLength

### ISSUE THREAD

**Issue by investr777** [aws-cloudformation/cloudformation-coverage-roadmap#720]
Hi. I try to deploy a resource AWS::MediaConvert::JobTemplate, but I get the error while deploying: `The following property in '/SettingsJson/OutputGroups/0/OutputGroupSettings/DashIsoGroupSettings' isn't supported: MinFinalSegmentLength`.

```
SettingsJson:
   OutputGroups:
      - Name: 'DASH'
            OutputGroupSettings:
              Type: 'DASH_ISO_GROUP_SETTINGS'
              DashIsoGroupSettings:
                MinFinalSegmentLength: 1
                .......
```
Why is this happening?
