### ISSUE TITLE
AWS::Athena::Workgroup -WorkGroupConfiguration/WorkGroupConfigurationUpdates should support setting engine version

### ISSUE THREAD

**Issue by mgmarino** [aws-cloudformation/cloudformation-coverage-roadmap#721]
## 2. Scope of request 

AWS::Athena::Workgroup -WorkGroupConfiguration/WorkGroupConfigurationUpdates should support setting the version of the Athena engine

## 3. Expected behavior

It should allow you to select the following:
    - Default => let AWS decide/upgrade
    - 1 => Manually set Version 1
    - 2 => Manually set Version 2

## 5. Helpful Links to speed up research and evaluation

Athena docs: https://docs.aws.amazon.com/athena/latest/ug/engine-versions-changing.html#engine-versions-changing-changing-the-engine-version

## 6. Category (required) 

Analytics

**Comment by vincentippon** [comment]
Did you try to set the `SelectedEngineVersion` to `Athena engine version 2` with `EnforceWorkGroupConfiguration` enabled ?

```yml
...
WorkGroupConfiguration:
  EnforceWorkGroupConfiguration: true
  EngineVersion:
    SelectedEngineVersion: Athena engine version 2
...
```
