### ISSUE TITLE
AWS::WAFv2::WebACL - Tags stack level tags not propagated to resource tags

### ISSUE THREAD

**Issue by grantforrester-nes** [aws-cloudformation/cloudformation-coverage-roadmap#757]
## 1. Title 
**AWS::WAFv2::WebACL-Tags stack level tags not propagated to resource tags**

## 2. Scope of request 

Stack level tags set through `aws cloudformation deploy ..... --tags foo=bar` are not propagated to tags on created resources of type `AWS::WAFv2::WebACL`. 

As a result we have to explicitly set the tags on each `WebACL` resource using stack parameters as follows:
```yaml
WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
        ...
    Tags:
        - Key: foo
          Value: !Ref fooValue
```

## 3. Expected behavior

Defining Stack level tags using `aws cloudformation deploy ..... --tags foo=bar` should result in those tags appearing on any created `AWS::WAFv2::WebACL` resources without requiring explicit resource tagging.

## 6. Category

Security
