### ISSUE TITLE
AWS::MediaPackage::OriginEndpoint - [Feature Request] Support for Url retrieval of CmafPackage based OriginEndpoint resources

### ISSUE THREAD

**Issue by shalen-n** [aws-cloudformation/cloudformation-coverage-roadmap#767]
## 1. Title 
[Feature Request] AWS::MediaPackage::OriginEndpoint - Support for Url retrieval of CmafPackage based OriginEndpoint resources

## 2. Scope of request 

The "AWS::MediaPackage::OriginEndpoint" [1] CloudFormation resource supports the Url return value. Upon further investigation it seems that this only supports the retrieval of Urls for DASH and HLS based package OriginEndpoints and not CmafPackage based OriginEndpoint. Consequently, when attempting to return the Url for CmafPackage based OriginEndpoints via stack outputs, the result is an empty Url field.

## 3. Expected behavior
To return the Url associated with creating CmafPackage based "AWS::MediaPackage::OriginEndpoint" resources in CloudFormation via the Fn::GetAtt intrinsic function associated with this resource. 

## 4. Suggest specific test cases

Test Case 1: For example the following template does not return a Url for the CmafPackage based OrginEndpoint:
```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  HEVCMediaPackage:
    Type: AWS::MediaPackage::Channel
    Properties:
      Id: HEVC001
      Description: HEVC

  CmafOriginEndpoint:
    Type: AWS::MediaPackage::OriginEndpoint
    Properties:
      Id: CmafOriginEndpoint001
      ChannelId: !Ref HEVCMediaPackage
      Description: CmafOriginEndpoint
      Origination: ALLOW
      StartoverWindowSeconds: 0
      CmafPackage:
        HlsManifests:
          - Id: HlsManifests001
            IncludeIframeOnlyStream: false
            PlaylistWindowSeconds: 300
            ProgramDateTimeIntervalSeconds: 30
        SegmentDurationSeconds: 1
        SegmentPrefix: index
        StreamSelection:
          StreamOrder: ORIGINAL

Outputs:
  CmafOriginEndpoint:
    Value: !GetAtt CmafOriginEndpoint.Url
```

Test Case 2: The following template will return a Url for the DashPackage based OriginEndpoint

```
AWSTemplateFormatVersion: 2010-09-09

Resources:
  HEVCMediaPackage:
    Type: AWS::MediaPackage::Channel
    Properties:
      Id: HEVC001
      Description: HEVC

  DashOriginEndpoint:
    Type: AWS::MediaPackage::OriginEndpoint
    Properties:
      Id: CmafOriginEndpoint001
      ChannelId: !Ref HEVCMediaPackage
      Description: DashOriginEndpoint
      Origination: ALLOW
      StartoverWindowSeconds: 0
      DashPackage:
        ManifestLayout: COMPACT
        ManifestWindowSeconds: 200
        MinBufferTimeSeconds: 4
        MinUpdatePeriodSeconds: 4
        Profile: NONE
        SegmentDurationSeconds: 2
        SegmentTemplateFormat: NUMBER_WITH_DURATION
        StreamSelection:
          StreamOrder: ORIGINAL
        SuggestedPresentationDelaySeconds: 4

Outputs:
  DashOriginEndpoint:
    Value: !GetAtt DashOriginEndpoint.Url
```

## 5. Helpful Links to speed up research and evaluation

[1] AWS::MediaPackage::OriginEndpoint - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediapackage-originendpoint.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. CloudFormation
2. MediaPackage
