### ISSUE TITLE
AWS::ElasticBeanstalk::Environment should remove environment variable

### ISSUE THREAD

**Issue by jkoelewijn** [aws-cloudformation/cloudformation-coverage-roadmap#776]
In an AWS::ElasticBeanstalk::Environment, removing an environment variable does not seem to have any effect.

Steps to reproduce:

1. Create a new CloudFormation stack with the following YAML-template:

```yaml
Description: Remove Elastic Beanstalk Environment Variable Example
Resources:
  application:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      ApplicationName: removeenvvar
      Description: Remove Elastic Beanstalk Environment Variable Example
  environment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: removeenvvar
      Description: Remove Elastic Beanstalk Environment Variable Example
      EnvironmentName: removeenvvar-environment
      OptionSettings:
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: arn:aws:iam::<account_number>:role/aws-elasticbeanstalk-service-role
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: application
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVIRONMENT_VARIABLE_KEY
          Value: "ENVIRONMENT_VARIABLE_VALUE"
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: <vpc_id>
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: <vpc_subnets>
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: <vpc_subnets>
        - Namespace: aws:ec2:instances
          OptionName: InstanceTypes
          Value: t3.micro
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: arn:aws:iam::<account_number>:instance-profile/aws-elasticbeanstalk-ec2-role
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: "1"
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: "1"
      PlatformArn: arn:aws:elasticbeanstalk:::platform/Corretto 11 running on 64bit Amazon Linux 2
```

where `<account_number>`, `<vpc_id>` and `<vpc_subnets>` should be substituted.

2. Remove the following part of the YAML-template and update the stack:

```yaml
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVIRONMENT_VARIABLE_KEY
          Value: "ENVIRONMENT_VARIABLE_VALUE"
```

3. In the AWS console, go to the Elastic Beanstalk environment removeenvvar-environment, choose Configuration -> Software -> Edit.
4. Observe that the environment variable `ENVIRONMENT_VARIABLE_KEY` still exists.

Expected behavior:
* In step 4 the environment variable `ENVIRONMENT_VARIABLE_KEY` should not exist anymore.
