### ISSUE TITLE
AWS::S3::BucketNotification

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-coverage-roadmap#79]
1. Title -> AWS::S3::BucketNotification
2. Scope of request -> Allow bucket notifications to be managed separate from the bucket resource itself, resolving a longstanding circular reference problem
3. Expected behavior -> I should be able to create auto-named buckets with notifications that invoke Lambda/SNS/SQS
4. 
5. Links to existing API doc -> see below
6. Category tag -> Compute, Storage
7. Additional context:

The problem:

1. Image thumbnailing is [serverless 101](https://www.google.com/search?q=serverless+image+thumbnail). It involves setting up bucket notifications to invoke a Lambda function on file upload to a bucket (then generate the thumbnails and write them back to the bucket).
2. A best practice for CloudFormation is to let CloudFormation name your resources wherever possible, and only deal with logical ids, not physical resource ids.
3. These two things cannot currently be accomplished simultaneously. There needs to be a Lambda permission or SNS/SQS topic/queue policy, which needs to reference the bucket name, but the permission is checked for at notification configuration creation, before the bucket name could be provided to the permission resource.

Fundamentally, this is because there is not a separation between the the _creation_ of a bucket (and its name) and the settings on that bucket. There are at least [three](https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-circular-dependency-cloudformation/) [separate](https://aws.amazon.com/blogs/mt/resolving-circular-dependency-in-provisioning-of-amazon-s3-buckets-with-aws-lambda-event-notifications/) [places](https://aws.amazon.com/blogs/infrastructure-and-automation/handling-circular-dependency-errors-in-aws-cloudformation/) on AWS that say 🤷 to customers and tell them to manually create a bucket name in two separate places, which is brittle both in terms of multiple deployments of the template and in terms of updating that bucket name in the future.

This could instead be solved with a separate BucketNotification resource. The bucket resource would be created first, the name `!Ref`'d to the relevant places, and then the BucketNotification resource would install the notification configuration onto the bucket.

**Comment by rosskarchner** [comment]
Would this help solve this SAM issue? https://github.com/awslabs/serverless-application-model/issues/138

**Comment by benkehoe** [comment]
Yes, it's exactly that same problem.

**Comment by rosskarchner** [comment]
AWS folks, any chance this will move onto the board soon?

**Comment by luiseduardocolon** [comment]
We're keeping an eye on the +1s on this, but we're trying to prioritize coverage items first.

**Comment by tebruno99** [comment]
This took us by surprise today. Seems to make Policy Templates unusable.. Please Fix! We don't like letting workaround hacks live in our production environments.

**Comment by dennisandersen** [comment]
+1 on this. This has hit us more than once and feel this should be prioritized. It is not possible to achieve what i consider "THE" base use-case for bucket notifications: "read file that was just added to bucket", without resolving to cumbersome workarounds.

**Comment by TonyFNZ** [comment]
A couple of useful links: 

Existing Custom Resource which implements this functionality:
https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-s3-notification-lambda/

CDK issue which is blocked by this issue: aws/aws-cdk#4323

**Comment by purnesh** [comment]
+1

**Comment by major-fire** [comment]
+1

**Comment by jorgeandresvasquez** [comment]
+1

**Comment by yeDor** [comment]
+1

**Comment by jorgeandresvasquez** [comment]
+1

**Comment by jeffmarcinko** [comment]
+1

Still implementing workarounds like this, https://aws.amazon.com/blogs/mt/resolving-circular-dependency-in-provisioning-of-amazon-s3-buckets-with-aws-lambda-event-notifications/

Plus-one for all of Ben's original points.

**Comment by IanShoe** [comment]
+1

**Comment by adhandharia** [comment]
+1

**Comment by sahil-gt** [comment]
+1

**Comment by kz974** [comment]
Yes! +1

**Comment by jamescarignan** [comment]
+1

**Comment by ikben** [comment]
@purnesh @yeDor @IanShoe @kz974 @jamescarignan 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by pam81** [comment]
+1

**Comment by frank-io** [comment]
+1

**Comment by frank-io** [comment]
👍

**Comment by gdelia** [comment]
:+1:

**Comment by gdelia** [comment]
:+1:

**Comment by tmccoy** [comment]
:+1:

**Comment by michaelbrewer** [comment]
https://github.com/aws/aws-cdk/pull/11773 PR  tries to resolve this for AWS CDK.

**Comment by itharavi** [comment]
+1

**Comment by mrosenlund** [comment]
+1

**Comment by KlemenKozelj** [comment]
+1

**Comment by benbridts** [comment]
@pam81 @frank-io @gdelia @itharavi @mrosenlund @KlemenKozelj 


If you react with the 👍  button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher.

**Comment by anowac01** [comment]
How was this issue resolved?  I don't see any updates in the CloudFormation documentation relevant to it, and it still warns against the circular dependency:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig.html

**Comment by zwezheng** [comment]
+1

**Comment by gnobre** [comment]
+1

**Comment by taku-takamatsu** [comment]
+1

**Comment by Us3rname** [comment]
+1

**Comment by agniswarmandal** [comment]
+1

**Comment by benkehoe** [comment]
@zwezheng  @gnobre  @Us3rname @qcurtemanjc @agniswarmandal (and future potential "+1" commenters)

If you react with the 👍 button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher.

**Comment by polaskj** [comment]
It looks like a more elegant solution for this is finally here with this announcement, using EventBridge. https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/

Here's a pseudo Lambda invocation example I tested with success. This assumes your externally referenced S3 Bucket enables [EventBridge](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-eventbridgeconfig.html#cfn-s3-bucket-eventbridgeconfiguration-eventbridgeenabled) 

Stack:
```yaml
EventRule:
  Type: AWS::Events::Rule
  Properties:
    Description: EventRule
    State: ENABLED
    EventPattern: # https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html#eb-filtering-data-
      source:
        - aws.s3
      detail-type:
        - "Object Created"
      detail:
        bucket:
          name:
            - "EXTERNAL-BUCKET"
    Targets:
      - Arn: !GetAtt MyLambda.Arn
        Id: MyLambdaFunctionTarget

PermissionForEventsToInvokeLambda:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref MyLambda
    Action: lambda:InvokeFunction
    Principal: events.amazonaws.com
    SourceArn: !GetAtt EventRule.Arn

MyLambda:
  Type: AWS::Serverless::Function
  ... 
```

Bucket Stack:
```yaml
S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    ...
    BucketName: "EXTERNAL-BUCKET"
    NotificationConfiguration:
      EventBridgeConfiguration:
        EventBridgeEnabled: true
```

Linking back to https://github.com/aws/serverless-application-model/issues/124 since this is almost exactly the use-case.

**Comment by souvikataws** [comment]
Thanks for the feedback. We have created a Product Feature Request which will be prioritized with other features planned for Amazon S3. As another option, you can [enable EventBridge notifications on the S3 Bucket](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-notificationconfig-eventbridgeconfig.html#cfn-s3-bucket-eventbridgeconfiguration-eventbridgeenabled) (there are details on getting started [here](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/)). Additionally, you can refer to an example from [Polaskj](https://github.com/polaskj) who has provided a [CloudFormation template using EventBridge and Lambda as a destination](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/79#issuecomment-1012457735).

**Comment by Amir-Ahmad** [comment]
You can also do this without separately specifying the EventRule and Lambda::Permission:

```yaml
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        S3:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail:
                eventName:
                  - PutObject
                requestParameters:
                  bucketName:
                    - !Ref BucketName
            Target:
              Id: !Ref Function
```
