### ISSUE TITLE
AWS::Events::Rule ScheduleExpression - cron expression fails when provided as a parameter

### ISSUE THREAD

**Issue by matthewhegarty** [aws-cloudformation/cloudformation-coverage-roadmap#804]
Creation of a Cloudwatch event rule with a scheduled expression works fine when the cron schedule is included in the template.

When passed as a parameter it fails with:

```
Parameter validation failed:
Invalid type for parameter Parameters[3].ParameterValue, value: ['cron(5', '15', '25', '35', '45', '55 * ? * * *)'], type: <class 'list'>, valid types: <class 'str'>
```

### Expected behaviour

It should be possible to pass the cron expression as a parameter.

### Create Command (success)

```bash
export ENV=test
export STACK_NAME=test

aws cloudformation create-stack \
    --stack-name $STACK_NAME-scheduled-sqs-event \
    --capabilities CAPABILITY_IAM \
    --template-body file://scheduled-sqs-event.yml \
    --parameters \
        ParameterKey=Env,ParameterValue=${ENV} \
        ParameterKey=SQSStackName,ParameterValue=${ENV}-sqs \
        ParameterKey=QueueName,ParameterValue=${ENV}-upload-queue
```

### Create Command (fails)

```bash
export ENV=test
export STACK_NAME=test

aws cloudformation create-stack \
    --stack-name $STACK_NAME-scheduled-sqs-event \
    --capabilities CAPABILITY_IAM \
    --template-body file://scheduled-sqs-event.yml \
    --parameters \
        ParameterKey=Env,ParameterValue=${ENV} \
        ParameterKey=SQSStackName,ParameterValue=${ENV}-sqs \
        ParameterKey=QueueName,ParameterValue=${ENV}-upload-queue \
        ParameterKey=CronSchedule,ParameterValue="cron(5,15,25,35,45,55 * ? * * *)"
```

### Template 

scheduled-sqs-event.yml

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: Creates a Cloudwatch rule to send SQS message
Parameters:
  Env:
    Type: String
    Default: staging
    Description: The deployment environment (staging|prod).
  SQSStackName:
    Type: String
    Default: sqs
    Description: The name of the SQS stack.
  QueueName:
    Type: String
    Default: upload-queue
    Description: The name of the target queue.
  EventId:
    Type: String
    Default: scheduled-sqs-event
    Description: The name of the event
  CronSchedule:
    Type: String
    Description: The cron schedule
    Default: "cron(5,15,25,35,45,55 * ? * * *)"
  CmdJson:
    Type: String
    Description: The command to be submitted to the queue
    Default: '{"jobName": "batch_test", "cmd": ["make", "batch_test"]}'

Resources:
  SendEventServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
            Action:
              - sts:AssumeRole

  SendSQSScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "send sqs scheduled rule"
      ScheduleExpression: !Ref CronSchedule
      State: "ENABLED"
      RoleArn: !GetAtt 'SendEventServiceRole.Arn'
      Targets:
        - Arn:
            Fn::ImportValue:
              !Join [ ':', [ !Ref 'SQSStackName', 'UploadEventSourceQueueArn' ] ]
          Id: !Sub 'pva-${Env}-${EventId}'
          Input: !Ref CmdJson

  SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: SendSQSScheduledRule
    Properties:
      Queues:
        - !Sub 'https://sqs:${AWS::Region}.amazonaws.com/${AWS::AccountId}/${QueueName}'
      PolicyDocument:
        Statement:
          - Action:
              - SQS:SendMessage
              - SQS:ReceiveMessage
            Effect: "Allow"
            Resource:
              Fn::ImportValue:
                !Join [ ':', [ !Ref 'SQSStackName', 'UploadEventSourceQueueArn' ] ]
            Principal:
              Service:
                - events.amazonaws.com
                - sqs.amazonaws.com
```

**Comment by benbridts** [comment]
This seems to be a CLI issue, and not a CloudFormation issue. The command fails even if you don't have any valid AWS credentials (and if you use other tools like `rain` or other commands like `aws cloudformation deploy` you don't run into this issue.

```
aws cloudformation deploy --template-file example.yaml --stack-name example-deploy --parameter-overrides Input=one,two,three

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - example-deploy
```

If you escape the `'` with a `\` it does seem to work for me.

I tried with this template:

```yaml
Parameters:
  Input:
    Type: String
Resources:
  Dummy:
    Type: AWS::CloudFormation::WaitConditionHandle
Outputs:
  Output:
    Value: !Ref Input
```

```
# this fails
~$ aws cloudformation create-stack --template-body file://example.yaml --stack-name example-create --parameters ParameterKey=Input,ParameterValue="one,two,three"

Parameter validation failed:
Invalid type for parameter Parameters[0].ParameterValue, value: ['one', 'two', 'three'], type: <class 'list'>, valid types: <class 'str'>

# this works
~$ aws cloudformation create-stack --template-body file://example.yaml --stack-name example-create --parameters ParameterKey=Input,ParameterValue="one\,two\,three"
{
    "StackId": "arn:aws:cloudformation:eu-west-1:123456789012:stack/example-create/cbf9fde0-aaaa-bbbb-cccc-ddddddddd"
}
#

# and the output does not contain the \
~$ aws cloudformation describe-stacks --stack-name example-create --query 'Stacks[0].Outputs[0]'
{
    "OutputKey": "Output",
    "OutputValue": "one,two,three"
}
```
