### ISSUE TITLE
AWS::ApiGateway::Method - ::Integration-TlsConfig 

### ISSUE THREAD

**Issue by marcinkaluza** [aws-cloudformation/cloudformation-coverage-roadmap#816]
## 2. Scope of request 
REST API Gateway internally supports TLS configuration of the backend integration (tlsConfig) which allows the end user to turn off validation of TLS cert's CA authority. This feature is not available through CloudFormation.  

## 3. Expected behavior

When set in the CF template as per example below the flag should be set on the integration object as per documentation https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-extensions-integration-tls-config.html

```
  MethodAPI:
    Type: AWS::ApiGateway::Method
    Properties: 
      RestApiId: 
        Fn::ImportValue: !Sub "${APIStackName}-PrivateRESTAPI"
      ResourceId: !Ref ResourceAPI
      HttpMethod: ANY
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: 
        TlsConfig:
           InsecureSkipVerification: true
```

The option should be applied in create and update operation as per console behavior. Update should not require replacement of the resource.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-extensions-integration-tls-config.html

## 6. Category

4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by alecsaunders** [comment]
I also would like to see this functionality.

**Comment by eboyeb** [comment]
I would like to see this functionality

**Comment by manupatteri** [comment]
I also would like to see this functionality.

**Comment by vergenzt** [comment]
I don't this mentioned in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html nor do I see `TlsConfig` in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-method-integration.html.

Additionally I keep getting an error when trying to use it. With this stack:

```yaml
...
Resources:
  ...
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: { Fn::GetAtt: [ApiGatewayRestApi, RootResourceId] }
      PathPart: ...
      RestApiId: { Ref: ApiGatewayRestApi }
  ProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: { Ref: ApiGatewayRestApi }
      ResourceId: { Ref: ProxyResource }
      HttpMethod: GET
      Integration:
        Type: HTTP_PROXY  # also fails with type `HTTP`
        IntegrationHttpMethod: GET
        Uri: https://wrong.host.badssl.com/
        TlsConfig:
          InsecureSkipVerification: true
```

I get an error:
```
CREATE_FAILED: ProxyMethod (AWS::ApiGateway::Method)
Properties validation failed for resource ProxyMethod with message:
[#/Integration: extraneous key [TlsConfig] is not permitted]
```
