### ISSUE TITLE
AWS::ECS::Cluster when ECS service linked role does not exist

### ISSUE THREAD

**Issue by hauntingEcho** [aws-cloudformation/cloudformation-coverage-roadmap#818]
## Scope of request 

When the service-linked role does not exist, creating a cluster fails (with "Invalid request provided: CreateCluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists.").  Recreating the stack succeeds.

## Expected behavior

success the first time

## Specific test cases

```
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
```
in a brand-new AWS account, ran with admin credentials

## Category

Compute, Security
