### ISSUE TITLE
AWS::EC2::Volume - Arn should be exposed via Fn::GetAtt

### ISSUE THREAD

**Issue by jfoy** [aws-cloudformation/cloudformation-coverage-roadmap#829]
## Scope of request

AWS::EC2::Volume-Arn should be available to query from other resources via Fn::GetAtt. 

## Common use case

```
---
Resources:
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 1024
      AvailabilityZone: us-west-2a

  Backup:
    Type: AWS::Backup::Selection
    Properties:
      BackupPlanId: !Ref Plan
      BackupSelection:
        Resources: !GetAtt Volume.Arn
```

## Category

Compute (EBS)

**Comment by kunithya** [comment]
From the public docs, https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Volume.html

Volume ARN is not something that exists in EC2. So, this cannot be supported through Cfn unless it is supported from the top-level.

I tried reproducing the customer's usecase and this is something I was successful with.

**Customer's usecase**

```
---
Resources:
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 1024
      AvailabilityZone: us-west-2a

  Backup:
    Type: AWS::Backup::Selection
    Properties:
      BackupPlanId: !Ref Plan
      BackupSelection:
        Resources: !GetAtt Volume.Arn
```

**Proposed workaround**
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 1024
      AvailabilityZone: us-east-1a

  Backup:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref Plan
      BackupSelection:
        Resources: 
            - !Sub arn:aws:ec2:<region>:<account-id>:volume/${Volume.VolumeId}
        SelectionName: Sample
        IamRoleArn: arn:aws:iam::<account-id>:role/<role-name>
```

-- EBS Engineer
