### ISSUE TITLE
AWS::AppConfig::EnvironmentMonitor

### ISSUE THREAD

**Issue by chrisoverzero** [aws-cloudformation/cloudformation-coverage-roadmap#840]
## Scope of Request

AWS::AppConfig::Environment is unwieldy to use with monitored rollback in many configurations, such as alongside AWS Lambda. For the Lambda Function to be able to read the AppConfig Configuration Version, it must be passed (among other things) the AppConfig Environment. To monitor the Function for rollback, the name of the function must be passed to a CloudWatch Alarm, the ARN of which must be passed to the monitor collection in the AppConfig Environment. It is undesirable to explicitly name Lambda Functions, so the circular dependency is difficult to avoid. (The same applies for AWS::Serverless::RestApi, for example.)

## Expected Behavior

It should be possible to break the circular dependency with another resource which attaches the other way, something like:

```yaml
ApiMonitor:
  Type: AWS::AppConfig::EnvironmentMonitor
  Properties:
    ApplicationId: !Ref ConfigApplication
    EnvironmentId: !Ref ConfigEnvironment
    AlarmArn: !GetAtt Api5xxAlarm.Arn
    AlarmRole: !GetAtt ConfigRollbackWatcherRole.Arn
```

## Suggest Specific Test Cases

A template with an AppConfig Application, Environment, and Configuration profile; a Lambda function; and a CloudWatch alarm should display it. Have the environment variables of the Function reference each AppConfig resource, have the alarm reference the Function, and have the AppConfig Environment reference the Alarm.

## Helpful Links to Speed Up Research and Evaluation

It would be great if it worked like Security Group [Egress][] and [Ingress][].

[Egress]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html
[Ingress]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-ingress.html

## Category

Management & Governance
