### ISSUE TITLE
AWS::SQS::QueuePolicy Bug resolving dynamic references in Condition statement

### ISSUE THREAD

**Issue by jamessoubry** [aws-cloudformation/cloudformation-coverage-roadmap#874]
2. Scope of request
Dynamic reference is not being resolved within the "Condition" section. instead, the text is displayed in the policy.

3. Expected behavior

It should lookup the secret

4. Test case recommendation 
The following template section does not resolve the secret. 
```
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "sqs:SendMessage"
            Principal:
              AWS: '*'
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn":  !Sub "{{resolve:secretsmanager:/${Environment}/${Region}/topics:SecretString:MyTopicArn}}"
      Queues:
        - !Ref Queue
```
I've not checked if its specific to a Condition statement or specific to QueuePolicy
