### ISSUE TITLE
How to interpolate resolved parameter store values with other strings?

### ISSUE THREAD

**Issue by charlesdarkwind** [aws-cloudformation/cloudformation-coverage-roadmap#879]
I want to build a string `{{resolve:ssm:myVar}}-someString` but the parameter store variable resolve part doesn't get evaluated.

parameter store variable 'bar-dev' value: 'myValue'

code:
```yaml
Resources:
  MyFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: path/
        Role: !GetAtt Role.Arn
        Events:
          TrackEventTableStream:
            Type: DynamoDB
            Properties:
              StartingPosition: TRIM_HORIZON
              MaximumRetryAttempts: 3
              Stream:
                Fn::ImportValue:
                  Fn::Join:
                    - ''
                    - - !Sub
                        - '{{resolve:ssm:/${foo}-${env}}}-'
                        - foo: 'bar'
                          env: !Ref Env
                      - 'TrackEventTableStreamArn'
```

Result during SAM deploy:
```
Deploy this changeset? [y/N]: y

2021-06-15 11:19:59 - Waiting for stack create/update to complete

CloudFormation events from changeset
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                  ResourceType                                    LogicalResourceId                               ResourceStatusReason
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UPDATE_ROLLBACK_IN_PROGRESS                     AWS::CloudFormation::Stack                      etl-ingestion-dev                               No export named {{resolve:ssm:bar-
                                                                                                                                                dev}}-TrackEventTableStreamArn found
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS    AWS::CloudFormation::Stack                      etl-ingestion-dev                               -
UPDATE_ROLLBACK_COMPLETE                        AWS::CloudFormation::Stack                      etl-ingestion-dev                               -
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Failed to create/update the stack: etl-ingestion-dev, Waiter StackUpdateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expe
cted path: "UPDATE_ROLLBACK_COMPLETE" at least once
```

Expected final value:
`myValue-TrackEventTableStreamArn`

Obtained final value:
`{{resolve:ssm:bar-dev}}-TrackEventTableStreamArn`
