### ISSUE TITLE
AWS::EFS::FileSystem -  FileSystemTags does not allow 'AWS::NoValue'

### ISSUE THREAD

**Issue by dvedhire** [aws-cloudformation/cloudformation-coverage-roadmap#884]
### Scope of request:

Support for conditional creation of FileSystemTags with 'AWS::NoValue' for `AWS::EFS::FileSystem` resource.

### Expected behavior:

Currently, when we are creating *FileSystemTags* with conditional value and if the condition evaluates to false, CloudFormation stack creation is failing for `AWS::EFS::FileSystem` resource with the following error: `Resource handler returned message: "null"`

For example, below tag value evaluates to `AWS::NoValue` considering the condition evaluates to false:

```
  EFS:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: backup
          Value: !If [BackUpTagNull, !Ref BackupTag, !Ref 'AWS::NoValue'] 
```

### Additional context:

* An empty value for FileSystemTags is supported through console. We request the same support using CloudFormation as well.
* Also, if the same condition is applied on an `AWS::S3::Bucket` resource, the bucket gets created successfully with an empty tag value. The same implementation for `AWS::EFS::FileSystem` resource would help greatly in managing the templates dynamically.

**Example:**
```
  Bucket: 
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: TestTag
          Value: !If [BackUpTagNull, !Ref BackupTag, !Ref 'AWS::NoValue'] 
```

**Comment by abatemt** [comment]
You should be able to achieve this by just passing an empty string as the `Value`. For example, this template successfully deploys:

```
Resources:
  EFSFileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      FileSystemTags:
        - Key: TestTag
           Value: ""
```

We don't implicitly convert `AWS::NoValue` into an empty string in this case.
