### ISSUE TITLE
AWS::RDS::DBCluster - Enable General Log in RDS doesn't create the LogGroup

### ISSUE THREAD

**Issue by biohazd** [aws-cloudformation/cloudformation-coverage-roadmap#885]
## 2. Scope of request 
I used Cloudformation to Enable the "EnableCloudwatchLogsExports" and enable "error" and "general" logs.
In Cloudwatch, I can only see the "error" log in LogGroups, the "general" log doesn't show.
If I look under Logs in the RDS console, there is also no "general" log, only "error" logs.

E.g. /aws/rds/cluster/dbcluster-1sfsdfsfsfsfi/error
 
## 3. Expected behavior
If the "EnableCloudwatchLogsExports" option is set then the correct logs in Cloudwatch LogGroups should be created.

What are the names of each log that should be create for MySQL Aurora?

> Aurora MySQL
> Possible values are audit, error, general, and slowquery. 

Are these the correct logGroups it should create?

- /aws/rds/cluster/dbcluster-1sfsdfsfsfsfi/error
- /aws/rds/cluster/dbcluster-1sfsdfsfsfsfi/general
- /aws/rds/cluster/dbcluster-1sfsdfsfsfsfi/slowquery
- /aws/rds/cluster/dbcluster-1sfsdfsfsfsfi/audit

**Comment by biohazd** [comment]
I found the LogGroup is only created if I view the RDS Cluster and edit the Parameter Group and set "general_log" to 1.    Previosuly it had no value.

**Comment by moataz-mhmd** [comment]
There is no way to allow general log from DBCluster resource. Allowing it is applicable via custom DB parameter group. You can follow this article [RDS MySQL Logs](https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-logs/). You can also use CloudForamtion stack to create this custom DB parameter group and referencing it to your db cluster.
Example DBClusterParameterGroup resource:
```
ExampleDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: Aurora mysql cluster parameter group example
      Family: aurora-mysql8.0
      Parameters:
        general_log: 1
        slow_query_log: 1
        server_audit_logging: 1
```
