### ISSUE TITLE
AWS::MediaLive::Input fails without the Name property

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-coverage-roadmap#906]
### Name of the resource

AWS::MediaLive::Input

### Resource Name

AWS::MediaLive::Input

### Issue Description

When deploying the following template, CloudFormation gives the error "Non-empty input name required (Service: AWSMediaLive; Status Code: 400; Error Code: BadRequestException; Request ID: bbe159d1-6916-47c7-a222-7fd1ac0efcf6; Proxy: null)", instead of generation a Name.

Note that the template is valid, [Name](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-medialive-input.html#cfn-medialive-input-name) is not a required property

```
Parameters:
  InputUrl:
    Description: Source stream URL
    Type: String
    AllowedPattern: "^https://.*"
Resources:
  MediaLiveInput:
    Type: "AWS::MediaLive::Input"
    Properties:
      Type: "URL_PULL"
      Sources:
        - Url: !Ref InputUrl
```

### Expected Behavior

The AWS::MediaLive::Input resource should auto-generate an acceptable name before sending the request to the MediaLive service.

### Observed Behavior

The service returns an error

### Test Cases

See the template in the description for a failing template. Adding the "Name" property makes the deploy succeed
