### ISSUE TITLE
AWS::KinesisFirehose::DeliveryStream - ExtendedS3DestinationConfiguration - Dynamic Partitioning

### ISSUE THREAD

**Issue by nickhiggs** [aws-cloudformation/cloudformation-coverage-roadmap#915]
### Name of the resource

AWS::KinesisFirehose::DeliveryStream

### Resource name

AWS::KinesisFirehose::DeliveryStream

### Description

Kinesis Firehose recently released dynamic partitioning for its S3 destination https://aws.amazon.com/about-aws/whats-new/2021/08/introducing-dynamic-partitioning-amazon-kinesis-data-firehose/ and we'd be interested in provisioning that functionality through CloudFormation.

**Comment by wolfadr** [comment]
This seems to work already, the documentation is not complete though. The JSON schema for `AWS::KinesisFirehose::DeliveryStream` already contains the configuration element for creating a stream with dynamic partitioning. We successfully deployed such a stream using the following properties (sorry, not a complete example):

```yaml
  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub "arn:aws:s3:::${BucketName}"
        BufferingHints:
          IntervalInSeconds: !Ref FlushIntervalInSeconds
          SizeInMBs: !Ref FlushSizeInMBs
        ErrorOutputPrefix: "errors/json/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/!{firehose:error-output-type}"
        Prefix: "data/json/year=!{partitionKeyFromQuery:year}/month=!{partitionKeyFromQuery:month}/day=!{partitionKeyFromQuery:day}/hour=!{partitionKeyFromQuery:hour}/"
        RoleARN: !GetAtt FirehoseRole.Arn
        DynamicPartitioningConfiguration:
          Enabled: true
          RetryOptions:
            DurationInSeconds: 300
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: MetadataExtraction
              Parameters:
                - ParameterName: MetadataExtractionQuery
                  ParameterValue: "{year:.requestEpoch | strftime(\"%Y\"),month:.requestEpoch | strftime(\"%m\"),day:.requestEpoch | strftime(\"%d\"),hour:.requestEpoch | strftime(\"%H\")}"
                - ParameterName: JsonParsingEngine
                  ParameterValue: "JQ-1.6"
```

Please be aware, that you can only CREATE a delivery stream this way, UPDATE is not supported (yet?).
