### ISSUE TITLE
AWS::ElastiCache::ReplicationGroup - Sharded cluster always requires replacement when increasing number of nodes

### ISSUE THREAD

**Issue by 422158** [aws-cloudformation/cloudformation-coverage-roadmap#918]
### Name of the resource

Other

### Resource name

AWS::ElastiCache::ReplicationGroup

### Description

When you try to increase a number of nodes per shard in `AWS::ElastiCache::ReplicationGroup` you always need to replace the resource.
It does not matter whether I use `ReplicasPerNodeGroup` parameter or if I use `NodeGroupConfiguration`. 

1. In case I use `ReplicasPerNodeGroup`, increase attempt always triggers the replacement.

2. In case I use `NodeGroupConfiguration`, increase attempt will throw error: `Node Group with Id 0001 has replica count 3` (provided that the previous number of nodes in shard 0001 was 3)

**Comment by aaaeeeo** [comment]
+1
I can do this without replacement with ElastiCache directly: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/increase-replica-count.html

**Comment by kloty** [comment]
I need this too. I added a new replica to failover on production, it became impossible to update cloudformation stack.

Is there a way to manually drift before aws supports it?

**Comment by expe-elenigen** [comment]
Would it be possible to get an update on this, I see there was an official response to this issue saying:

> [...] That being said the Cloudformation service team is aware of this behavior change for the ReplicasPerNodeGroup parameter via the console and are working towards releasing a fix so that you can update ReplicasPerNodeGroup via Cloudformation without a replacement of the cluster in the same way you are able to do it via the console. [...]

https://repost.aws/questions/QUsBl1YbQFSiue-TaPdyvtiA/change-the-number-of-replicas-on-my-cluster-without-recreate-it-using-cloudformation

**Comment by Aleks-vvt** [comment]
+1

**Comment by mvhowardAWS** [comment]
I believe the [UseOnlineResharding update policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-useonlineresharding) is the solution here?

> To modify a replication group's shards by adding or removing shards, rather than replacing the entire [AWS::ElastiCache::ReplicationGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html) resource, use the UseOnlineResharding update policy.

> If UseOnlineResharding is set to true, you can update the NumNodeGroups and NodeGroupConfiguration properties of the AWS::ElastiCache::ReplicationGroup resource, and CloudFormation will update those properties without interruption. When UseOnlineResharding is set to false, or not specified, updating the NumNodeGroups and NodeGroupConfiguration properties results in CloudFormation replacing the entire AWS::ElastiCache::ReplicationGroup resource.

**Comment by sukumaar** [comment]
@422158 ,

Thanks for reporting this. Managing `ReplicasPerNodeGroup` through CloudFormation can indeed be challenging, as updates to this property may not behave as expected in all scenarios.

Here are a couple of workaround options depending on your setup:

> **⚠️ Disclaimer:** Any solutions provided below are workarounds and are not officially mentioned or suggested in any AWS documentation. They do not represent official AWS guidance. Please use them at your own risk and test thoroughly in a non-production environment before applying to any production workloads.

### Option 1: Manual update (suitable for small Redis clusters)

**Workaround steps for an existing CloudFormation stack** (assuming a stack is already deployed via CloudFormation):

1. Modify the ElastiCache Replication Group:
    - Either using the AWS CLI
    - Or using the AWS Console (web UI)
2. Then edit `ReplicaCount` or `NodeGroupConfiguration` in the template that was used while creating the stack in CloudFormation.
3. Select your stack in CloudFormation.
4. Update stack → Make a direct update → Use the newly edited template.
5. The CloudFormation stack will update with the latest state of the [ElastiCache Replication Group](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ReplicationGroup.html).

### Option 2: CustomResource with Lambda (suitable for Redis and Valkey)

There is another option where you can use a [CustomResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-cloudformation-customresource.html) with [custom provisioning logic](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html) , [custom resource lambda](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources-lambda.html).

This approach is applicable for both Redis and Valkey. Make sure you do **not** include `ReplicasPerNodeGroup` in `AWS::ElastiCache::ReplicationGroup` so that CloudFormation does not track it. Otherwise, CloudFormation will try to sync the deployed resources with the template and may override your replica count changes.

The following is a reference snippet - you will need to adapt it to fit your existing template and environment:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  VPC-based networking stack with ElastiCache valkey and redis replication group

Resources:
# Your existing resources
# .
# .
# .
# .
# AWS::EC2::VPC 
# AWS::EC2::InternetGateway 
# AWS::EC2::VPCGatewayAttachment 
# AWS::EC2::RouteTable 
# AWS::EC2::Route 
# AWS::EC2::Subnet 
# AWS::EC2::SubnetRouteTableAssociation 
# AWS::ElastiCache::SubnetGroup 
# AWS::EC2::SecurityGroup  
# AWS::EC2::SecurityGroupIngress
# .
# .
# .

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    UpdatePolicy:
      UseOnlineResharding: true
    Properties:
      ReplicationGroupDescription: Primary RG for test
      Engine: valkey
      EngineVersion: "8.0"
      AutomaticFailoverEnabled: true
      MultiAZEnabled: false
      NumNodeGroups: 1
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      SecurityGroupIds:
        - !Ref CacheSecurityGroup
      CacheParameterGroupName: default.valkey8.cluster.on
      CacheNodeType: cache.t4g.micro
      Port: 6379
      AtRestEncryptionEnabled: false
      TransitEncryptionEnabled: false

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    UpdatePolicy:
      UseOnlineResharding: true
    Properties:
      ReplicationGroupDescription: Redis 7 RG for test
      Engine: redis
      EngineVersion: "7.1"
      AutomaticFailoverEnabled: true
      MultiAZEnabled: false
      NumNodeGroups: 1
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      SecurityGroupIds:
        - !Ref CacheSecurityGroup
      CacheParameterGroupName: default.redis7.cluster.on
      CacheNodeType: cache.t4g.micro
      Port: 6379
      AtRestEncryptionEnabled: false
      TransitEncryptionEnabled: false

  MyReplicaScaler:
    Type: Custom::ReplicaCount
    DependsOn: ReplicationGroup
    Properties:
      ServiceToken: !GetAtt ReplicaScalerFunction.Arn
      ReplicationGroupId: !Ref ReplicationGroup
      ReplicaCount: "1"

  MyRedisReplicaScaler:
    Type: Custom::ReplicaCount
    DependsOn: RedisReplicationGroup
    Properties:
      ServiceToken: !GetAtt ReplicaScalerFunction.Arn
      ReplicationGroupId: !Ref RedisReplicationGroup
      ReplicaCount: "2"

  ReplicaScalerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ElastiCacheReplicaScaler
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - elasticache:DescribeReplicationGroups
                  - elasticache:IncreaseReplicaCount
                  - elasticache:DecreaseReplicaCount
                Resource: "*"

  ReplicaScalerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: elasticache-replica-scaler
      Runtime: python3.12
      Handler: index.handler
      Timeout: 900
      Role: !GetAtt ReplicaScalerRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import time

          client = boto3.client("elasticache")

          def get_current_replica_count(group_id):
              desc = client.describe_replication_groups(ReplicationGroupId=group_id)
              return len(desc["ReplicationGroups"][0]["NodeGroups"][0]["NodeGroupMembers"]) - 1

          def wait_for_available(group_id, timeout=900):
              start = time.time()
              while time.time() - start < timeout:
                  desc = client.describe_replication_groups(ReplicationGroupId=group_id)
                  status = desc["ReplicationGroups"][0]["Status"]
                  if status == "available":
                      return
                  time.sleep(30)
              raise TimeoutError(f"Replication group {group_id} not available after {timeout}s")

          def handler(event, context):
              try:
                  request_type = event["RequestType"]
                  props = event["ResourceProperties"]
                  group_id = props["ReplicationGroupId"]
                  desired = int(props["ReplicaCount"])

                  if request_type in ("Create", "Update"):
                      current = get_current_replica_count(group_id)

                      if desired > current:
                          client.increase_replica_count(
                              ReplicationGroupId=group_id,
                              NewReplicaCount=desired,
                              ApplyImmediately=True,
                          )
                          wait_for_available(group_id)
                      elif desired < current:
                          client.decrease_replica_count(
                              ReplicationGroupId=group_id,
                              NewReplicaCount=desired,
                              ApplyImmediately=True,
                          )
                          wait_for_available(group_id)

                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {
                      "ReplicaCount": str(desired) if request_type != "Delete" else "0",
                  }, group_id)

              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Error": str(e)})

Outputs:
  PrimaryRGId:
    Description: Replication group ID
    Value: !Ref ReplicationGroup

  PrimaryEndpoint:
    Description: Primary endpoint address for the replication group
    Value: !GetAtt ReplicationGroup.ConfigurationEndPoint.Address

```
