### ISSUE TITLE
AWS::RDS::DBCluster - 'You currently can't modify BackupWindow with Aurora Serverless' - Validation error even if the BackupWindow property is unchanged

### ISSUE THREAD

**Issue by Sanchi-Halikar** [aws-cloudformation/cloudformation-coverage-roadmap#939]
### Name of the resource

AWS::RDS::DBCluster

### Resource Name

AWS::RDS::DBCluster

### Issue Description

On updating `AWS::RDS::DBCluster` with engine type  **_Aurora Serverless_** any of the following two errors are observed even when the properties _BackupWindow_ and  _MaintenanceWindow_ are not updated :  

`You currently can't modify BackupWindow with Aurora Serverless` or  `Currently can't modify MaintenanceWindow with Aurora Serverless`

### Expected Behavior

Since the property value is not changed during an update, the update for DB cluster resource should go through. ModifyDBCluster API call should go not fail

### Observed Behavior

BackupWindow and  MaintenanceWindow are passed within ModifyDBCluster API call even with no changes during an update causing the update to fail. 

### Test Cases

```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetIDAZA:
    Type: AWS::EC2::Subnet::Id
  SubnetIDAZB:
    Type: AWS::EC2::Subnet::Id
  AuroraMetastoreSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
Resources:
  AuroraMetastore:
    Properties:
      DBSubnetGroupName:
        Ref: AuroraMetastoreDBSubnetGroup
      Engine: aurora
      EngineMode: serverless
      MasterUserPassword: "12345"
      MasterUsername: admin
      PreferredBackupWindow: 03:32-04:02
      PreferredMaintenanceWindow: mon:02:56-mon:03:26
      Tags:
      - Key: SystemOwner
        Value: Chippen Dale
      VpcSecurityGroupIds:
      - Ref: AuroraMetastoreSecurityGroup
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
  AuroraMetastoreDBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: Subnet group for Aurora RDS Metastore
      SubnetIds:
      - Ref: SubnetIDAZA
      - Ref: SubnetIDAZB
      Tags:
      - Key: SystemOwner
        Value: Marco
    Type: AWS::RDS::DBSubnetGroup
```

During the next update, making any changes to resources ( updated 'Tags') will result in failure with the message:

_You currently can't modify BackupWindow with Aurora Serverless_
