### ISSUE TITLE
Fn::Map intrinsic function

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-coverage-roadmap#941]
### Details

A lot of complaints about CloudFormation verbosity are things like having to replicate subnets for each availability zone. An `Fn::Map` function, which allowed basic parameterization of resources or properties, would allow for concise, semantically-meaningful expression of duplication.

[A twitter thread on this topic]()

An example from [here](https://gist.github.com/benbridts/810ad93de0a2acd6744746478785973d)
```yaml
Resources:
  EfsMountTargets:
    # this assigns each item from Subnets to x while iterating
    Map: {x: !Ref Subnets}
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSVolume
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: !Ref x
Outputs:
  EfsMountIpAddress:
    Map: {x: !Ref Subnets}
    Description: !Sub "Ip Address for ${x}"
    # this might be better without the !Sub, assuming !GetAtt/Ref knows to resolve that in the Map
    Value: !GetAtt !Sub "EfsMountTargets.${x}.IpAddress"
```
This could be equivalent to

```yaml
Resources:
  # the part after the . can be anything; as long as the same input keeps the same resource name
  # using the value as-is might help with linking mapped resources (see outputs)? 
  EfsMountTarget.eu-west-1a:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSVolume
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: eu-west-1a
  EfsMountTarget.eu-west-1b:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref EFSVolume
      SecurityGroups:
        - !Ref EFSSecurityGroup
      SubnetId: eu-west-1a
Outputs:
  EfsMountIpAddress.eu-west-1a:
    Description: Ip Address for eu-west-1a
    Value: !GetAtt EfsMountTargets.eu-west-1a.IpAddress
  EfsMountIpAddress.eu-west-1b:
    Description: Ip Address for eu-west-1b
    Value: !GetAtt EfsMountTargets.eu-west-1b.IpAddress
```
The above assumes that `Map` was a first-class property of resources, for convenience. The general-purpose intrinsic function could look like this:
```yaml
# with !Ref AZs being [a, b]
!Map:
  - AZ: !Sub "${AWS::Region}${x}"
  - x: !Ref AZs
```
equivalent to

```yaml
- !Sub "${AWS::Region}a"
- !Sub "${AWS::Region}b"
```
