### ISSUE TITLE
AWS::CodeDeploy::Application deployment fails when 'Tags' updated

### ISSUE THREAD

**Issue by nom3ad** [aws-cloudformation/cloudformation-coverage-roadmap#946]
### Name of the resource

Other

### Resource Name

AWS::CodeDeploy::Application

### Issue Description

According to this [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-application.html),  CodeDeploy application supports tags.   And tags are supposed to be updatable without any replacement.   But such deployment won't be successful as of now.  (tested in `us-east-1`)

### Expected Behavior

Tags should be updated without interruption

### Observed Behavior

Deployment fails with an error:

`Update to resource type AWS::CodeDeploy::Application is not supported.`

### Test Cases

1. Deploy following.  (tested in `us-east-1`)
```yaml
Resources:
  ServerApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server
      Tags:
        - Key: Environment
          Value: foo
```
2. Updated deployment  with
```yaml
Resources:
  ServerApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ComputePlatform: Server
      Tags:
        - Key: Environment
          Value: bar    # tag value was changed
```

### Other Details

AWS CDK was updated with [CloudFormation spec v39.5.0](https://github.com/aws/aws-cdk/pull/15536/files?authenticity_token=ZzwdcaDgM%2Fs5pmPKbVu8d%2FD4i7gzh6JLIEMszTSvPLFDIyP2syxuCWxmRb0LGEa%2BDSLslNa%2F9gwK146pJqHXfA%3D%3D&file-filters%5B%5D=.md&file-filters%5B%5D=.ts-fixture#r730243609)  that supposed to  support CodeDeploy application tagging properly. 

This seems to be the root cause on the example provided in https://github.com/aws/aws-cdk/issues/15947
