### ISSUE TITLE
AWS::Events::Rule / MaximumRetryAttempts causes drift detection false-positive

### ISSUE THREAD

**Issue by tstibbs** [aws-cloudformation/cloudformation-coverage-roadmap#956]
### Name of the resource

AWS::Events::Rule

### Resource Name

AWS::Events::Rule

### Issue Description

Drift detection reports drift on a `Rule` which has `MaximumRetryAttempts`, even if the resource is in sync.

### Expected Behavior

Resource should not be reported as drifted if both the rule and the cloudformation template specify the same value for `MaximumRetryAttempts`.

### Observed Behavior

Resource is marked as drifted even though both the rule and the cloudformation template specify the same value for `MaximumRetryAttempts`.

### Test Cases

1. Deploy a stack with the following template: 
    ```
    Resources:
      LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
          RetentionInDays: 3
          LogGroupName: '/aws/events/LogGroup-Test'

      Rule:
        Type: AWS::Events::Rule
        Properties:
          ScheduleExpression: cron(0 0 * * ? *)
          State: ENABLED
          Targets:
            - Id: 'CloudwatchLogsTarget'
              Arn: !GetAtt LogGroup.Arn
              RetryPolicy:
                MaximumRetryAttempts: 4
    ```
1. Run drift detect
1. Note that drift detection immediately reports that the rule does not have the `MaximumRetryAttempts` value set at all.
