### ISSUE TITLE
AWS::EC2::LaunchTemplate Launch Template Tags are not updated when TagSpecifications property has changed

### ISSUE THREAD

**Issue by mattsperle** [aws-cloudformation/cloudformation-coverage-roadmap#957]
### Name of the resource

AWS::EC2::LaunchTemplate

### Issue Description

Updating an existing AWS::EC2::LaunchTemplate with a new tag in a CloudFormation template fails to add the tag to the resource. Updating an existing tag with a new value fails to update the tag as well.

```
Type: AWS::EC2::LaunchTemplate
    Properties:
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
          - Key: NewTag
            Value: NewValue
          - Key: ExistingTag
          - Value: NewValue
```

### Expected Behavior

The Launch Template would be updated with the new tag added or the existing tag updated.

### Observed Behavior

1. The AWS::EC2::LaunchTemplate was updated with a new tag, but the new tag was not added.
2. The AWS::EC2::LaunchTemplate was updated with a new value for an existing tag, but the tag was not updated.

### Test Cases

- Add a tag to AWS::EC2::LaunchTemplate TagSpecification property and update a CloudFormation Stack.
- Update an existing tags value in AWS::EC2::LaunchTemplate TagSpecification property or through a parameter and update a CloudFormation Stack.
