### ISSUE TITLE
AWS::CloudFront::Distribution Custom Response Headers

### ISSUE THREAD

**Issue by ueokande** [aws-cloudformation/cloudformation-coverage-roadmap#969]
### Name of the resource

AWS::CloudFront::Distribution

### Description

CloudFront Distribution now provides custom response headers.
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-cloudfront-supports-cors-security-custom-http-response-headers/

It is available on the CloudFront Console and the [APIs](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DefaultCacheBehavior.html#cloudfront-Type-DefaultCacheBehavior-ResponseHeadersPolicyId).  I hope the [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html) also supports it.

**Comment by ueokande** [comment]
[ResponseHeadersPolicyId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-responseheaderspolicyid) is now available.  Thank you.

**Comment by GrahamCampbell** [comment]
@zjinmei While this appears in the docs, it doesn't actually work on us-east-1 (as of this time yesterday). My document is rejected with error `#/DistributionConfig/DefaultCacheBehavior: extraneous key [ResponseHeadersPolicyId] is not permitted`.

**Comment by GrahamCampbell** [comment]
cc @ueokande

**Comment by GrahamCampbell** [comment]
Tried it again just now. Same issue.

**Comment by GrahamCampbell** [comment]
Any news here? Excited to use this, but am blocked on this.

**Comment by homie-du** [comment]
I am experiencing the same issue when I use serverless framework.

+ serverless.yml
```
    CF:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            ResponseHeadersPolicyId: a323da2a-065c-43c9-a263-289cf629c834
```

+ result
```
  An error occurred: CF - Properties validation failed for resource CF with message:
  #/DistributionConfig/DefaultCacheBehavior: extraneous key [responseHeadersPolicyId] is not permitted.
```
