### ISSUE TITLE
DocumentDB Indexes

### ISSUE THREAD

**Issue by ronkorving** [aws-cloudformation/cloudformation-coverage-roadmap#976]
### Name of the resource

AWS::DocDB::DBCluster

### Description

It could, under certain circumstances, be very helpful if DocumentDB collection indexes could be made via a CloudFormation resource. Would love to hear thoughts from other users too on this, in case I may have missed an obvious lifecycle-related best opportunity for index creation. But CloudFormation resources to me seem like they would make creation/deletion very seamless.

### Other Details

I was thinking something along these lines:

```yaml
MyCollectionIndex:
  Type: AWS::DocDb::Index
  Properties:
    SecretId: !Ref MyDocumentDbCredentials
    CollectionName: myCollection
    Name: myIndex
    Keys:
      - Field: myField
        Order: asc # either "asc" or "desc"
    Unique: false # either true or false (optional, default: false)
    Sparse: false # either true or false (optional, default: false)
```
