### ISSUE TITLE
AWS::WorkSpaces::Workspace does not have stack-level tags

### ISSUE THREAD

**Issue by madeline-k** [aws-cloudformation/cloudformation-coverage-roadmap#985]
### Name of the resource

Other

### Resource Name

AWS::WorkSpaces::Workspace

### Issue Description

Stack-level tags are not created for an AWS:WorkSpaces::Workspace resource as documented [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html). 

This issue was originally reported in the CDK repo, but I believe it is a CloudFormation issue: https://github.com/aws/aws-cdk/issues/17139 

Create a Cloudformation Stack with an Amazon Prometheus Workspace:

```typescript
import * as cdk from '@aws-cdk/core';
import { CfnWorkspace } from '@aws-cdk/aws-aps';

export class HelloCdkStack extends cdk.Stack {
  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);
    this.createWorkspace()
  }
  
  private createWorkspace(): void {
      const aliasName = `alias-name`
      new CfnWorkspace(this, `SomeWorkspace`, {
          alias: aliasName
      })
  }
}
```

CFN template:

```yaml
Resources:
  SomeWorkspace:
    Type: AWS::APS::Workspace
    Properties:
      Alias: alias-name
    Metadata:
      aws:cdk:path: ProdSampleAppStack3/SomeWorkspace
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/yWLMQrDMAxFz5LdUWq30LWQG6RDZyOr4JhaQZLTIeTuTej0H+/xPfjrDS7dI361x1SGDVkItqdFLG7kqiYNzY3vOpFyE6STj5CyZa67O49xUTjsi6XoEpF2VzkRzDqsPkAIcO9mzbmXVi1/CKb//gDW+CwXfQAAAA==
    Metadata:
      aws:cdk:path: ProdSampleAppStack3/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
   ...
```

### Expected Behavior

A workspace created with stack-level tags with the prefix `aws:`

```
aws:cloudformation:logical-id

aws:cloudformation:stack-id

aws:cloudformation:stack-name

```

### Observed Behavior

A workspace created without `aws:` tags.

### Test Cases

Create a new AWS::WorkSpaces::Workspace, and verify presence of stack-level tags on the resource.
